"""Websocket module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="websocket",
    group_name="websocket_websocket_status",
    title="Websocket Get Websocket Status (GET) (SSOT)",
    description="Get enhanced WebSocket connection status",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.websocket.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="websocket",
    group_name="websocket_user_connections",
    title="Websocket Get User Connections (GET) (SSOT)",
    description="Get WebSocket connections for a specific user",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.websocket.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="websocket",
    group_name="websocket_send_notification_to_user",
    title="Websocket Send Notification To User (POST) (SSOT)",
    description="Send a notification to a specific user via WebSocket",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.websocket.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="websocket",
    group_name="websocket_broadcast_notification",
    title="Websocket Broadcast Notification (POST) (SSOT)",
    description="Broadcast a notification to all connected users",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.websocket.router",),
    deterministic=False,
))
