"""Tactics module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group


register_function_group(FunctionGroupContract(
    module="tactics",
    group_name="tactics_recommendations",
    title="Tactics Get Recommendations (GET) (SSOT)",
    description="GET /recommendations",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.tactics.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="tactics",
    group_name="tactics_analyze_case",
    title="Tactics Analyze Case (POST) (SSOT)",
    description="POST /analyze",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.tactics.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="tactics",
    group_name="tactics_evidence_checklist",
    title="Tactics Get Evidence Checklist (GET) (SSOT)",
    description="GET /evidence-checklist",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.tactics.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="tactics",
    group_name="tactics_pre_hearing_timeline",
    title="Tactics Get Pre Hearing Timeline (GET) (SSOT)",
    description="GET /pre-hearing-timeline",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.tactics.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="tactics",
    group_name="tactics_check_retaliation",
    title="Tactics Check Retaliation (POST) (SSOT)",
    description="POST /check-retaliation",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.tactics.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="tactics",
    group_name="tactics_check_habitability",
    title="Tactics Check Habitability (POST) (SSOT)",
    description="POST /check-habitability",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.tactics.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="tactics",
    group_name="tactics_check_service_timeline",
    title="Tactics Check Service Timeline (GET) (SSOT)",
    description="GET /service-check",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.tactics.router",),
    deterministic=True,
))
