"""Workflow module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(
    FunctionGroupContract(
        module="workflow",
        group_name="workflow_route_decision",
        title="Workflow Get Route Decision (POST) (SSOT)",
        description="Return a deterministic routing decision for the given role + storage state.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.workflow.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="workflow",
        group_name="workflow_advance_workflow",
        title="Workflow Advance Workflow (POST) (SSOT)",
        description="Gate-based transition endpoint.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.workflow.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="workflow",
        group_name="workflow_next_step",
        title="Workflow Get Next Step (POST) (SSOT)",
        description="Determine the single best deterministic next step from current case state.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.workflow.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="workflow",
        group_name="workflow_case_state",
        title="Workflow Get Case State (GET) (SSOT)",
        description="Derive real case-state signals from persisted artifacts.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.workflow.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="workflow",
        group_name="workflow_process_groups",
        title="Workflow List Process Groups (GET) (SSOT)",
        description="Return all 8 process groups, optionally filtered by role.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.workflow.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="workflow",
        group_name="workflow_contracts",
        title="Workflow List Contracts (GET) (SSOT)",
        description="Return all registered page contracts (summary view).",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.workflow.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="workflow",
        group_name="workflow_page_contract",
        title="Workflow Get Page Contract (GET) (SSOT)",
        description="Return the full page contract for a specific page.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.workflow.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="workflow",
        group_name="workflow_contract_health",
        title="Workflow Contract Health (GET) (SSOT)",
        description="Run the contract validation suite and return a health report.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.workflow.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="workflow",
        group_name="workflow_module_contracts",
        title="Workflow List Module Contracts (GET) (SSOT)",
        description="Return all registered function-group (module) contracts.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.workflow.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="workflow",
        group_name="workflow_help_telemetry_summary",
        title="Workflow Help Telemetry Summary (GET) (SSOT)",
        description="Aggregate help-related click telemetry from the positronic brain event history.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.workflow.router",),
        deterministic=True,
    )
)
