"""Hud_Funding module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group


register_function_group(FunctionGroupContract(
    module="hud_funding",
    group_name="hud_funding_all_programs",
    title="Hud_Funding List All Programs (GET) (SSOT)",
    description="GET /programs",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.hud_funding.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="hud_funding",
    group_name="hud_funding_program_details",
    title="Hud_Funding Get Program Details (GET) (SSOT)",
    description="GET /programs/{program_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.hud_funding.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="hud_funding",
    group_name="hud_funding_program_summary",
    title="Hud_Funding Get Program Summary (GET) (SSOT)",
    description="GET /programs/{program_id}/summary",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.hud_funding.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="hud_funding",
    group_name="hud_funding_search_programs",
    title="Hud_Funding Search Programs (GET) (SSOT)",
    description="GET /search",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.hud_funding.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="hud_funding",
    group_name="hud_funding_tax_credit_programs",
    title="Hud_Funding List Tax Credit Programs (GET) (SSOT)",
    description="GET /tax-credits",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.hud_funding.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="hud_funding",
    group_name="hud_funding_voucher_programs",
    title="Hud_Funding List Voucher Programs (GET) (SSOT)",
    description="GET /voucher-programs",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.hud_funding.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="hud_funding",
    group_name="hud_funding_grant_programs",
    title="Hud_Funding List Grant Programs (GET) (SSOT)",
    description="GET /grants",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.hud_funding.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="hud_funding",
    group_name="hud_funding_landlord_requirements",
    title="Hud_Funding Get Landlord Requirements (GET) (SSOT)",
    description="GET /programs/{program_id}/landlord-requirements",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.hud_funding.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="hud_funding",
    group_name="hud_funding_landlord_eligibility",
    title="Hud_Funding Get Landlord Eligibility (GET) (SSOT)",
    description="GET /programs/{program_id}/landlord-eligibility",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.hud_funding.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="hud_funding",
    group_name="hud_funding_all_landlord_obligations",
    title="Hud_Funding Get All Landlord Obligations (GET) (SSOT)",
    description="GET /all-landlord-obligations",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.hud_funding.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="hud_funding",
    group_name="hud_funding_tenant_recourse",
    title="Hud_Funding Get Tenant Recourse (GET) (SSOT)",
    description="GET /programs/{program_id}/tenant-recourse",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.hud_funding.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="hud_funding",
    group_name="hud_funding_tax_breaks",
    title="Hud_Funding List Tax Breaks (GET) (SSOT)",
    description="GET /tax-breaks",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.hud_funding.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="hud_funding",
    group_name="hud_funding_tax_break",
    title="Hud_Funding Get Tax Break (GET) (SSOT)",
    description="GET /tax-breaks/{tax_break_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.hud_funding.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="hud_funding",
    group_name="hud_funding_check_tenant_eligibility",
    title="Hud_Funding Check Tenant Eligibility (POST) (SSOT)",
    description="POST /check-eligibility",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.hud_funding.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="hud_funding",
    group_name="hud_funding_check_property_programs",
    title="Hud_Funding Check Property Programs (GET) (SSOT)",
    description="GET /check-property",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.hud_funding.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="hud_funding",
    group_name="hud_funding_compare_programs",
    title="Hud_Funding Compare Programs (GET) (SSOT)",
    description="GET /compare",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.hud_funding.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="hud_funding",
    group_name="hud_funding_quick_reference",
    title="Hud_Funding Quick Reference (GET) (SSOT)",
    description="○ Quick reference guide for understanding HUD programs.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.hud_funding.router",),
    deterministic=True,
))
