"""Plugins module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="plugins",
    group_name="plugins_plugins",
    title="Plugins List Plugins (GET) (SSOT)",
    description="GET /",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.plugins.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="plugins",
    group_name="plugins_plugin",
    title="Plugins Get Plugin (GET) (SSOT)",
    description="GET /{plugin_name}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.plugins.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="plugins",
    group_name="plugins_load_plugin",
    title="Plugins Load Plugin (POST) (SSOT)",
    description="POST /{plugin_name}/load",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.plugins.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="plugins",
    group_name="plugins_unload_plugin",
    title="Plugins Unload Plugin (POST) (SSOT)",
    description="POST /{plugin_name}/unload",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.plugins.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="plugins",
    group_name="plugins_execute_plugin_action",
    title="Plugins Execute Plugin Action (POST) (SSOT)",
    description="POST /{plugin_name}/action/{action_name}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.plugins.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="plugins",
    group_name="plugins_browse_marketplace",
    title="Plugins Browse Marketplace (GET) (SSOT)",
    description="GET /marketplace/browse",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.plugins.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="plugins",
    group_name="plugins_plugin_system_health",
    title="Plugins Plugin System Health (GET) (SSOT)",
    description="Get plugin system health status.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.plugins.router",),
    deterministic=True,
))
