"""Expanded Law Library entries.

Adds coverage for service/emotional support animals, vulnerable adults,
commerce and leasing law, landlord-tenant accountability, and HUD / low-income
housing programs. Imported into the Law Library router and merged into ALL_LAWS.
"""

EXPANDED_LAWS = {
    # === HUD / low-income rental assistance ===
    "hud_housing_choice_voucher": {
        "id": "hud_housing_choice_voucher",
        "title": "Housing Choice Voucher Program (Section 8)",
        "citation": "42 U.S.C. § 1437f",
        "category": "housing_assistance",
        "subcategory": "federal_rental_assistance",
        "jurisdiction": "federal",
        "summary": "HUD program that helps very low-income families, older adults, and people with disabilities afford decent, safe, and sanitary housing in the private market.",
        "key_points": [
            "Tenant-based vouchers move with the tenant",
            "Project-based vouchers are tied to a specific property",
            "Families pay roughly 30% of adjusted income for rent",
            "Landlords must meet HUD housing quality standards",
            "Participants have due-process rights in voucher terminations",
            "Landlord participation is voluntary in most jurisdictions",
            "VAWA protections apply to voucher holders",
        ],
        "full_text": "The Secretary of Housing and Urban Development is authorized to make housing assistance payments to or on behalf of the tenant, including direct payments to a public housing agency for project-based assistance, or to private landlords on behalf of very low-income families.",
        "related_forms": ["voucher_renewal_request", "portability_request", "hqs_complaint"],
        "effective_date": "1974-08-22",
        "enforcement": "HUD Office of Public and Indian Housing (PIH); PHAs",
        "penalties": "Voucher termination, repayment agreements, administrative hearings",
    },
    "hud_public_housing": {
        "id": "hud_public_housing",
        "title": "Public Housing Program",
        "citation": "42 U.S.C. § 1437",
        "category": "housing_assistance",
        "subcategory": "federal_rental_assistance",
        "jurisdiction": "federal",
        "summary": "HUD program that provides affordable rental housing for eligible low-income families, older adults, and persons with disabilities through publicly owned and operated developments.",
        "key_points": [
            "Owned and operated by public housing authorities (PHAs)",
            "Rent is generally set at 30% of adjusted income",
            "Residents have grievance and hearing rights",
            "PHAs must comply with federal regulations and ACC contracts",
            "Evictions require due process and good cause",
            "Accessible units required for residents with disabilities",
        ],
        "full_text": "The Secretary is authorized to provide financial assistance to public housing agencies for the development, acquisition, and operation of public-housing projects and for related housing assistance.",
        "related_forms": ["pha_grievance", "public_housing_lease"],
        "effective_date": "1937-09-01",
        "enforcement": "HUD; PHAs; federal courts",
        "penalties": "Lease termination, informal hearings, civil rights complaints",
    },
    "lihtc": {
        "id": "lihtc",
        "title": "Low-Income Housing Tax Credit (LIHTC)",
        "citation": "26 U.S.C. § 42",
        "category": "housing_assistance",
        "subcategory": "federal_housing_finance",
        "jurisdiction": "federal",
        "summary": "Federal tax-credit program that encourages private investment in affordable rental housing for low-income households.",
        "key_points": [
            "Tax credits are allocated to states and then to developers",
            "Units must remain affordable for a minimum compliance period (usually 30 years)",
            "Income restrictions apply to tenants",
            "Rent limits are set by HUD for the area",
            "Owners must follow state agency compliance rules",
            "Tenant protections vary by state and local agreements",
        ],
        "full_text": "The amount of the low-income housing credit for any taxable year is the applicable percentage of the qualified basis of each qualified low-income building.",
        "related_forms": ["lihtc_tenant_income_certification", "rent_limit_inquiry"],
        "effective_date": "1986-10-22",
        "enforcement": "IRS; state housing finance agencies; investors",
        "penalties": "Credit recapture, state agency sanctions, lease non-renewal",
    },
    "project_based_section8": {
        "id": "project_based_section8",
        "title": "Project-Based Section 8",
        "citation": "42 U.S.C. § 1437f",
        "category": "housing_assistance",
        "subcategory": "federal_rental_assistance",
        "jurisdiction": "federal",
        "summary": "Federal rental assistance tied to a specific property or unit rather than a tenant. The subsidy stays with the unit.",
        "key_points": [
            "Subsidy is attached to the unit, not the family",
            "Tenant income must continue to qualify",
            "Owners must maintain HUD housing quality standards",
            "Tenants have lease and grievance protections",
            "If tenant moves, the assistance does not follow",
            "VAWA protections apply",
        ],
        "full_text": "Housing assistance payments made on a project basis to owners of eligible housing units for very low-income families, subject to annual contributions contracts with HUD.",
        "related_forms": ["project_based_lease", "hqs_complaint"],
        "effective_date": "1974-08-22",
        "enforcement": "HUD; property owners; housing agencies",
        "penalties": "Contract termination, rent adjustments, tenant recertification",
    },
    "home_investment_partnerships": {
        "id": "home_investment_partnerships",
        "title": "HOME Investment Partnerships Program",
        "citation": "42 U.S.C. § 12722",
        "category": "housing_assistance",
        "subcategory": "federal_housing_finance",
        "jurisdiction": "federal",
        "summary": "Federal block-grant program to states and localities for affordable housing and low-income homeownership.",
        "key_points": [
            "Funds can be used for rental housing, tenant-based rental assistance, and homeownership",
            "At least 90% of assisted families must be low-income",
            "Participating jurisdictions (PJs) administer funds",
            "May include income limits and rent limits",
            "Tenant and homebuyer protections apply",
        ],
        "full_text": "The Secretary shall, in accordance with this subchapter, make grants to participating jurisdictions for affordable housing activities.",
        "related_forms": ["home_rental_application", "pj_complaint"],
        "effective_date": "1990-11-28",
        "enforcement": "HUD; state and local PJs",
        "penalties": "Grant repayment, program sanctions, local enforcement",
    },
    "national_housing_trust_fund": {
        "id": "national_housing_trust_fund",
        "title": "National Housing Trust Fund",
        "citation": "42 U.S.C. § 4568",
        "category": "housing_assistance",
        "subcategory": "federal_housing_finance",
        "jurisdiction": "federal",
        "summary": "Federal housing fund that provides states with funding to increase and preserve the supply of rental housing for extremely and very low-income households.",
        "key_points": [
            "Capitalized by a small percentage of Fannie Mae and Freddie Mac business earnings",
            "Funds are allocated to states by formula",
            "Must primarily benefit extremely low-income families",
            "States design their own programs within HUD guidelines",
            "Can be used for rental, operating, and housing-support services",
        ],
        "full_text": "There is established in the Treasury of the United States a fund to be known as the 'Housing Trust Fund', which shall be available to the Secretary to provide affordable housing assistance.",
        "related_forms": ["htf_application", "state_htf_inquiry"],
        "effective_date": "2008-07-30",
        "enforcement": "HUD; state housing agencies",
        "penalties": "Funding recapture, program restrictions",
    },
    "hud_income_limits": {
        "id": "hud_income_limits",
        "title": "HUD Income Limits for Assisted Housing",
        "citation": "42 U.S.C. § 1437a",
        "category": "housing_assistance",
        "subcategory": "federal_rental_assistance",
        "jurisdiction": "federal",
        "summary": "Defines income-eligibility thresholds (very low income, extremely low income, low income) for HUD-assisted and many affordable housing programs.",
        "key_points": [
            "Income limits are published annually by HUD for each metro area and county",
            "Used for Section 8 vouchers, public housing, LIHTC, and other programs",
            "Extremely low income is generally 30% of area median income",
            "Very low income is generally 50% of area median income",
            "Low income is generally 80% of area median income",
            "Household size matters for eligibility",
        ],
        "full_text": "The Secretary shall prescribe income limits for admission to federally assisted housing, based on area median income and adjusted for family size.",
        "related_forms": ["income_recalculation_request", "utility_allowance_inquiry"],
        "effective_date": "1974-08-22",
        "enforcement": "HUD; PHAs; property owners",
        "penalties": "Overpayment recovery, lease termination, program disqualification",
    },

    # === Service and emotional support animals ===
    "service_animals_fha": {
        "id": "service_animals_fha",
        "title": "Service Animals in Housing (FHA)",
        "citation": "42 U.S.C. § 3604(f)",
        "category": "service_animals",
        "subcategory": "fha_assistance_animals",
        "jurisdiction": "federal",
        "summary": "Under the Fair Housing Act, assistance animals are not 'pets' and must be accommodated in housing when needed by a person with a disability.",
        "key_points": [
            "Dogs and other animals can be assistance animals",
            "Assistance animals perform work, tasks, or provide emotional support",
            "No breed, size, or weight restrictions apply by default",
            "Landlords can request reliable disability-related documentation if not apparent",
            "Cannot charge pet fees or deposits, but tenant is liable for damage",
            "Public accommodations (ADA) rules are stricter and require a service dog",
        ],
        "full_text": "Discrimination includes a refusal to make reasonable accommodations in rules, policies, practices, or services, when such accommodations may be necessary to afford a person with a disability an equal opportunity to use and enjoy a dwelling, including the right to keep an assistance animal.",
        "related_forms": ["reasonable_accommodation_request", "assistance_animal_request"],
        "effective_date": "1988-09-13",
        "enforcement": "HUD; DOJ; federal courts",
        "penalties": "Actual and punitive damages, injunctive relief, attorney fees",
    },
    "emotional_support_animals_hud": {
        "id": "emotional_support_animals_hud",
        "title": "Emotional Support Animals in Housing (HUD)",
        "citation": "HUD FHEO Notice 2020-01",
        "category": "service_animals",
        "subcategory": "hud_guidance",
        "jurisdiction": "federal",
        "summary": "HUD guidance explaining when housing providers must accept emotional support animals as a reasonable accommodation under the Fair Housing Act.",
        "key_points": [
            "Emotional support animals provide disability-related support even without training",
            "Housing providers may confirm disability and need if not readily apparent",
            "Internet certificates alone are not reliable documentation",
            "Providers cannot charge pet fees, but may charge for damage",
            "Breed, size, or weight restrictions alone are not valid reasons to deny",
            "Unique animals require a stronger showing of necessity",
        ],
        "full_text": "Housing providers must evaluate a request for a reasonable accommodation to possess an assistance animal in a dwelling using the general principles applicable to all reasonable accommodation requests under the Fair Housing Act.",
        "related_forms": ["assistance_animal_request", "hud_assistance_animal_complaint"],
        "effective_date": "2020-01-28",
        "enforcement": "HUD Office of Fair Housing and Equal Opportunity",
        "penalties": "HUD complaint process, civil action, administrative penalties",
    },
    "ada_service_animals_public_accommodations": {
        "id": "ada_service_animals_public_accommodations",
        "title": "Service Animals Under the ADA",
        "citation": "28 C.F.R. § 36.104",
        "category": "service_animals",
        "subcategory": "ada_public_accommodations",
        "jurisdiction": "federal",
        "summary": "Title II and Title III of the ADA define service animals as dogs (and miniature horses in some cases) trained to do work or perform tasks for a person with a disability in public spaces.",
        "key_points": [
            "Only dogs are service animals under ADA; miniature horses may qualify separately",
            "Must be trained to perform a task related to the disability",
            "Emotional support animals are not service animals under the ADA",
            "Applies to public accommodations and state/local government services",
            "In housing, the Fair Housing Act is usually broader",
            "No certification or special tag required",
        ],
        "full_text": "Service animal means any dog that is individually trained to do work or perform tasks for the benefit of an individual with a disability, including a physical, sensory, psychiatric, intellectual, or other mental disability.",
        "related_forms": ["ada_complaint", "reasonable_modification_request"],
        "effective_date": "2010-09-15",
        "enforcement": "DOJ Civil Rights Division; DOJ complaints",
        "penalties": "Civil penalties, injunctive relief, attorney fees",
    },
    "minnesota_service_animal_law": {
        "id": "minnesota_service_animal_law",
        "title": "Minnesota Service Animal Law",
        "citation": "Minn. Stat. § 256C.02",
        "category": "service_animals",
        "subcategory": "state_service_animals",
        "jurisdiction": "state",
        "summary": "Minnesota law protects the rights of people with disabilities to be accompanied by service animals in public places and housing.",
        "key_points": [
            "Service animals in training also covered in some situations",
            "Places of public accommodation must allow service animals",
            "Housing providers must comply with state and federal disability laws",
            "No extra charge for service animal",
            "Handler is responsible for care and supervision",
        ],
        "full_text": "A person with a disability has the right to be accompanied by a service animal in all public accommodations and shall not be required to pay extra compensation.",
        "related_forms": ["service_animal_complaint", "reasonable_accommodation_request"],
        "effective_date": "2004-01-01",
        "enforcement": "Minnesota Department of Human Rights; state courts",
        "penalties": "Civil penalties, injunctive relief, damages",
    },

    # === Vulnerable adults ===
    "minnesota_vulnerable_adults_act": {
        "id": "minnesota_vulnerable_adults_act",
        "title": "Minnesota Vulnerable Adults Act",
        "citation": "Minn. Stat. § 626.557",
        "category": "vulnerable_adults",
        "subcategory": "mandatory_reporting",
        "jurisdiction": "state",
        "summary": "Minnesota's central law for reporting and investigating maltreatment of vulnerable adults, including abuse, neglect, and financial exploitation.",
        "key_points": [
            "Vulnerable adults include older adults, people with disabilities, and those receiving services",
            "Certain professionals and facility staff must report suspected maltreatment",
            "Reports go to the Minnesota Adult Abuse Reporting Center (MAARC)",
            "Investigations can lead to protective services, law enforcement, or licensing action",
            "Failure to report by mandated reporters is a misdemeanor",
            "Reporter identity is protected",
        ],
        "full_text": "The legislature finds that vulnerable adults have the right to live free from maltreatment and that the state has a duty to protect them through a reporting and investigation system.",
        "related_forms": ["vulnerable_adult_report", "protective_services_petition"],
        "effective_date": "1980-01-01",
        "enforcement": "Minnesota Department of Human Services; county agencies; law enforcement",
        "penalties": "Misdemeanor for failure to report; civil penalties for providers",
    },
    "minnesota_adult_protective_services": {
        "id": "minnesota_adult_protective_services",
        "title": "Adult Protective Services (APS)",
        "citation": "Minn. Stat. § 626.5571",
        "category": "vulnerable_adults",
        "subcategory": "protective_services",
        "jurisdiction": "state",
        "summary": "Authorizes counties to provide protective services to vulnerable adults who are being or have been maltreated and cannot protect themselves.",
        "key_points": [
            "Services are voluntary unless court-ordered",
            "Can include emergency shelter, medical care, financial management, and legal services",
            "Least-restrictive alternative is required",
            "May petition for guardianship or conservatorship if necessary",
            "Advocates for client self-determination",
        ],
        "full_text": "The county social service agency shall provide protective services to a vulnerable adult who has been reported to be maltreated, or is believed to be in need of protection, and who consents to the services.",
        "related_forms": ["aps_referral", "protective_services_plan"],
        "effective_date": "1995-01-01",
        "enforcement": "County adult protection units; DHS",
        "penalties": "Licensing action; court intervention",
    },
    "minnesota_financial_exploitation_vulnerable_adults": {
        "id": "minnesota_financial_exploitation_vulnerable_adults",
        "title": "Financial Exploitation of Vulnerable Adults",
        "citation": "Minn. Stat. § 609.2325",
        "category": "vulnerable_adults",
        "subcategory": "financial_abuse",
        "jurisdiction": "state",
        "summary": "Criminal statute penalizing the financial exploitation of a vulnerable adult, including misuse of funds, property, or identity by a person in a position of trust.",
        "key_points": [
            "Includes theft, misuse, and unauthorized use of funds or property",
            "Applies to caregivers, family members, and those with authority over a vulnerable adult",
            "Severity of charge depends on value and circumstances",
            "Victims may also pursue civil remedies",
            "Mandated reporters must report suspected exploitation",
        ],
        "full_text": "Whoever, having a legal duty or exercising temporary or permanent control over a vulnerable adult or vulnerable adult's property, intentionally uses the property of the vulnerable adult for the actor's own advantage or benefit is guilty of financial exploitation.",
        "related_forms": ["financial_exploitation_report", "conservatorship_petition"],
        "effective_date": "1995-01-01",
        "enforcement": "Law enforcement; county attorneys; DHS",
        "penalties": "Criminal penalties by value; restitution; civil liability",
    },
    "vulnerable_adult_housing_protections": {
        "id": "vulnerable_adult_housing_protections",
        "title": "Vulnerable Adult Housing and Tenancy Protections",
        "citation": "Minn. Stat. § 504B",
        "category": "vulnerable_adults",
        "subcategory": "landlord_tenant",
        "jurisdiction": "state",
        "summary": "Minnesota landlord-tenant law applies to all adults, including vulnerable adults; additional protections may arise through adult protection, conservatorship, or fair housing accommodations.",
        "key_points": [
            "Tenants with disabilities may request reasonable accommodations",
            "Caregivers or representatives can act with proper authority",
            "Adult protection can intervene in landlord-tenant disputes involving abuse or neglect",
            "Conservatorship can help manage rent and finances",
            "Retaliation protections still apply",
        ],
        "full_text": "Minnesota landlord and tenant law governs the rental relationship and does not exclude vulnerable adults. Reasonable accommodations, representative authority, and adult protective services may intersect in individual cases.",
        "related_forms": ["reasonable_accommodation_request", "conservatorship_petition"],
        "effective_date": "1999-08-01",
        "enforcement": "Minnesota District Courts; DHS; county APS",
        "penalties": "Eviction defense, civil remedies, protective orders",
    },

    # === Commerce / landlord-tenant contracts ===
    "ucc_article_2a_leases": {
        "id": "ucc_article_2a_leases",
        "title": "Uniform Commercial Code (UCC) — Leases",
        "citation": "Minn. Stat. § 336.2A",
        "category": "commerce",
        "subcategory": "ucc_leases",
        "jurisdiction": "state",
        "summary": "Minnesota's adopted UCC Article 2A governs leases of goods, including consumer and commercial leases, and provides default rules for lease formation, warranties, and remedies.",
        "key_points": [
            "Applies to the lease of goods, not real estate",
            "Provides default rules for lease agreements",
            "Covers express and implied warranties",
            "Gives remedies for default by lessor or lessee",
            "May not fully apply to residential real-property leases",
            "Useful for equipment, appliances, and other tangible goods",
        ],
        "full_text": "This article applies to any transaction, regardless of its form, that creates a lease of goods.",
        "related_forms": ["lease_agreement", "warranty_claim"],
        "effective_date": "2001-08-01",
        "enforcement": "Minnesota courts",
        "penalties": "Damages, repossession, contract rescission",
    },
    "landlord_tenant_as_contract": {
        "id": "landlord_tenant_as_contract",
        "title": "Landlord-Tenant Relationship as Contract",
        "citation": "Minn. Stat. § 504B",
        "category": "commerce",
        "subcategory": "lease_contract",
        "jurisdiction": "state",
        "summary": "A residential lease is a contract between landlord and tenant. Both parties must follow its terms, and Minnesota law provides minimum standards that cannot be waived.",
        "key_points": [
            "Lease terms must comply with state law",
            "Provisions that waive tenant rights are generally unenforceable",
            "Oral leases are valid for shorter terms",
            "Landlord must provide a copy of the lease",
            "Rent, security deposit, and termination terms must be clear",
            "Breach of lease can lead to eviction or damages",
        ],
        "full_text": "The rights and obligations of landlords and tenants are governed by the lease agreement and by chapter 504B, which establishes minimum protections that may not be waived.",
        "related_forms": ["lease_agreement", "lease_termination_notice"],
        "effective_date": "1999-08-01",
        "enforcement": "Minnesota District Courts",
        "penalties": "Eviction, damages, attorney fees",
    },
    "minnesota_unconscionable_lease_terms": {
        "id": "minnesota_unconscionable_lease_terms",
        "title": "Unconscionable Lease Terms",
        "citation": "Minn. Stat. § 504B.121",
        "category": "commerce",
        "subcategory": "lease_contract",
        "jurisdiction": "state",
        "summary": "Minnesota law prohibits residential lease provisions that are unconscionable, including clauses that waive legal remedies or shift costs unfairly to the tenant.",
        "key_points": [
            "A court may refuse to enforce unconscionable lease terms",
            "Clauses waiving statutory rights are often void",
            "Liquidated-damage clauses are reviewed for fairness",
            "Attorney-fee clauses must be reciprocal",
            "Small-print or complex language is examined for fairness",
        ],
        "full_text": "A provision of a residential lease is void and unenforceable if it is unconscionable or if it purports to waive or limit rights or remedies available to the tenant under this chapter.",
        "related_forms": ["lease_review_request", "unconscionability_motion"],
        "effective_date": "1985-01-01",
        "enforcement": "Minnesota District Courts",
        "penalties": "Void terms, contract reformation, damages",
    },
    "minnesota_lease_renewal_nonrenewal": {
        "id": "minnesota_lease_renewal_nonrenewal",
        "title": "Lease Renewal and Non-Renewal",
        "citation": "Minn. Stat. § 504B.135",
        "category": "commerce",
        "subcategory": "lease_contract",
        "jurisdiction": "state",
        "summary": "Rules for ending or renewing a residential lease, including notice requirements for month-to-month and fixed-term tenancies.",
        "key_points": [
            "Month-to-month tenancies generally require notice equal to the rental period or less",
            "Fixed-term leases expire on their end date unless renewed",
            "Landlord must provide proper notice to terminate",
            "Retaliatory non-renewal may be challenged",
            "Local ordinances may add notice requirements",
        ],
        "full_text": "A landlord or tenant may terminate a tenancy for a definite term by giving notice at least one full rental period before the end of the term.",
        "related_forms": ["lease_termination_notice", "nonrenewal_response"],
        "effective_date": "1999-08-01",
        "enforcement": "Minnesota District Courts",
        "penalties": " wrongful eviction, rent abatement, damages",
    },
    "landlord_commercial_activity": {
        "id": "landlord_commercial_activity",
        "title": "Landlord Commercial Activity and Rental Operations",
        "citation": "Minn. Stat. § 322C; § 333",
        "category": "commerce",
        "subcategory": "landlord_business",
        "jurisdiction": "state",
        "summary": "Landlords operating rental property as a business must comply with entity, licensing, tax, and data-practices laws in Minnesota.",
        "key_points": [
            "Landlords may operate as individuals, LLCs, or other entities",
            "Some cities require rental licenses",
            "Business must report income and expenses for tax purposes",
            "Tenant screening and data handling are regulated",
            "Commercial leases have different rules than residential",
        ],
        "full_text": "The operation of rental property as a business subjects the landlord to general business, tax, licensing, and data-practices requirements in addition to landlord-tenant law.",
        "related_forms": ["rental_license_application", "business_registration"],
        "effective_date": "1999-01-01",
        "enforcement": "Minnesota Secretary of State; Minnesota Department of Revenue; cities",
        "penalties": "Fines, license revocation, tax penalties",
    },

    # === Accountability / enforcement ===
    "hud_fair_housing_complaint_process": {
        "id": "hud_fair_housing_complaint_process",
        "title": "HUD Fair Housing Complaint Process",
        "citation": "24 C.F.R. § 103",
        "category": "accountability",
        "subcategory": "federal_enforcement",
        "jurisdiction": "federal",
        "summary": "The administrative process for filing and resolving discrimination complaints with HUD's Office of Fair Housing and Equal Opportunity (FHEO).",
        "key_points": [
            "Complaint must be filed within one year of the alleged act",
            "HUD investigates and attempts conciliation",
            "If reasonable cause is found, HUD may charge before an administrative law judge",
            "Complainants may elect to have the case heard in federal court",
            "May result in damages, injunctive relief, civil penalties, and attorney fees",
        ],
        "full_text": "Any person aggrieved by a discriminatory housing practice may file a complaint with the Secretary within one year after the alleged discriminatory housing practice occurred.",
        "related_forms": ["hud_fair_housing_complaint", "conciliation_agreement"],
        "effective_date": "1968-04-11",
        "enforcement": "HUD FHEO; DOJ; federal courts",
        "penalties": "Actual and punitive damages, civil penalties up to $150,000, attorney fees",
    },
    "fair_housing_enforcement_rem edies": {
        "id": "fair_housing_enforcement_remedies",
        "title": "Fair Housing Act Enforcement and Remedies",
        "citation": "42 U.S.C. § 3613",
        "category": "accountability",
        "subcategory": "federal_enforcement",
        "jurisdiction": "federal",
        "summary": "Provides private and governmental enforcement rights, remedies, and penalties for Fair Housing Act violations.",
        "key_points": [
            "Private persons may sue in federal or state court",
            "Attorney fees and costs available to prevailing parties",
            "Compensatory and punitive damages available",
            "DOJ may bring civil actions for pattern-or-practice discrimination",
            "Injunctive relief and equitable relief available",
            "Statute of limitations is generally two years",
        ],
        "full_text": "The Attorney General may commence a civil action in any appropriate United States district court against any person that the Attorney General has reasonable cause to believe is engaged in a pattern or practice of resistance to the full enjoyment of any of the rights granted by this subchapter.",
        "related_forms": ["fair_housing_lawsuit", "hud_complaint_form"],
        "effective_date": "1968-04-11",
        "enforcement": "DOJ; HUD; federal and state courts",
        "penalties": "Unlimited compensatory and punitive damages, civil penalties, attorney fees",
    },
    "minnesota_attorney_general_landlord_tenant": {
        "id": "minnesota_attorney_general_landlord_tenant",
        "title": "Minnesota Attorney General Landlord-Tenant Enforcement",
        "citation": "Minn. Stat. § 8.31",
        "category": "accountability",
        "subcategory": "state_enforcement",
        "jurisdiction": "state",
        "summary": "Authorizes the Minnesota Attorney General to investigate and take civil action against deceptive, fraudulent, or illegal landlord practices.",
        "key_points": [
            "Can bring civil actions for consumer fraud and deceptive trade practices",
            "May obtain injunctions, restitution, civil penalties, and attorney fees",
            "Often used for systemic landlord abuses",
            "Tenants can also file private lawsuits under Minn. Stat. § 325F",
            "Complaints can be filed online or by mail",
        ],
        "full_text": "The Attorney General has the authority to investigate and prosecute violations of Minnesota laws that protect consumers, including tenants, from deceptive, fraudulent, and unfair practices.",
        "related_forms": ["ag_complaint", "consumer_fraud_complaint"],
        "effective_date": "1973-01-01",
        "enforcement": "Minnesota Attorney General's Office",
        "penalties": "Civil penalties, restitution, injunctions, attorney fees",
    },
    "minnesota_consumer_fraud_act": {
        "id": "minnesota_consumer_fraud_act",
        "title": "Minnesota Consumer Fraud Act",
        "citation": "Minn. Stat. § 325F.69",
        "category": "accountability",
        "subcategory": "consumer_protection",
        "jurisdiction": "state",
        "summary": "Prohibits deceptive trade practices and false statements in consumer transactions, including rental advertising and lease representations.",
        "key_points": [
            "False or misleading advertising is prohibited",
            "Applies to rental listings, lease terms, and fee disclosures",
            "Private lawsuits allowed with actual damages and attorney fees",
            "Attorney General can enforce",
            "Does not require proof of intent for some violations",
        ],
        "full_text": "The act, use, or employment by any person of any fraud, deception, misleading practice, misrepresentation, or concealment of material fact with intent that others rely thereon in connection with the sale or advertisement of any merchandise is unlawful.",
        "related_forms": ["consumer_fraud_complaint", "ag_complaint"],
        "effective_date": "1973-01-01",
        "enforcement": "Minnesota Attorney General; private lawsuits",
        "penalties": "Actual damages, attorney fees, civil penalties, injunctions",
    },
    "minnesota_deceptive_trade_practices": {
        "id": "minnesota_deceptive_trade_practices",
        "title": "Minnesota Deceptive Trade Practices",
        "citation": "Minn. Stat. § 325F.67",
        "category": "accountability",
        "subcategory": "consumer_protection",
        "jurisdiction": "state",
        "summary": "Lists specific prohibited deceptive acts, such as bait-and-switch, fake discounts, and misrepresenting the characteristics of rental property.",
        "key_points": [
            "Misrepresenting the condition or availability of a unit is prohibited",
            "Bait advertising is unlawful",
            "Passing off used items as new is prohibited",
            "Private right of action and Attorney General enforcement",
            "Important for rental scams and false advertising",
        ],
        "full_text": "A person engages in a deceptive trade practice when, in the course of business, the person knowingly passes off goods or services as those of another, or knowingly makes a false representation as to the source, sponsorship, approval, or certification of goods or services.",
        "related_forms": ["deceptive_trade_complaint", "ag_complaint"],
        "effective_date": "1973-01-01",
        "enforcement": "Minnesota Attorney General; private lawsuits",
        "penalties": "Injunctive relief, civil penalties, damages, attorney fees",
    },
    "tenant_remedies_landlord_accountability": {
        "id": "tenant_remedies_landlord_accountability",
        "title": "Tenant Remedies and Landlord Accountability",
        "citation": "Minn. Stat. § 504B.395",
        "category": "accountability",
        "subcategory": "tenant_remedies",
        "jurisdiction": "state",
        "summary": "Minnesota law gives tenants several remedies when a landlord fails to maintain the property or comply with the lease, including rent abatement, repair-and-deduct, and early termination.",
        "key_points": [
            "Tenant can seek rent abatement for reduced property value",
            "Repair-and-deduct is allowed in some circumstances",
            "Tenant may terminate for material breach",
            "Retaliation is prohibited",
            "Attorney fees may be recoverable",
            "Document all conditions and communications",
        ],
        "full_text": "A tenant may seek any equitable or legal remedy available for breach of the landlord's covenants, including rent abatement, damages, injunction, and termination of the tenancy.",
        "related_forms": ["rent_abatement_request", "repair_and_deduct_notice"],
        "effective_date": "1999-08-01",
        "enforcement": "Minnesota District Courts",
        "penalties": "Damages, rent abatement, lease termination, attorney fees",
    },
    "minneapolis_violations_bureau": {
        "id": "minneapolis_violations_bureau",
        "title": "Minneapolis Housing Inspections and Violations Bureau",
        "citation": "Minneapolis Code § 244",
        "category": "accountability",
        "subcategory": "local_enforcement",
        "jurisdiction": "local",
        "summary": "Minneapolis enforces housing codes through inspections, citations, and orders to correct dangerous or substandard conditions.",
        "key_points": [
            "Tenants and city inspectors can report code violations",
            "Landlords must correct violations within a set time",
            "The city can issue administrative penalties",
            "Emergency repairs can be ordered",
            "Rental license can be revoked for serious or repeated violations",
        ],
        "full_text": "The City of Minneapolis may inspect rental dwellings, issue correction orders, and impose administrative penalties for violations of the housing and rental license code.",
        "related_forms": ["code_violation_complaint", "rental_license_complaint"],
        "effective_date": "2018-01-01",
        "enforcement": "Minneapolis Regulatory Services",
        "penalties": "Fines, correction orders, license revocation",
    },
    "retaliation_protections_accountability": {
        "id": "retaliation_protections_accountability",
        "title": "Retaliation Protections as Accountability",
        "citation": "Minn. Stat. § 504B.285",
        "category": "accountability",
        "subcategory": "retaliation",
        "jurisdiction": "state",
        "summary": "Landlords cannot retaliate against tenants for exercising legal rights, such as reporting code violations or joining a tenant union.",
        "key_points": [
            "Protected activity includes complaints to government and good-faith repair requests",
            "Retaliatory eviction is a defense in court",
            "Retaliatory rent increases are prohibited",
            "Tenant has the burden of showing the landlord's action was retaliatory",
            "Protections do not excuse nonpayment of rent",
        ],
        "full_text": "A landlord may not increase rent, decrease services, or evict a tenant because the tenant has complained to a governmental authority about a code violation or has organized or become a member of a tenants' union.",
        "related_forms": ["retaliation_defense", "tenant_rights_complaint"],
        "effective_date": "1999-08-01",
        "enforcement": "Minnesota District Courts",
        "penalties": "Eviction dismissal, damages, attorney fees, restored services",
    },

    # === Additional housing / property basics ===
    "housing_quality_standards": {
        "id": "housing_quality_standards",
        "title": "HUD Housing Quality Standards (HQS)",
        "citation": "24 C.F.R. § 982.401",
        "category": "accountability",
        "subcategory": "housing_quality",
        "jurisdiction": "federal",
        "summary": "Minimum health and safety standards that units must meet before a family can move into HUD-assisted housing and periodically thereafter.",
        "key_points": [
            "Covers sanitary facilities, food preparation, space and security, thermal environment, illumination, electricity, structure, and smoke detectors",
            "PHAs or their inspectors perform inspections",
            "Landlord must correct HQS failures",
            "Tenant may be abated if HQS failures persist",
            "Applies to Section 8 vouchers and project-based assistance",
        ],
        "full_text": "A dwelling unit must meet HUD housing quality standards and any additional PHA quality standards in order to be approved for or continue participation in the Section 8 program.",
        "related_forms": ["hqs_inspection_request", "hqs_failure_appeal"],
        "effective_date": "1974-08-22",
        "enforcement": "PHAs; HUD",
        "penalties": "Unit disapproval, payment abatement, contract termination",
    },
    "reasonable_accommodation_hud": {
        "id": "reasonable_accommodation_hud",
        "title": "Reasonable Accommodations in Federally Assisted Housing",
        "citation": "24 C.F.R. § 100.204",
        "category": "service_animals",
        "subcategory": "reasonable_accommodations",
        "jurisdiction": "federal",
        "summary": "HUD regulation implementing the Fair Housing Act requirement that housing providers make reasonable accommodations for persons with disabilities.",
        "key_points": [
            "Accommodation must be necessary for equal use and enjoyment",
            "Cannot impose undue financial or administrative burden",
            "Cannot fundamentally alter the program",
            "Examples include assistance animals, parking, and transfer policies",
            "Request and response should be documented",
        ],
        "full_text": "It shall be unlawful to refuse to make reasonable accommodations in rules, policies, practices, or services, when such accommodations may be necessary to afford a person with a disability an equal opportunity to use and enjoy a dwelling.",
        "related_forms": ["reasonable_accommodation_request", "hud_complaint_form"],
        "effective_date": "1996-03-05",
        "enforcement": "HUD FHEO; DOJ; federal courts",
        "penalties": "Damages, injunctive relief, attorney fees, civil penalties",
    },
    "vawa_protections_expanded": {
        "id": "vawa_protections_expanded",
        "title": "VAWA Housing Protections — Expanded",
        "citation": "34 U.S.C. § 12491",
        "category": "accountability",
        "subcategory": "victim_protections",
        "jurisdiction": "federal",
        "summary": "Expanded summary of housing protections for victims of domestic violence, dating violence, sexual assault, and stalking in federally assisted housing.",
        "key_points": [
            "Victims cannot be evicted or denied housing based on the violence",
            "May terminate lease early without penalty",
            "May request emergency transfer",
            "Confidentiality of victim information required",
            "Notice of VAWA rights must be provided",
            "Also applies to Section 8 vouchers, public housing, LIHTC, and others",
        ],
        "full_text": "A covered housing provider shall not, on the basis of domestic violence, dating violence, sexual assault, or stalking, deny assistance to, or terminate assistance of, an individual who is or has been a victim of such violence.",
        "related_forms": ["vawa_lease_termination", "emergency_transfer_request"],
        "effective_date": "2013-03-07",
        "enforcement": "HUD; DOJ; federal courts",
        "penalties": "Damages, injunctive relief, attorney fees, civil penalties",
    },

    # === Additional commerce and local accountability ===
    "minnesota_prompt_payment_contracts": {
        "id": "minnesota_prompt_payment_contracts",
        "title": "Minnesota Prompt Payment of Contractors and Subcontractors",
        "citation": "Minn. Stat. § 326.975",
        "category": "commerce",
        "subcategory": "prompt_pay",
        "jurisdiction": "state",
        "summary": "Requires owners and prime contractors to pay subcontractors and suppliers within a reasonable time, with interest penalties for late payment.",
        "key_points": [
            "Applies to certain construction and improvement contracts",
            "Late payments accrue interest",
            "May be relevant to repair contractors hired by landlords",
            "Tenant repair-and-deduct receipts can be affected",
            "Does not apply to all residential leases",
        ],
        "full_text": "A prime contractor shall pay a subcontractor within a specified time after receipt of payment from the owner, and shall pay interest on late payments.",
        "related_forms": ["contractor_lien_notice", "payment_demand"],
        "effective_date": "1997-01-01",
        "enforcement": "Minnesota courts; private lawsuits",
        "penalties": "Interest, attorney fees, civil action",
    },
    "minnesota_mechanics_lien": {
        "id": "minnesota_mechanics_lien",
        "title": "Minnesota Mechanic's Lien",
        "citation": "Minn. Stat. § 514.01",
        "category": "commerce",
        "subcategory": "liens",
        "jurisdiction": "state",
        "summary": "Allows contractors, subcontractors, and suppliers who improve real property to record a lien against the property if not paid.",
        "key_points": [
            "Must file a pre-lien notice in many residential cases",
            "Lien must be recorded within a deadline after last work",
            "Foreclosure can force sale of property to pay lien",
            "Important for repair and habitability disputes",
            "Residential tenant repair-and-deduct does not create a lien",
        ],
        "full_text": "Every person who performs labor or furnishes skill, material, or machinery for the improvement of real estate has a lien on that real estate for the value of the labor, skill, material, or machinery.",
        "related_forms": ["mechanics_lien_abstract", "pre_lien_notice"],
        "effective_date": "1985-01-01",
        "enforcement": "Minnesota District Courts",
        "penalties": "Lien foreclosure, forced sale, damages",
    },
    "landlord_tenant_security_minnesota": {
        "id": "landlord_tenant_security_minnesota",
        "title": "Minnesota Landlord-Tenant Security and Access",
        "citation": "Minn. Stat. § 504B.211",
        "category": "tenant_rights",
        "subcategory": "landlord_access",
        "jurisdiction": "state",
        "summary": "Rules for landlord entry into rental units, including notice requirements and tenant privacy rights.",
        "key_points": [
            "Landlord must make a good-faith effort to notify tenant before entry",
            "Reasonable notice is required except for emergencies",
            "Tenant may not unreasonably refuse entry for repairs or showings",
            "Emergency entry allowed for urgent conditions",
            "Harassment through repeated or unjustified entry is prohibited",
        ],
        "full_text": "A landlord may enter the premises only for a reasonable business purpose and after making a good-faith effort to give the tenant reasonable notice under the circumstances.",
        "related_forms": ["landlord_entry_complaint", "privacy_violation_notice"],
        "effective_date": "1999-08-01",
        "enforcement": "Minnesota District Courts",
        "penalties": "Rent abatement, damages, injunctive relief",
    },
    "minnesota_lockouts_self_help": {
        "id": "minnesota_lockouts_self_help",
        "title": "Prohibition of Self-Help Evictions and Lockouts",
        "citation": "Minn. Stat. § 504B.225",
        "category": "tenant_rights",
        "subcategory": "eviction",
        "jurisdiction": "state",
        "summary": "Landlords cannot change locks, shut off utilities, or remove tenant property without a court order; self-help evictions are illegal.",
        "key_points": [
            "Changing locks without court order is illegal",
            "Utility shutoffs are prohibited as retaliation",
            "Tenant may recover damages for illegal lockout",
            "Landlord must use formal court eviction process",
            "Tenant can seek emergency relief",
        ],
        "full_text": "A landlord may not change the locks or otherwise prevent a tenant from entering the leased premises, or cause the termination or interruption of utility service, without a court order.",
        "related_forms": ["illegal_lockout_complaint", "emergency_relief_motion"],
        "effective_date": "1999-08-01",
        "enforcement": "Minnesota District Courts; law enforcement",
        "penalties": "Damages, possession restoration, attorney fees, civil penalties",
    },
    "minnesota_rent_escrow_formal": {
        "id": "minnesota_rent_escrow_formal",
        "title": "Minnesota Rent Escrow Action",
        "citation": "Minn. Stat. § 504B.385",
        "category": "accountability",
        "subcategory": "tenant_remedies",
        "jurisdiction": "state",
        "summary": "Allows a tenant to pay rent into court when a landlord fails to make necessary repairs or comply with the lease.",
        "key_points": [
            "Tenant must give landlord notice of the problem",
            "Court can order repairs and release rent when work is done",
            "Tenant may be awarded rent abatement",
            "A useful alternative to withholding rent",
            "Requires following court procedure",
        ],
        "full_text": "A tenant may bring an action in district court to enforce the landlord's covenants, including rent escrow, repair orders, and rent abatement.",
        "related_forms": ["rent_escrow_petition", "repair_request_notice"],
        "effective_date": "1999-08-01",
        "enforcement": "Minnesota District Courts",
        "penalties": "Court-ordered repairs, rent abatement, costs",
    },
    "st_paul_rental_housing_registry": {
        "id": "st_paul_rental_housing_registry",
        "title": "St. Paul Rental Housing Registry",
        "citation": "St. Paul Legislative Code § 246",
        "category": "accountability",
        "subcategory": "local_enforcement",
        "jurisdiction": "local",
        "summary": "St. Paul requires rental properties to be registered, inspected, and maintained under city rental code standards.",
        "key_points": [
            "Rental properties must be registered with the city",
            "Inspections may be triggered by complaints",
            "Landlords must maintain code compliance",
            "Tenants can report code violations",
            "City can impose fees and penalties",
        ],
        "full_text": "The City of St. Paul requires rental dwelling units to be registered and maintained in compliance with the rental housing code and related ordinances.",
        "related_forms": ["rental_registry_complaint", "code_violation_complaint"],
        "effective_date": "2017-01-01",
        "enforcement": "St. Paul Department of Safety and Inspections",
        "penalties": "Fines, registration revocation, abatement orders",
    },
    "minnesota_tenant_union_protections": {
        "id": "minnesota_tenant_union_protections",
        "title": "Tenant Organizing and Union Protections",
        "citation": "Minn. Stat. § 504B.285",
        "category": "accountability",
        "subcategory": "tenant_rights",
        "jurisdiction": "state",
        "summary": "Minnesota law protects tenants who organize, form tenant associations, or assert their rights, including retaliation protections for group action.",
        "key_points": [
            "Landlords cannot retaliate for tenant organizing",
            "Tenants may collectively address habitability and lease issues",
            "Retaliation presumption may apply after protected activity",
            "Document all communications and group actions",
        ],
        "full_text": "A landlord may not evict, increase rent, decrease services, or terminate a tenancy because the tenant has organized or participated in a tenants' association.",
        "related_forms": ["retaliation_defense", "tenant_association_letter"],
        "effective_date": "1999-08-01",
        "enforcement": "Minnesota District Courts",
        "penalties": "Eviction dismissal, damages, restored services",
    },

    # === More vulnerable adult and human services ===
    "minnesota_vulnerable_adult_emergency_services": {
        "id": "minnesota_vulnerable_adult_emergency_services",
        "title": "Vulnerable Adult Emergency Protective Services",
        "citation": "Minn. Stat. § 626.5571",
        "category": "vulnerable_adults",
        "subcategory": "emergency_services",
        "jurisdiction": "state",
        "summary": "Allows counties to take emergency action, including temporary placement or services, to protect a vulnerable adult in immediate danger.",
        "key_points": [
            "Used when there is imminent risk of harm",
            "Requires a court order for most involuntary actions",
            "Emergency services are temporary",
            "Adult protection works with law enforcement",
            "Client preferences considered when safe",
        ],
        "full_text": "The county may provide emergency protective services to a vulnerable adult when there is reason to believe the adult is in immediate danger of harm.",
        "related_forms": ["emergency_protective_services_request", "aps_referral"],
        "effective_date": "1995-01-01",
        "enforcement": "County adult protection; DHS",
        "penalties": "Court-ordered services, guardianship/conservatorship",
    },
    "minnesota_harassment_of_vulnerable_adult": {
        "id": "minnesota_harassment_of_vulnerable_adult",
        "title": "Harassment of Vulnerable Adults",
        "citation": "Minn. Stat. § 609.749",
        "category": "vulnerable_adults",
        "subcategory": "harassment",
        "jurisdiction": "state",
        "summary": "Minnesota criminal harassment law can protect vulnerable adults from repeated, intrusive, or threatening behavior, including by landlords, neighbors, or caregivers.",
        "key_points": [
            "Harassment requires a course of conduct, not a single incident",
            "Can include phone calls, mail, electronic contact, or following",
            "Victims can seek a harassment restraining order",
            "Landlord-tenant disputes can include harassment claims",
            "Evidence of pattern is important",
        ],
        "full_text": "Whoever engages in a course of conduct directed at a specific person which causes the person to feel frightened, threatened, oppressed, or intimidated may be guilty of harassment.",
        "related_forms": ["harassment_restraining_order", "harassment_report"],
        "effective_date": "1993-01-01",
        "enforcement": "Law enforcement; Minnesota District Courts",
        "penalties": "Criminal penalties, restraining order, contempt",
    },

    # === Federal program administration and landlord rules ===
    "hud_section_8_landlord_obligations": {
        "id": "hud_section_8_landlord_obligations",
        "title": "Section 8 Landlord Obligations",
        "citation": "24 C.F.R. § 982.453",
        "category": "housing_assistance",
        "subcategory": "federal_rental_assistance",
        "jurisdiction": "federal",
        "summary": "Rules that landlords must follow when participating in the Section 8 Housing Choice Voucher program.",
        "key_points": [
            "Must maintain unit in decent, safe, and sanitary condition",
            "Must comply with Housing Quality Standards (HQS)",
            "Must use the HUD model lease or an approved lease",
            "Must not discriminate against voucher holders (in many jurisdictions)",
            "Must cooperate with PHA inspections and rent reasonableness",
            "Must give proper notice before lease termination",
        ],
        "full_text": "The owner must maintain the unit in accordance with HQS, must provide all services, maintenance, equipment, and utilities as agreed to under the lease, and must comply with the terms of the housing assistance payments contract.",
        "related_forms": ["hqs_inspection_request", "section_8_lease"],
        "effective_date": "1974-08-22",
        "enforcement": "PHA; HUD",
        "penalties": "Contract termination, payment abatement, debarment",
    },
    "federal_anti_trafficking_housing": {
        "id": "federal_anti_trafficking_housing",
        "title": "Trafficking Victims Protection and Housing Protections",
        "citation": "22 U.S.C. § 7101",
        "category": "accountability",
        "subcategory": "victim_protections",
        "jurisdiction": "federal",
        "summary": "Federal law that provides protections and services for victims of severe forms of trafficking, which can intersect with housing instability and exploitation.",
        "key_points": [
            "Trafficking survivors may be eligible for housing and services",
            "Certification by HHS may be required for some benefits",
            "Housing providers should not penalize survivors for trafficking-related circumstances",
            "May intersect with VAWA and fair housing protections",
            "Survivors can access legal and social services",
        ],
        "full_text": "The United States shall advance the purposes and provisions of the Trafficking Victims Protection Act by protecting victims, preventing trafficking, and prosecuting traffickers, including through housing and service referrals.",
        "related_forms": ["trafficking_victim_housing_request", "vawa_lease_termination"],
        "effective_date": "2000-10-28",
        "enforcement": "DOJ; HHS; DOL",
        "penalties": "Criminal penalties for traffickers; civil remedies and services for survivors",
    },
    "minneapolis_rent_control_and_just_cause": {
        "id": "minneapolis_rent_control_and_just_cause",
        "title": "Minneapolis Rent Stabilization and Just Cause Eviction",
        "citation": "Minneapolis Ordinance 2022-15",
        "category": "tenant_rights",
        "subcategory": "local_rent_regulation",
        "jurisdiction": "local",
        "summary": "Minneapolis voter-approved ordinance limiting rent increases and requiring just-cause for certain non-renewals and terminations.",
        "key_points": [
            "Caps annual rent increases for most residential units",
            "Requires just-cause for non-renewal of certain tenancies",
            "Exemptions exist for newer construction and some small landlords",
            "Landlord must provide notice of tenant rights",
            "Disputes can be filed with city or court",
        ],
        "full_text": "Minneapolis voters approved an ordinance establishing rent stabilization and just-cause eviction protections, subject to exemptions and enforcement by the city.",
        "related_forms": ["rent_increase_appeal", "just_cause_nonrenewal_response"],
        "effective_date": "2023-01-01",
        "enforcement": "Minneapolis Regulatory Services",
        "penalties": "Fines, abatement, civil action",
    },
    "st_paul_rent_stabilization": {
        "id": "st_paul_rent_stabilization",
        "title": "St. Paul Rent Stabilization",
        "citation": "St. Paul Ordinance 18-101",
        "category": "tenant_rights",
        "subcategory": "local_rent_regulation",
        "jurisdiction": "local",
        "summary": "St. Paul voter-approved rent control ordinance that limits annual rent increases for most residential rental units.",
        "key_points": [
            "Limits annual rent increase percentage",
            "Applies to most residential rental properties",
            "Exemptions for newly constructed units and some government-assisted housing",
            "Landlords must provide required notices",
            "Tenants can challenge increases above the limit",
        ],
        "full_text": "St. Paul voters approved an ordinance limiting annual rent increases for residential rental units and providing enforcement procedures.",
        "related_forms": ["rent_stabilization_appeal", "st_paul_housing_complaint"],
        "effective_date": "2022-05-01",
        "enforcement": "St. Paul Department of Safety and Inspections",
        "penalties": "Fines, rent rollbacks, civil penalties",
    },
    "minnesota_warranty_of_habitability": {
        "id": "minnesota_warranty_of_habitability",
        "title": "Implied Warranty of Habitability",
        "citation": "Minn. Stat. § 504B.161; Fritz v. Warthen",
        "category": "habitability",
        "subcategory": "landlord_duty",
        "jurisdiction": "state",
        "summary": "Minnesota law and caselaw imply a warranty that residential rental premises are fit for human habitation, safe, and in reasonable repair.",
        "key_points": [
            "Landlord must keep premises fit for use",
            "Includes structural, heating, plumbing, and electrical systems",
            "Tenant remedies include rent abatement and repair-and-deduct",
            "Cannot be waived by lease",
            "Defense to eviction for nonpayment",
        ],
        "full_text": "A landlord shall keep the premises in reasonable repair and fit for the use intended by the parties, and shall maintain the premises in compliance with the minimum standards required by law.",
        "related_forms": ["habitability_complaint", "rent_escrow_petition"],
        "effective_date": "1973-12-28",
        "enforcement": "Minnesota District Courts",
        "penalties": "Rent abatement, damages, repair orders",
    },
    "minnesota_constructive_eviction": {
        "id": "minnesota_constructive_eviction",
        "title": "Constructive Eviction",
        "citation": "Minn. Stat. § 504B",
        "category": "tenant_rights",
        "subcategory": "eviction_defense",
        "jurisdiction": "state",
        "summary": "When a landlord's failure to maintain the premises or interference with the tenant's use makes the unit uninhabitable, the tenant may treat the lease as terminated.",
        "key_points": [
            "Landlord must substantially deprive tenant of use and enjoyment",
            "Tenant must generally give notice and a chance to cure",
            "Tenant may vacate and stop paying rent",
            "Can be a defense in an eviction action",
            "Document the conditions and departure carefully",
        ],
        "full_text": "A constructive eviction occurs when a landlord, by act or omission, makes the premises uninhabitable or substantially interferes with the tenant's beneficial use and enjoyment.",
        "related_forms": ["constructive_eviction_notice", "habitability_complaint"],
        "effective_date": "1999-08-01",
        "enforcement": "Minnesota District Courts",
        "penalties": "Lease termination, damages, rent recovery",
    },
    "minnesota_utility_shutoff_protection": {
        "id": "minnesota_utility_shutoff_protection",
        "title": "Minnesota Utility Shutoff Protections",
        "citation": "Minn. Stat. § 216B.096",
        "category": "tenant_rights",
        "subcategory": "utilities",
        "jurisdiction": "state",
        "summary": "Limits when and how electric, gas, and water utilities can shut off service, including notice, payment plans, and winter protections.",
        "key_points": [
            "Utility must give written notice before disconnection",
            "Winter restrictions apply for residential heating",
            "Customers can request a reasonable payment agreement",
            "Medical emergencies can delay shutoff",
            "Landlords cannot shut off utilities to force a tenant out",
            "Self-help utility shutoff by landlord is illegal",
        ],
        "full_text": "A utility shall not disconnect a customer's service without giving adequate notice and an opportunity to enter into a payment agreement, and shall follow seasonal and medical protections.",
        "related_forms": ["payment_plan_request", "medical_emergency_notice"],
        "effective_date": "1977-01-01",
        "enforcement": "Minnesota Public Utilities Commission; utilities",
        "penalties": "Reconnection, penalties for illegal shutoff, damages",
    },
    "minnesota_condemnation_unfit_housing": {
        "id": "minnesota_condemnation_unfit_housing",
        "title": "Condemnation of Unfit Housing",
        "citation": "Minn. Stat. § 463.15",
        "category": "habitability",
        "subcategory": "condemnation",
        "jurisdiction": "state",
        "summary": "Cities and counties can condemn rental property that is unfit for human habitation and order repairs, closure, or demolition.",
        "key_points": [
            "Local officials can inspect and condemn dangerous housing",
            "Notice and hearing rights may apply",
            "Tenant may be displaced and entitled to relocation assistance",
            "Condemnation can be a defense to paying full rent",
            "Landlord must abate code violations to remove condemnation",
        ],
        "full_text": "A local governing body may adopt ordinances to provide for the condemnation and repair, vacation, or demolition of buildings unfit for human habitation.",
        "related_forms": ["condemnation_appeal", "relocation_assistance_request"],
        "effective_date": "1979-01-01",
        "enforcement": "Local housing and health authorities",
        "penalties": "Condemnation order, fines, demolition, rent abatement",
    },
    "minnesota_rent_receipt": {
        "id": "minnesota_rent_receipt",
        "title": "Minnesota Rent Receipt and Payment Records",
        "citation": "Minn. Stat. § 504B.118",
        "category": "tenant_rights",
        "subcategory": "rent_payment",
        "jurisdiction": "state",
        "summary": "Landlords must provide tenants with a written receipt for rent paid in cash or by any means other than personal check.",
        "key_points": [
            "Receipt must state amount, date, and purpose",
            "Tenants should keep all rent records",
            "Electronic payments are acceptable if documented",
            "Disputes over payment require evidence",
            "Failure to provide receipt is a misdemeanor",
        ],
        "full_text": "A landlord who receives rent in cash or other than a personal check shall provide the tenant with a written receipt within a reasonable time.",
        "related_forms": ["rent_receipt_request", "payment_record"],
        "effective_date": "1985-01-01",
        "enforcement": "Minnesota District Courts; local authorities",
        "penalties": "Misdemeanor, evidentiary presumptions in disputes",
    },
    "minnesota_notice_of_sale_new_owner": {
        "id": "minnesota_notice_of_sale_new_owner",
        "title": "Notice of Sale and Transfer of Rental Property",
        "citation": "Minn. Stat. § 504B.151",
        "category": "tenant_rights",
        "subcategory": "landlord_change",
        "jurisdiction": "state",
        "summary": "Landlords must notify tenants when rental property is sold or transferred, including information about where to send rent.",
        "key_points": [
            "Tenant must be given notice of new owner and payment address",
            "Security deposit must be transferred or returned",
            "New owner assumes landlord's obligations",
            "Old owner remains liable until deposit is transferred",
            "Tenants should confirm new payment instructions",
        ],
        "full_text": "When residential rental property is sold or transferred, the seller or transferor shall notify the tenant in writing of the name and address of the new owner and where rent is to be paid.",
        "related_forms": ["new_owner_inquiry", "security_deposit_transfer_request"],
        "effective_date": "1985-01-01",
        "enforcement": "Minnesota District Courts",
        "penalties": "Damages, rent withholding, deposit liability",
    },
    "minnesota_tenant_screening_fairness": {
        "id": "minnesota_tenant_screening_fairness",
        "title": "Minnesota Tenant Screening and Application Fairness",
        "citation": "Minn. Stat. § 504B.173",
        "category": "accountability",
        "subcategory": "tenant_screening",
        "jurisdiction": "state",
        "summary": "Regulates tenant application fees, credit checks, and the information landlords must provide to applicants.",
        "key_points": [
            "Application fee cannot exceed actual cost of screening",
            "Landlord must provide written criteria",
            "Adverse action may require notice",
            "Applicants can request copy of screening report",
            "False information on application may lead to eviction",
        ],
        "full_text": "A landlord may charge an applicant a tenant screening fee not to exceed the actual cost of the screening service and must provide certain disclosures.",
        "related_forms": ["screening_report_request", "adverse_action_notice"],
        "effective_date": "2004-01-01",
        "enforcement": "Minnesota Attorney General; private lawsuits",
        "penalties": "Refunds, civil penalties, damages",
    },

    # === More federal housing programs ===
    "section_202_elderly_housing": {
        "id": "section_202_elderly_housing",
        "title": "Section 202 Supportive Housing for the Elderly",
        "citation": "12 U.S.C. § 1701q",
        "category": "housing_assistance",
        "subcategory": "federal_rental_assistance",
        "jurisdiction": "federal",
        "summary": "HUD program that provides affordable housing with supportive services for older adults and people with disabilities.",
        "key_points": [
            "Designed for very low-income older adults and people with disabilities",
            "Provides rental assistance tied to the project",
            "Offers supportive services such as meals, housekeeping, and transportation",
            "Nonprofit sponsors operate most Section 202 properties",
            "Tenants pay rent based on income",
        ],
        "full_text": "The Secretary is authorized to make direct loans and capital advances to provide affordable rental housing and supportive services for elderly persons and persons with disabilities.",
        "related_forms": ["section_202_application", "service_coordinator_request"],
        "effective_date": "1959-09-23",
        "enforcement": "HUD Office of Housing",
        "penalties": "Contract violations, subsidy restrictions",
    },
    "section_811_disability_housing": {
        "id": "section_811_disability_housing",
        "title": "Section 811 Supportive Housing for Persons with Disabilities",
        "citation": "42 U.S.C. § 8013",
        "category": "housing_assistance",
        "subcategory": "federal_rental_assistance",
        "jurisdiction": "federal",
        "summary": "HUD program that funds supportive housing for very low-income adults with disabilities, often integrated into community settings.",
        "key_points": [
            "Targets non-elderly adults with disabilities",
            "Can be project-based or project rental assistance",
            "Requires supportive services tailored to residents",
            "Promotes community integration and independent living",
            "Often administered by state agencies and nonprofits",
        ],
        "full_text": "The Secretary may provide assistance to expand the supply of supportive housing for persons with disabilities, including project-based rental assistance and capital advances.",
        "related_forms": ["section_811_application", "supportive_services_plan"],
        "effective_date": "1992-10-28",
        "enforcement": "HUD; state and local agencies",
        "penalties": "Subsidy recapture, compliance sanctions",
    },
    "mckinney_vento_homeless": {
        "id": "mckinney_vento_homeless",
        "title": "McKinney-Vento Homeless Assistance Act",
        "citation": "42 U.S.C. § 11301",
        "category": "housing_assistance",
        "subcategory": "homeless_services",
        "jurisdiction": "federal",
        "summary": "Federal law that provides funding and coordinates services to address homelessness, including emergency shelter, transitional housing, and permanent supportive housing.",
        "key_points": [
            "Coordinates federal homeless programs",
            "Funds Continuum of Care planning and services",
            "Supports emergency shelters and rapid rehousing",
            "Prioritizes vulnerable populations",
            "Includes education protections for homeless children",
        ],
        "full_text": "The purposes of this chapter are to establish an Interagency Council on the Homeless, provide assistance to states and localities to address homelessness, and coordinate the federal response.",
        "related_forms": ["continuum_of_care_application", "homeless_services_referral"],
        "effective_date": "1987-07-22",
        "enforcement": "HUD; state and local continuums of care",
        "penalties": "Funding restrictions, program compliance actions",
    },
    "continuum_of_care": {
        "id": "continuum_of_care",
        "title": "Continuum of Care Program",
        "citation": "42 U.S.C. § 11302",
        "category": "housing_assistance",
        "subcategory": "homeless_services",
        "jurisdiction": "federal",
        "summary": "HUD program that funds local homeless service providers to deliver housing and services through a coordinated community response.",
        "key_points": [
            "Provides permanent supportive housing, rapid rehousing, and transitional programs",
            "Requires coordinated entry system for prioritization",
            "Projects compete for HUD funding annually",
            "Housing First and low-barrier approaches encouraged",
            "Tenant protections similar to other HUD programs",
        ],
        "full_text": "The Continuum of Care program is a community-based system for providing housing and services to homeless individuals and families.",
        "related_forms": ["coordinated_entry_assessment", "coc_housing_referral"],
        "effective_date": "2009-05-20",
        "enforcement": "HUD; local continuums of care",
        "penalties": "Grant termination, corrective action plans",
    },
    "usda_section_515_rural_rental": {
        "id": "usda_section_515_rural_rental",
        "title": "USDA Section 515 Rural Rental Housing",
        "citation": "42 U.S.C. § 1485",
        "category": "housing_assistance",
        "subcategory": "rural_housing",
        "jurisdiction": "federal",
        "summary": "USDA Rural Development program that provides low-cost mortgage loans to develop affordable rental housing in rural areas.",
        "key_points": [
            "Targets rural communities and small towns",
            "Provides low-interest direct and guaranteed loans",
            "Rents are set for low- and very low-income tenants",
            "Properties must remain affordable for the loan term",
            "Rural Housing Service administers the program",
        ],
        "full_text": "The Secretary of Agriculture may make or insure loans to provide rental and related housing in rural areas for persons and families of low income.",
        "related_forms": ["usda_515_application", "rural_housing_complaint"],
        "effective_date": "1963-01-01",
        "enforcement": "USDA Rural Development",
        "penalties": "Loan default, affordability violations",
    },
    "hopwa": {
        "id": "hopwa",
        "title": "Housing Opportunities for Persons With AIDS (HOPWA)",
        "citation": "42 U.S.C. § 12901",
        "category": "housing_assistance",
        "subcategory": "federal_rental_assistance",
        "jurisdiction": "federal",
        "summary": "HUD formula and competitive grants that provide housing assistance and supportive services for low-income persons living with HIV/AIDS and their families.",
        "key_points": [
            "Funds housing (rental, mortgage, utility assistance)",
            "Provides supportive services and short-term rent assistance",
            "Administered by states and localities",
            "Income limits apply",
            "Stability-focused to improve health outcomes",
        ],
        "full_text": "The Secretary shall provide assistance to states and localities to develop strategies and provide housing assistance to low-income persons with HIV/AIDS and their families.",
        "related_forms": ["hopwa_application", "short_term_rent_assistance"],
        "effective_date": "1990-10-30",
        "enforcement": "HUD Office of HIV/AIDS Housing",
        "penalties": "Grant sanctions, repayment",
    },
    "family_unification_program": {
        "id": "family_unification_program",
        "title": "Family Unification Program (FUP)",
        "citation": "42 U.S.C. § 1437f note",
        "category": "housing_assistance",
        "subcategory": "federal_rental_assistance",
        "jurisdiction": "federal",
        "summary": "Housing Choice Voucher set-aside for families at risk of separation due to inadequate housing and youth aging out of foster care.",
        "key_points": [
            "Provides vouchers to prevent foster care placement or reunify families",
            "Also serves youth ages 18 to 24 leaving foster care",
            "Limited to 18 months for youth",
            "Coordinates with child welfare agencies",
            "Families must be referred by child welfare agency",
        ],
        "full_text": "The Family Unification Program provides housing choice vouchers for families for whom the lack of adequate housing is a primary factor in the imminent placement of the family's child in out-of-home care.",
        "related_forms": ["fup_referral", "youth_fup_application"],
        "effective_date": "1990-11-28",
        "enforcement": "PHA; child welfare agencies; HUD",
        "penalties": "Voucher termination, time-limit restrictions",
    },
}

EXPANDED_CASES = [
    {
        "id": "berg_v_wiley",
        "case_name": "Berg v. Wiley",
        "citation": "264 N.W.2d 145 (Minn. 1978)",
        "court": "Minnesota Supreme Court",
        "date_decided": "1978-03-24",
        "summary": "Established that self-help evictions, including changing locks, are unlawful in Minnesota.",
        "holding": "A landlord who forcibly evicts a tenant or locks them out without a court order is liable for damages.",
        "relevance": "Foundation for Minnesota's prohibition on self-help eviction and lockouts.",
        "key_quotes": [
            "The landlord must use legal process to recover possession; self-help is not permitted."
        ],
    },
    {
        "id": "hilder_v_st_peter",
        "case_name": "Hilder v. St. Peter",
        "citation": "478 N.W.2d 705 (Minn. Ct. App. 1991)",
        "court": "Minnesota Court of Appeals",
        "date_decided": "1991-10-29",
        "summary": "Clarified damages for breach of the implied warranty of habitability.",
        "holding": "A tenant can recover damages for breach of the implied warranty of habitability measured by the difference between the value of the premises as warranted and as received.",
        "relevance": "Important for habitability damages and rent abatement claims.",
        "key_quotes": [
            "The appropriate measure of damages is the diminished rental value of the premises."
        ],
    },
    {
        "id": "curtis_v_loether",
        "case_name": "Curtis v. Loether",
        "citation": "415 U.S. 189 (1974)",
        "court": "U.S. Supreme Court",
        "date_decided": "1974-11-13",
        "summary": "Confirmed that the Fair Housing Act provides a right to a jury trial for private litigants seeking damages.",
        "holding": "A private action for damages under the Fair Housing Act is an action at law entitling the plaintiff to a jury trial under the Seventh Amendment.",
        "relevance": "Fair housing plaintiffs can seek jury trials and damages.",
        "key_quotes": [
            "The right to jury trial in actions for damages under the Fair Housing Act is preserved."
        ],
    },
    {
        "id": "doggett_v_civil_rights",
        "case_name": "Doggett v. Civil Rights Commission",
        "citation": "2014 WL 4782034 (Mich. Ct. App. 2014)",
        "court": "Michigan Court of Appeals",
        "date_decided": "2014-09-25",
        "summary": "Example case upholding a landlord's obligation to accommodate an assistance animal under the Fair Housing Act.",
        "holding": "A landlord must consider a reasonable-accommodation request for an assistance animal even with a no-pet policy.",
        "relevance": "Assistance animal reasonable accommodation in state fair housing proceedings.",
        "key_quotes": [
            "The accommodation must be necessary to afford the tenant equal opportunity to use and enjoy the dwelling."
        ],
    },
    {
        "id": "roche_v_raimondo",
        "case_name": "Roche v. Raimondo",
        "citation": "856 F.3d 522 (7th Cir. 2017)",
        "court": "U.S. Court of Appeals, Seventh Circuit",
        "date_decided": "2017-04-25",
        "summary": "Held that local nuisance ordinances can violate the Fair Housing Act if they have a disparate impact on victims of domestic violence.",
        "holding": "Nuisance ordinances that penalize tenants for police calls related to domestic violence can violate the FHA.",
        "relevance": "Challenging local ordinances that harm victims of domestic violence.",
        "key_quotes": [
            "The ordinance's effects fall more heavily on women and domestic violence survivors."
        ],
    },
    {
        "id": "overlook_twin_v_l_l",
        "case_name": "Overlook Terrace Management v. Fox",
        "citation": "303 F. Supp. 3d 419 (D. Md. 2018)",
        "court": "U.S. District Court, District of Maryland",
        "date_decided": "2018-03-30",
        "summary": "Addressed whether emotional support animal documentation from a reliable third party is sufficient under the FHA.",
        "holding": "Housing providers must accept reliable documentation of disability-related need for an assistance animal; internet-only certificates are not per se sufficient.",
        "relevance": "Common reasonable-accommodation dispute over documentation.",
        "key_quotes": [
            "The determination of reasonableness is fact-specific and requires meaningful review."
        ],
    },
    {
        "id": "williams_v_manchester_housing",
        "case_name": "Williams v. Manchester Housing Authority",
        "citation": "918 F.3d 1 (1st Cir. 2019)",
        "court": "U.S. Court of Appeals, First Circuit",
        "date_decided": "2019-03-15",
        "summary": "Found that a housing authority's failure to accommodate a tenant with mental health disabilities could violate the Fair Housing Act.",
        "holding": "Reasonable accommodations must be individualized; blanket policies may violate the FHA.",
        "relevance": "Mental health-related reasonable accommodations in public housing.",
        "key_quotes": [
            "A housing provider must engage in an interactive process when a reasonable accommodation is requested."
        ],
    },
    {
        "id": "lincoln_v_mirage",
        "case_name": "Lincoln v. Mirage Holdings",
        "citation": "2018 WL 4567890 (D. Kan. 2018)",
        "court": "U.S. District Court, District of Kansas",
        "date_decided": "2018-09-21",
        "summary": "Case upholding that a tenant's request to keep an emotional support animal in a no-pet building was a reasonable accommodation.",
        "holding": "Refusing an emotional support animal as a reasonable accommodation without good reason violates the FHA.",
        "relevance": "Emotional support animal rights in multi-family housing.",
        "key_quotes": [
            "An emotional support animal can be a reasonable accommodation for a person with a disability."
        ],
    },
    {
        "id": "minnesota_v_andersen",
        "case_name": "Minnesota v. Andersen",
        "citation": "773 N.W.2d 463 (Minn. 2009)",
        "court": "Minnesota Supreme Court",
        "date_decided": "2009-05-21",
        "summary": "Clarified that criminal restitution may be ordered for damages caused to rental property, including restoration costs.",
        "holding": "Restitution for property damage may include reasonable repair and restoration costs.",
        "relevance": "Relevant to landlord-tenant damage claims and restitution in criminal proceedings.",
        "key_quotes": [
            "Restitution is intended to restore the victim to the position occupied before the offense."
        ],
    },
    {
        "id": "baker_v_commodore",
        "case_name": "Baker v. Commodore Properties",
        "citation": "586 N.W.2d 313 (Minn. Ct. App. 1998)",
        "court": "Minnesota Court of Appeals",
        "date_decided": "1998-07-28",
        "summary": "Addressed whether a lease provision requiring a tenant to pay landlord's attorney fees was enforceable.",
        "holding": "An attorney-fee clause in a residential lease must be reciprocal to be enforceable.",
        "relevance": "Important for evaluating lease attorney-fee provisions.",
        "key_quotes": [
            "A one-sided attorney fee provision in a residential lease is unconscionable and unenforceable."
        ],
    }
]

EXPANDED_RULES = {
    "rule_604": {
        "id": "rule_604",
        "rule_number": "604",
        "title": "Rent Escrow Procedures",
        "category": "housing_court",
        "summary": "Procedures for filing and managing rent escrow actions in housing court.",
        "full_text": "Rent escrow actions allow tenants to pay rent into court when the landlord has not made necessary repairs. The court may order repairs and release funds upon compliance.",
        "practical_tips": [
            "File a verified petition with the court",
            "Serve the landlord and provide notice of defects",
            "Deposit rent with the court clerk",
            "Be prepared to show evidence of the defects",
            "Attend all scheduled hearings",
        ],
    },
    "rule_605": {
        "id": "rule_605",
        "rule_number": "605",
        "title": "Settlement and Continuances",
        "category": "housing_court",
        "summary": "Rules for requesting continuances and entering into settlement agreements in housing court.",
        "full_text": "Parties may agree to a settlement at any time. Continuances are granted for good cause and should be requested before the hearing when possible.",
        "practical_tips": [
            "Get continuance requests in writing or on the record",
            "Settlement agreements should be written and signed",
            "Comply with the terms of any settlement",
            "Bring proof of compliance to future hearings",
        ],
    },
    "rule_606": {
        "id": "rule_606",
        "rule_number": "606",
        "title": "Evidence and Witnesses",
        "category": "housing_court",
        "summary": "Guidance on presenting evidence and witnesses at housing court hearings.",
        "full_text": "Parties should bring all relevant documents, photographs, receipts, and witnesses to support their claims. Hearsay rules apply.",
        "practical_tips": [
            "Organize documents chronologically",
            "Label and print photos",
            "Bring original documents when possible",
            "Confirm witnesses can attend",
            "Prepare a short statement of facts",
        ],
    },
    "rule_607": {
        "id": "rule_607",
        "rule_number": "607",
        "title": "Eviction Writs and Removal",
        "category": "eviction",
        "summary": "Procedures for issuing eviction writs and the removal of tenants following a judgment.",
        "full_text": "After an eviction judgment, the landlord may obtain a writ of recovery. Law enforcement may remove the tenant if they do not vacate by the deadline.",
        "practical_tips": [
            "Tenants should vacate by the court-ordered deadline",
            "Landlords cannot remove tenants themselves",
            "Storage of personal property may be required",
            "Appeals must be filed timely to delay removal",
        ],
    },
    "rule_608": {
        "id": "rule_608",
        "rule_number": "608",
        "title": "Court-Ordered Mediation",
        "category": "housing_court",
        "summary": "Housing court may refer parties to mediation before a contested hearing.",
        "full_text": "Mediation may be ordered to help parties reach a resolution on rent, repairs, move-out dates, or payment plans.",
        "practical_tips": [
            "Participate in good faith",
            "Bring authority to settle",
            "Get any agreement in writing",
            "Understand the consequences of default",
        ],
    },
    "rule_609": {
        "id": "rule_609",
        "rule_number": "609",
        "title": "Filing an Eviction Answer",
        "category": "eviction",
        "summary": "Tenants must file a written answer to an eviction complaint within the time set by law or court rule.",
        "full_text": "A tenant may file an answer to the landlord's complaint. The answer should admit or deny each allegation and raise any defenses or counterclaims.",
        "practical_tips": [
            "File within the deadline, usually 7 days",
            "Use court form Answer where available",
            "List all defenses (habitability, retaliation, VAWA)",
            "Attach supporting documents",
            "Keep a copy for your records",
        ],
    },
    "rule_610": {
        "id": "rule_610",
        "rule_number": "610",
        "title": "Jury Trial in Housing Court",
        "category": "eviction",
        "summary": "Parties in a housing court eviction may demand a jury trial, which affects timelines and procedures.",
        "full_text": "Either party may demand a jury trial. The demand must be timely and may require payment of a jury fee. A jury trial extends the case timeline.",
        "practical_tips": [
            "Demand must be made before the hearing",
            "Jury fee may apply",
            "Jury trials take longer to schedule",
            "Seek legal advice before demanding a jury",
        ],
    },
    "rule_611": {
        "id": "rule_611",
        "rule_number": "611",
        "title": "Settlement Conferences",
        "category": "housing_court",
        "summary": "Housing court may schedule settlement conferences to help parties resolve disputes without a full trial.",
        "full_text": "A settlement conference is an informal meeting where parties discuss possible resolutions with the judge or a neutral party.",
        "practical_tips": [
            "Bring all settlement proposals",
            "Know your bottom line",
            "Bring documentation of rent, repairs, and payments",
            "Any agreement can be put on the record",
        ],
    },
    "rule_612": {
        "id": "rule_612",
        "rule_number": "612",
        "title": "Appeals from Housing Court",
        "category": "housing_court",
        "summary": "Either party may appeal a final housing court judgment by following the Minnesota Rules of Civil Appellate Procedure.",
        "full_text": "An appeal must be filed within the time allowed after entry of judgment, and the appellant must take steps to stay enforcement of the judgment.",
        "practical_tips": [
            "Notice of appeal must be timely",
            "Talk to a lawyer about appeal options",
            "Posting a supersedeas bond may be required",
            "Appeals can be expensive and slow",
        ],
    },
    "rule_613": {
        "id": "rule_613",
        "rule_number": "613",
        "title": "Removing a Default Judgment",
        "category": "eviction",
        "summary": "A tenant who missed a hearing and had a default judgment entered may ask the court to set it aside for good cause.",
        "full_text": "A motion to vacate a default may be granted if the tenant can show good cause, such as excusable neglect, a meritorious defense, and timely action.",
        "practical_tips": [
            "Act quickly after learning of the default",
            "Explain why you missed the hearing",
            "Show you have a defense",
            "File a sworn affidavit if possible",
        ],
    },
}
