"""Expanded Law Library entries.

Adds coverage for service/emotional support animals, vulnerable adults,
commerce and leasing law, landlord-tenant accountability, and HUD / low-income
housing programs. Imported into the Law Library router and merged into ALL_LAWS.
"""

EXPANDED_LAWS = {
    # === HUD / low-income rental assistance ===
    "hud_housing_choice_voucher": {
        "id": "hud_housing_choice_voucher",
        "title": "Housing Choice Voucher Program (Section 8)",
        "citation": "42 U.S.C. § 1437f",
        "category": "housing_assistance",
        "subcategory": "federal_rental_assistance",
        "jurisdiction": "federal",
        "summary": "HUD program that helps very low-income families, older adults, and people with disabilities afford decent, safe, and sanitary housing in the private market.",
        "key_points": [
            "Tenant-based vouchers move with the tenant",
            "Project-based vouchers are tied to a specific property",
            "Families pay roughly 30% of adjusted income for rent",
            "Landlords must meet HUD housing quality standards",
            "Participants have due-process rights in voucher terminations",
            "Landlord participation is voluntary in most jurisdictions",
            "VAWA protections apply to voucher holders",
        ],
        "full_text": "The Secretary of Housing and Urban Development is authorized to make housing assistance payments to or on behalf of the tenant, including direct payments to a public housing agency for project-based assistance, or to private landlords on behalf of very low-income families.",
        "related_forms": ["voucher_renewal_request", "portability_request", "hqs_complaint"],
        "effective_date": "1974-08-22",
        "enforcement": "HUD Office of Public and Indian Housing (PIH); PHAs",
        "penalties": "Voucher termination, repayment agreements, administrative hearings",
    },
    "hud_public_housing": {
        "id": "hud_public_housing",
        "title": "Public Housing Program",
        "citation": "42 U.S.C. § 1437",
        "category": "housing_assistance",
        "subcategory": "federal_rental_assistance",
        "jurisdiction": "federal",
        "summary": "HUD program that provides affordable rental housing for eligible low-income families, older adults, and persons with disabilities through publicly owned and operated developments.",
        "key_points": [
            "Owned and operated by public housing authorities (PHAs)",
            "Rent is generally set at 30% of adjusted income",
            "Residents have grievance and hearing rights",
            "PHAs must comply with federal regulations and ACC contracts",
            "Evictions require due process and good cause",
            "Accessible units required for residents with disabilities",
        ],
        "full_text": "The Secretary is authorized to provide financial assistance to public housing agencies for the development, acquisition, and operation of public-housing projects and for related housing assistance.",
        "related_forms": ["pha_grievance", "public_housing_lease"],
        "effective_date": "1937-09-01",
        "enforcement": "HUD; PHAs; federal courts",
        "penalties": "Lease termination, informal hearings, civil rights complaints",
    },
    "lihtc": {
        "id": "lihtc",
        "title": "Low-Income Housing Tax Credit (LIHTC)",
        "citation": "26 U.S.C. § 42",
        "category": "housing_assistance",
        "subcategory": "federal_housing_finance",
        "jurisdiction": "federal",
        "summary": "Federal tax-credit program that encourages private investment in affordable rental housing for low-income households.",
        "key_points": [
            "Tax credits are allocated to states and then to developers",
            "Units must remain affordable for a minimum compliance period (usually 30 years)",
            "Income restrictions apply to tenants",
            "Rent limits are set by HUD for the area",
            "Owners must follow state agency compliance rules",
            "Tenant protections vary by state and local agreements",
        ],
        "full_text": "The amount of the low-income housing credit for any taxable year is the applicable percentage of the qualified basis of each qualified low-income building.",
        "related_forms": ["lihtc_tenant_income_certification", "rent_limit_inquiry"],
        "effective_date": "1986-10-22",
        "enforcement": "IRS; state housing finance agencies; investors",
        "penalties": "Credit recapture, state agency sanctions, lease non-renewal",
    },
    "project_based_section8": {
        "id": "project_based_section8",
        "title": "Project-Based Section 8",
        "citation": "42 U.S.C. § 1437f",
        "category": "housing_assistance",
        "subcategory": "federal_rental_assistance",
        "jurisdiction": "federal",
        "summary": "Federal rental assistance tied to a specific property or unit rather than a tenant. The subsidy stays with the unit.",
        "key_points": [
            "Subsidy is attached to the unit, not the family",
            "Tenant income must continue to qualify",
            "Owners must maintain HUD housing quality standards",
            "Tenants have lease and grievance protections",
            "If tenant moves, the assistance does not follow",
            "VAWA protections apply",
        ],
        "full_text": "Housing assistance payments made on a project basis to owners of eligible housing units for very low-income families, subject to annual contributions contracts with HUD.",
        "related_forms": ["project_based_lease", "hqs_complaint"],
        "effective_date": "1974-08-22",
        "enforcement": "HUD; property owners; housing agencies",
        "penalties": "Contract termination, rent adjustments, tenant recertification",
    },
    "home_investment_partnerships": {
        "id": "home_investment_partnerships",
        "title": "HOME Investment Partnerships Program",
        "citation": "42 U.S.C. § 12722",
        "category": "housing_assistance",
        "subcategory": "federal_housing_finance",
        "jurisdiction": "federal",
        "summary": "Federal block-grant program to states and localities for affordable housing and low-income homeownership.",
        "key_points": [
            "Funds can be used for rental housing, tenant-based rental assistance, and homeownership",
            "At least 90% of assisted families must be low-income",
            "Participating jurisdictions (PJs) administer funds",
            "May include income limits and rent limits",
            "Tenant and homebuyer protections apply",
        ],
        "full_text": "The Secretary shall, in accordance with this subchapter, make grants to participating jurisdictions for affordable housing activities.",
        "related_forms": ["home_rental_application", "pj_complaint"],
        "effective_date": "1990-11-28",
        "enforcement": "HUD; state and local PJs",
        "penalties": "Grant repayment, program sanctions, local enforcement",
    },
    "national_housing_trust_fund": {
        "id": "national_housing_trust_fund",
        "title": "National Housing Trust Fund",
        "citation": "42 U.S.C. § 4568",
        "category": "housing_assistance",
        "subcategory": "federal_housing_finance",
        "jurisdiction": "federal",
        "summary": "Federal housing fund that provides states with funding to increase and preserve the supply of rental housing for extremely and very low-income households.",
        "key_points": [
            "Capitalized by a small percentage of Fannie Mae and Freddie Mac business earnings",
            "Funds are allocated to states by formula",
            "Must primarily benefit extremely low-income families",
            "States design their own programs within HUD guidelines",
            "Can be used for rental, operating, and housing-support services",
        ],
        "full_text": "There is established in the Treasury of the United States a fund to be known as the 'Housing Trust Fund', which shall be available to the Secretary to provide affordable housing assistance.",
        "related_forms": ["htf_application", "state_htf_inquiry"],
        "effective_date": "2008-07-30",
        "enforcement": "HUD; state housing agencies",
        "penalties": "Funding recapture, program restrictions",
    },
    "hud_income_limits": {
        "id": "hud_income_limits",
        "title": "HUD Income Limits for Assisted Housing",
        "citation": "42 U.S.C. § 1437a",
        "category": "housing_assistance",
        "subcategory": "federal_rental_assistance",
        "jurisdiction": "federal",
        "summary": "Defines income-eligibility thresholds (very low income, extremely low income, low income) for HUD-assisted and many affordable housing programs.",
        "key_points": [
            "Income limits are published annually by HUD for each metro area and county",
            "Used for Section 8 vouchers, public housing, LIHTC, and other programs",
            "Extremely low income is generally 30% of area median income",
            "Very low income is generally 50% of area median income",
            "Low income is generally 80% of area median income",
            "Household size matters for eligibility",
        ],
        "full_text": "The Secretary shall prescribe income limits for admission to federally assisted housing, based on area median income and adjusted for family size.",
        "related_forms": ["income_recalculation_request", "utility_allowance_inquiry"],
        "effective_date": "1974-08-22",
        "enforcement": "HUD; PHAs; property owners",
        "penalties": "Overpayment recovery, lease termination, program disqualification",
    },

    # === Service and emotional support animals ===
    "service_animals_fha": {
        "id": "service_animals_fha",
        "title": "Service Animals in Housing (FHA)",
        "citation": "42 U.S.C. § 3604(f)",
        "category": "service_animals",
        "subcategory": "fha_assistance_animals",
        "jurisdiction": "federal",
        "summary": "Under the Fair Housing Act, assistance animals are not 'pets' and must be accommodated in housing when needed by a person with a disability.",
        "key_points": [
            "Dogs and other animals can be assistance animals",
            "Assistance animals perform work, tasks, or provide emotional support",
            "No breed, size, or weight restrictions apply by default",
            "Landlords can request reliable disability-related documentation if not apparent",
            "Cannot charge pet fees or deposits, but tenant is liable for damage",
            "Public accommodations (ADA) rules are stricter and require a service dog",
        ],
        "full_text": "Discrimination includes a refusal to make reasonable accommodations in rules, policies, practices, or services, when such accommodations may be necessary to afford a person with a disability an equal opportunity to use and enjoy a dwelling, including the right to keep an assistance animal.",
        "related_forms": ["reasonable_accommodation_request", "assistance_animal_request"],
        "effective_date": "1988-09-13",
        "enforcement": "HUD; DOJ; federal courts",
        "penalties": "Actual and punitive damages, injunctive relief, attorney fees",
    },
    "emotional_support_animals_hud": {
        "id": "emotional_support_animals_hud",
        "title": "Emotional Support Animals in Housing (HUD)",
        "citation": "HUD FHEO Notice 2020-01",
        "category": "service_animals",
        "subcategory": "hud_guidance",
        "jurisdiction": "federal",
        "summary": "HUD guidance explaining when housing providers must accept emotional support animals as a reasonable accommodation under the Fair Housing Act.",
        "key_points": [
            "Emotional support animals provide disability-related support even without training",
            "Housing providers may confirm disability and need if not readily apparent",
            "Internet certificates alone are not reliable documentation",
            "Providers cannot charge pet fees, but may charge for damage",
            "Breed, size, or weight restrictions alone are not valid reasons to deny",
            "Unique animals require a stronger showing of necessity",
        ],
        "full_text": "Housing providers must evaluate a request for a reasonable accommodation to possess an assistance animal in a dwelling using the general principles applicable to all reasonable accommodation requests under the Fair Housing Act.",
        "related_forms": ["assistance_animal_request", "hud_assistance_animal_complaint"],
        "effective_date": "2020-01-28",
        "enforcement": "HUD Office of Fair Housing and Equal Opportunity",
        "penalties": "HUD complaint process, civil action, administrative penalties",
    },
    "ada_service_animals_public_accommodations": {
        "id": "ada_service_animals_public_accommodations",
        "title": "Service Animals Under the ADA",
        "citation": "28 C.F.R. § 36.104",
        "category": "service_animals",
        "subcategory": "ada_public_accommodations",
        "jurisdiction": "federal",
        "summary": "Title II and Title III of the ADA define service animals as dogs (and miniature horses in some cases) trained to do work or perform tasks for a person with a disability in public spaces.",
        "key_points": [
            "Only dogs are service animals under ADA; miniature horses may qualify separately",
            "Must be trained to perform a task related to the disability",
            "Emotional support animals are not service animals under the ADA",
            "Applies to public accommodations and state/local government services",
            "In housing, the Fair Housing Act is usually broader",
            "No certification or special tag required",
        ],
        "full_text": "Service animal means any dog that is individually trained to do work or perform tasks for the benefit of an individual with a disability, including a physical, sensory, psychiatric, intellectual, or other mental disability.",
        "related_forms": ["ada_complaint", "reasonable_modification_request"],
        "effective_date": "2010-09-15",
        "enforcement": "DOJ Civil Rights Division; DOJ complaints",
        "penalties": "Civil penalties, injunctive relief, attorney fees",
    },
    "minnesota_service_animal_law": {
        "id": "minnesota_service_animal_law",
        "title": "Minnesota Service Animal Law",
        "citation": "Minn. Stat. § 256C.02",
        "category": "service_animals",
        "subcategory": "state_service_animals",
        "jurisdiction": "state",
        "summary": "Minnesota law protects the rights of people with disabilities to be accompanied by service animals in public places and housing.",
        "key_points": [
            "Service animals in training also covered in some situations",
            "Places of public accommodation must allow service animals",
            "Housing providers must comply with state and federal disability laws",
            "No extra charge for service animal",
            "Handler is responsible for care and supervision",
        ],
        "full_text": "A person with a disability has the right to be accompanied by a service animal in all public accommodations and shall not be required to pay extra compensation.",
        "related_forms": ["service_animal_complaint", "reasonable_accommodation_request"],
        "effective_date": "2004-01-01",
        "enforcement": "Minnesota Department of Human Rights; state courts",
        "penalties": "Civil penalties, injunctive relief, damages",
    },

    # === Vulnerable adults ===
    "minnesota_vulnerable_adults_act": {
        "id": "minnesota_vulnerable_adults_act",
        "title": "Minnesota Vulnerable Adults Act",
        "citation": "Minn. Stat. § 626.557",
        "category": "vulnerable_adults",
        "subcategory": "mandatory_reporting",
        "jurisdiction": "state",
        "summary": "Minnesota's central law for reporting and investigating maltreatment of vulnerable adults, including abuse, neglect, and financial exploitation.",
        "key_points": [
            "Vulnerable adults include older adults, people with disabilities, and those receiving services",
            "Certain professionals and facility staff must report suspected maltreatment",
            "Reports go to the Minnesota Adult Abuse Reporting Center (MAARC)",
            "Investigations can lead to protective services, law enforcement, or licensing action",
            "Failure to report by mandated reporters is a misdemeanor",
            "Reporter identity is protected",
        ],
        "full_text": "The legislature finds that vulnerable adults have the right to live free from maltreatment and that the state has a duty to protect them through a reporting and investigation system.",
        "related_forms": ["vulnerable_adult_report", "protective_services_petition"],
        "effective_date": "1980-01-01",
        "enforcement": "Minnesota Department of Human Services; county agencies; law enforcement",
        "penalties": "Misdemeanor for failure to report; civil penalties for providers",
    },
    "minnesota_adult_protective_services": {
        "id": "minnesota_adult_protective_services",
        "title": "Adult Protective Services (APS)",
        "citation": "Minn. Stat. § 626.5571",
        "category": "vulnerable_adults",
        "subcategory": "protective_services",
        "jurisdiction": "state",
        "summary": "Authorizes counties to provide protective services to vulnerable adults who are being or have been maltreated and cannot protect themselves.",
        "key_points": [
            "Services are voluntary unless court-ordered",
            "Can include emergency shelter, medical care, financial management, and legal services",
            "Least-restrictive alternative is required",
            "May petition for guardianship or conservatorship if necessary",
            "Advocates for client self-determination",
        ],
        "full_text": "The county social service agency shall provide protective services to a vulnerable adult who has been reported to be maltreated, or is believed to be in need of protection, and who consents to the services.",
        "related_forms": ["aps_referral", "protective_services_plan"],
        "effective_date": "1995-01-01",
        "enforcement": "County adult protection units; DHS",
        "penalties": "Licensing action; court intervention",
    },
    "minnesota_financial_exploitation_vulnerable_adults": {
        "id": "minnesota_financial_exploitation_vulnerable_adults",
        "title": "Financial Exploitation of Vulnerable Adults",
        "citation": "Minn. Stat. § 609.2325",
        "category": "vulnerable_adults",
        "subcategory": "financial_abuse",
        "jurisdiction": "state",
        "summary": "Criminal statute penalizing the financial exploitation of a vulnerable adult, including misuse of funds, property, or identity by a person in a position of trust.",
        "key_points": [
            "Includes theft, misuse, and unauthorized use of funds or property",
            "Applies to caregivers, family members, and those with authority over a vulnerable adult",
            "Severity of charge depends on value and circumstances",
            "Victims may also pursue civil remedies",
            "Mandated reporters must report suspected exploitation",
        ],
        "full_text": "Whoever, having a legal duty or exercising temporary or permanent control over a vulnerable adult or vulnerable adult's property, intentionally uses the property of the vulnerable adult for the actor's own advantage or benefit is guilty of financial exploitation.",
        "related_forms": ["financial_exploitation_report", "conservatorship_petition"],
        "effective_date": "1995-01-01",
        "enforcement": "Law enforcement; county attorneys; DHS",
        "penalties": "Criminal penalties by value; restitution; civil liability",
    },
    "vulnerable_adult_housing_protections": {
        "id": "vulnerable_adult_housing_protections",
        "title": "Vulnerable Adult Housing and Tenancy Protections",
        "citation": "Minn. Stat. § 504B",
        "category": "vulnerable_adults",
        "subcategory": "landlord_tenant",
        "jurisdiction": "state",
        "summary": "Minnesota landlord-tenant law applies to all adults, including vulnerable adults; additional protections may arise through adult protection, conservatorship, or fair housing accommodations.",
        "key_points": [
            "Tenants with disabilities may request reasonable accommodations",
            "Caregivers or representatives can act with proper authority",
            "Adult protection can intervene in landlord-tenant disputes involving abuse or neglect",
            "Conservatorship can help manage rent and finances",
            "Retaliation protections still apply",
        ],
        "full_text": "Minnesota landlord and tenant law governs the rental relationship and does not exclude vulnerable adults. Reasonable accommodations, representative authority, and adult protective services may intersect in individual cases.",
        "related_forms": ["reasonable_accommodation_request", "conservatorship_petition"],
        "effective_date": "1999-08-01",
        "enforcement": "Minnesota District Courts; DHS; county APS",
        "penalties": "Eviction defense, civil remedies, protective orders",
    },

    # === Commerce / landlord-tenant contracts ===
    "ucc_article_2a_leases": {
        "id": "ucc_article_2a_leases",
        "title": "Uniform Commercial Code (UCC) — Leases",
        "citation": "Minn. Stat. § 336.2A",
        "category": "commerce",
        "subcategory": "ucc_leases",
        "jurisdiction": "state",
        "summary": "Minnesota's adopted UCC Article 2A governs leases of goods, including consumer and commercial leases, and provides default rules for lease formation, warranties, and remedies.",
        "key_points": [
            "Applies to the lease of goods, not real estate",
            "Provides default rules for lease agreements",
            "Covers express and implied warranties",
            "Gives remedies for default by lessor or lessee",
            "May not fully apply to residential real-property leases",
            "Useful for equipment, appliances, and other tangible goods",
        ],
        "full_text": "This article applies to any transaction, regardless of its form, that creates a lease of goods.",
        "related_forms": ["lease_agreement", "warranty_claim"],
        "effective_date": "2001-08-01",
        "enforcement": "Minnesota courts",
        "penalties": "Damages, repossession, contract rescission",
    },
    "landlord_tenant_as_contract": {
        "id": "landlord_tenant_as_contract",
        "title": "Landlord-Tenant Relationship as Contract",
        "citation": "Minn. Stat. § 504B",
        "category": "commerce",
        "subcategory": "lease_contract",
        "jurisdiction": "state",
        "summary": "A residential lease is a contract between landlord and tenant. Both parties must follow its terms, and Minnesota law provides minimum standards that cannot be waived.",
        "key_points": [
            "Lease terms must comply with state law",
            "Provisions that waive tenant rights are generally unenforceable",
            "Oral leases are valid for shorter terms",
            "Landlord must provide a copy of the lease",
            "Rent, security deposit, and termination terms must be clear",
            "Breach of lease can lead to eviction or damages",
        ],
        "full_text": "The rights and obligations of landlords and tenants are governed by the lease agreement and by chapter 504B, which establishes minimum protections that may not be waived.",
        "related_forms": ["lease_agreement", "lease_termination_notice"],
        "effective_date": "1999-08-01",
        "enforcement": "Minnesota District Courts",
        "penalties": "Eviction, damages, attorney fees",
    },
    "minnesota_unconscionable_lease_terms": {
        "id": "minnesota_unconscionable_lease_terms",
        "title": "Unconscionable Lease Terms",
        "citation": "Minn. Stat. § 504B.121",
        "category": "commerce",
        "subcategory": "lease_contract",
        "jurisdiction": "state",
        "summary": "Minnesota law prohibits residential lease provisions that are unconscionable, including clauses that waive legal remedies or shift costs unfairly to the tenant.",
        "key_points": [
            "A court may refuse to enforce unconscionable lease terms",
            "Clauses waiving statutory rights are often void",
            "Liquidated-damage clauses are reviewed for fairness",
            "Attorney-fee clauses must be reciprocal",
            "Small-print or complex language is examined for fairness",
        ],
        "full_text": "A provision of a residential lease is void and unenforceable if it is unconscionable or if it purports to waive or limit rights or remedies available to the tenant under this chapter.",
        "related_forms": ["lease_review_request", "unconscionability_motion"],
        "effective_date": "1985-01-01",
        "enforcement": "Minnesota District Courts",
        "penalties": "Void terms, contract reformation, damages",
    },
    "minnesota_lease_renewal_nonrenewal": {
        "id": "minnesota_lease_renewal_nonrenewal",
        "title": "Lease Renewal and Non-Renewal",
        "citation": "Minn. Stat. § 504B.135",
        "category": "commerce",
        "subcategory": "lease_contract",
        "jurisdiction": "state",
        "summary": "Rules for ending or renewing a residential lease, including notice requirements for month-to-month and fixed-term tenancies.",
        "key_points": [
            "Month-to-month tenancies generally require notice equal to the rental period or less",
            "Fixed-term leases expire on their end date unless renewed",
            "Landlord must provide proper notice to terminate",
            "Retaliatory non-renewal may be challenged",
            "Local ordinances may add notice requirements",
        ],
        "full_text": "A landlord or tenant may terminate a tenancy for a definite term by giving notice at least one full rental period before the end of the term.",
        "related_forms": ["lease_termination_notice", "nonrenewal_response"],
        "effective_date": "1999-08-01",
        "enforcement": "Minnesota District Courts",
        "penalties": " wrongful eviction, rent abatement, damages",
    },
    "landlord_commercial_activity": {
        "id": "landlord_commercial_activity",
        "title": "Landlord Commercial Activity and Rental Operations",
        "citation": "Minn. Stat. § 322C; § 333",
        "category": "commerce",
        "subcategory": "landlord_business",
        "jurisdiction": "state",
        "summary": "Landlords operating rental property as a business must comply with entity, licensing, tax, and data-practices laws in Minnesota.",
        "key_points": [
            "Landlords may operate as individuals, LLCs, or other entities",
            "Some cities require rental licenses",
            "Business must report income and expenses for tax purposes",
            "Tenant screening and data handling are regulated",
            "Commercial leases have different rules than residential",
        ],
        "full_text": "The operation of rental property as a business subjects the landlord to general business, tax, licensing, and data-practices requirements in addition to landlord-tenant law.",
        "related_forms": ["rental_license_application", "business_registration"],
        "effective_date": "1999-01-01",
        "enforcement": "Minnesota Secretary of State; Minnesota Department of Revenue; cities",
        "penalties": "Fines, license revocation, tax penalties",
    },

    # === Accountability / enforcement ===
    "hud_fair_housing_complaint_process": {
        "id": "hud_fair_housing_complaint_process",
        "title": "HUD Fair Housing Complaint Process",
        "citation": "24 C.F.R. § 103",
        "category": "accountability",
        "subcategory": "federal_enforcement",
        "jurisdiction": "federal",
        "summary": "The administrative process for filing and resolving discrimination complaints with HUD's Office of Fair Housing and Equal Opportunity (FHEO).",
        "key_points": [
            "Complaint must be filed within one year of the alleged act",
            "HUD investigates and attempts conciliation",
            "If reasonable cause is found, HUD may charge before an administrative law judge",
            "Complainants may elect to have the case heard in federal court",
            "May result in damages, injunctive relief, civil penalties, and attorney fees",
        ],
        "full_text": "Any person aggrieved by a discriminatory housing practice may file a complaint with the Secretary within one year after the alleged discriminatory housing practice occurred.",
        "related_forms": ["hud_fair_housing_complaint", "conciliation_agreement"],
        "effective_date": "1968-04-11",
        "enforcement": "HUD FHEO; DOJ; federal courts",
        "penalties": "Actual and punitive damages, civil penalties up to $150,000, attorney fees",
    },
    "fair_housing_enforcement_rem edies": {
        "id": "fair_housing_enforcement_remedies",
        "title": "Fair Housing Act Enforcement and Remedies",
        "citation": "42 U.S.C. § 3613",
        "category": "accountability",
        "subcategory": "federal_enforcement",
        "jurisdiction": "federal",
        "summary": "Provides private and governmental enforcement rights, remedies, and penalties for Fair Housing Act violations.",
        "key_points": [
            "Private persons may sue in federal or state court",
            "Attorney fees and costs available to prevailing parties",
            "Compensatory and punitive damages available",
            "DOJ may bring civil actions for pattern-or-practice discrimination",
            "Injunctive relief and equitable relief available",
            "Statute of limitations is generally two years",
        ],
        "full_text": "The Attorney General may commence a civil action in any appropriate United States district court against any person that the Attorney General has reasonable cause to believe is engaged in a pattern or practice of resistance to the full enjoyment of any of the rights granted by this subchapter.",
        "related_forms": ["fair_housing_lawsuit", "hud_complaint_form"],
        "effective_date": "1968-04-11",
        "enforcement": "DOJ; HUD; federal and state courts",
        "penalties": "Unlimited compensatory and punitive damages, civil penalties, attorney fees",
    },
    "minnesota_attorney_general_landlord_tenant": {
        "id": "minnesota_attorney_general_landlord_tenant",
        "title": "Minnesota Attorney General Landlord-Tenant Enforcement",
        "citation": "Minn. Stat. § 8.31",
        "category": "accountability",
        "subcategory": "state_enforcement",
        "jurisdiction": "state",
        "summary": "Authorizes the Minnesota Attorney General to investigate and take civil action against deceptive, fraudulent, or illegal landlord practices.",
        "key_points": [
            "Can bring civil actions for consumer fraud and deceptive trade practices",
            "May obtain injunctions, restitution, civil penalties, and attorney fees",
            "Often used for systemic landlord abuses",
            "Tenants can also file private lawsuits under Minn. Stat. § 325F",
            "Complaints can be filed online or by mail",
        ],
        "full_text": "The Attorney General has the authority to investigate and prosecute violations of Minnesota laws that protect consumers, including tenants, from deceptive, fraudulent, and unfair practices.",
        "related_forms": ["ag_complaint", "consumer_fraud_complaint"],
        "effective_date": "1973-01-01",
        "enforcement": "Minnesota Attorney General's Office",
        "penalties": "Civil penalties, restitution, injunctions, attorney fees",
    },
    "minnesota_consumer_fraud_act": {
        "id": "minnesota_consumer_fraud_act",
        "title": "Minnesota Consumer Fraud Act",
        "citation": "Minn. Stat. § 325F.69",
        "category": "accountability",
        "subcategory": "consumer_protection",
        "jurisdiction": "state",
        "summary": "Prohibits deceptive trade practices and false statements in consumer transactions, including rental advertising and lease representations.",
        "key_points": [
            "False or misleading advertising is prohibited",
            "Applies to rental listings, lease terms, and fee disclosures",
            "Private lawsuits allowed with actual damages and attorney fees",
            "Attorney General can enforce",
            "Does not require proof of intent for some violations",
        ],
        "full_text": "The act, use, or employment by any person of any fraud, deception, misleading practice, misrepresentation, or concealment of material fact with intent that others rely thereon in connection with the sale or advertisement of any merchandise is unlawful.",
        "related_forms": ["consumer_fraud_complaint", "ag_complaint"],
        "effective_date": "1973-01-01",
        "enforcement": "Minnesota Attorney General; private lawsuits",
        "penalties": "Actual damages, attorney fees, civil penalties, injunctions",
    },
    "minnesota_deceptive_trade_practices": {
        "id": "minnesota_deceptive_trade_practices",
        "title": "Minnesota Deceptive Trade Practices",
        "citation": "Minn. Stat. § 325F.67",
        "category": "accountability",
        "subcategory": "consumer_protection",
        "jurisdiction": "state",
        "summary": "Lists specific prohibited deceptive acts, such as bait-and-switch, fake discounts, and misrepresenting the characteristics of rental property.",
        "key_points": [
            "Misrepresenting the condition or availability of a unit is prohibited",
            "Bait advertising is unlawful",
            "Passing off used items as new is prohibited",
            "Private right of action and Attorney General enforcement",
            "Important for rental scams and false advertising",
        ],
        "full_text": "A person engages in a deceptive trade practice when, in the course of business, the person knowingly passes off goods or services as those of another, or knowingly makes a false representation as to the source, sponsorship, approval, or certification of goods or services.",
        "related_forms": ["deceptive_trade_complaint", "ag_complaint"],
        "effective_date": "1973-01-01",
        "enforcement": "Minnesota Attorney General; private lawsuits",
        "penalties": "Injunctive relief, civil penalties, damages, attorney fees",
    },
    "tenant_remedies_landlord_accountability": {
        "id": "tenant_remedies_landlord_accountability",
        "title": "Tenant Remedies and Landlord Accountability",
        "citation": "Minn. Stat. § 504B.395",
        "category": "accountability",
        "subcategory": "tenant_remedies",
        "jurisdiction": "state",
        "summary": "Minnesota law gives tenants several remedies when a landlord fails to maintain the property or comply with the lease, including rent abatement, repair-and-deduct, and early termination.",
        "key_points": [
            "Tenant can seek rent abatement for reduced property value",
            "Repair-and-deduct is allowed in some circumstances",
            "Tenant may terminate for material breach",
            "Retaliation is prohibited",
            "Attorney fees may be recoverable",
            "Document all conditions and communications",
        ],
        "full_text": "A tenant may seek any equitable or legal remedy available for breach of the landlord's covenants, including rent abatement, damages, injunction, and termination of the tenancy.",
        "related_forms": ["rent_abatement_request", "repair_and_deduct_notice"],
        "effective_date": "1999-08-01",
        "enforcement": "Minnesota District Courts",
        "penalties": "Damages, rent abatement, lease termination, attorney fees",
    },
    "minneapolis_violations_bureau": {
        "id": "minneapolis_violations_bureau",
        "title": "Minneapolis Housing Inspections and Violations Bureau",
        "citation": "Minneapolis Code § 244",
        "category": "accountability",
        "subcategory": "local_enforcement",
        "jurisdiction": "local",
        "summary": "Minneapolis enforces housing codes through inspections, citations, and orders to correct dangerous or substandard conditions.",
        "key_points": [
            "Tenants and city inspectors can report code violations",
            "Landlords must correct violations within a set time",
            "The city can issue administrative penalties",
            "Emergency repairs can be ordered",
            "Rental license can be revoked for serious or repeated violations",
        ],
        "full_text": "The City of Minneapolis may inspect rental dwellings, issue correction orders, and impose administrative penalties for violations of the housing and rental license code.",
        "related_forms": ["code_violation_complaint", "rental_license_complaint"],
        "effective_date": "2018-01-01",
        "enforcement": "Minneapolis Regulatory Services",
        "penalties": "Fines, correction orders, license revocation",
    },
    "retaliation_protections_accountability": {
        "id": "retaliation_protections_accountability",
        "title": "Retaliation Protections as Accountability",
        "citation": "Minn. Stat. § 504B.285",
        "category": "accountability",
        "subcategory": "retaliation",
        "jurisdiction": "state",
        "summary": "Landlords cannot retaliate against tenants for exercising legal rights, such as reporting code violations or joining a tenant union.",
        "key_points": [
            "Protected activity includes complaints to government and good-faith repair requests",
            "Retaliatory eviction is a defense in court",
            "Retaliatory rent increases are prohibited",
            "Tenant has the burden of showing the landlord's action was retaliatory",
            "Protections do not excuse nonpayment of rent",
        ],
        "full_text": "A landlord may not increase rent, decrease services, or evict a tenant because the tenant has complained to a governmental authority about a code violation or has organized or become a member of a tenants' union.",
        "related_forms": ["retaliation_defense", "tenant_rights_complaint"],
        "effective_date": "1999-08-01",
        "enforcement": "Minnesota District Courts",
        "penalties": "Eviction dismissal, damages, attorney fees, restored services",
    },

    # === Additional housing / property basics ===
    "housing_quality_standards": {
        "id": "housing_quality_standards",
        "title": "HUD Housing Quality Standards (HQS)",
        "citation": "24 C.F.R. § 982.401",
        "category": "accountability",
        "subcategory": "housing_quality",
        "jurisdiction": "federal",
        "summary": "Minimum health and safety standards that units must meet before a family can move into HUD-assisted housing and periodically thereafter.",
        "key_points": [
            "Covers sanitary facilities, food preparation, space and security, thermal environment, illumination, electricity, structure, and smoke detectors",
            "PHAs or their inspectors perform inspections",
            "Landlord must correct HQS failures",
            "Tenant may be abated if HQS failures persist",
            "Applies to Section 8 vouchers and project-based assistance",
        ],
        "full_text": "A dwelling unit must meet HUD housing quality standards and any additional PHA quality standards in order to be approved for or continue participation in the Section 8 program.",
        "related_forms": ["hqs_inspection_request", "hqs_failure_appeal"],
        "effective_date": "1974-08-22",
        "enforcement": "PHAs; HUD",
        "penalties": "Unit disapproval, payment abatement, contract termination",
    },
    "reasonable_accommodation_hud": {
        "id": "reasonable_accommodation_hud",
        "title": "Reasonable Accommodations in Federally Assisted Housing",
        "citation": "24 C.F.R. § 100.204",
        "category": "service_animals",
        "subcategory": "reasonable_accommodations",
        "jurisdiction": "federal",
        "summary": "HUD regulation implementing the Fair Housing Act requirement that housing providers make reasonable accommodations for persons with disabilities.",
        "key_points": [
            "Accommodation must be necessary for equal use and enjoyment",
            "Cannot impose undue financial or administrative burden",
            "Cannot fundamentally alter the program",
            "Examples include assistance animals, parking, and transfer policies",
            "Request and response should be documented",
        ],
        "full_text": "It shall be unlawful to refuse to make reasonable accommodations in rules, policies, practices, or services, when such accommodations may be necessary to afford a person with a disability an equal opportunity to use and enjoy a dwelling.",
        "related_forms": ["reasonable_accommodation_request", "hud_complaint_form"],
        "effective_date": "1996-03-05",
        "enforcement": "HUD FHEO; DOJ; federal courts",
        "penalties": "Damages, injunctive relief, attorney fees, civil penalties",
    },
    "vawa_protections_expanded": {
        "id": "vawa_protections_expanded",
        "title": "VAWA Housing Protections — Expanded",
        "citation": "34 U.S.C. § 12491",
        "category": "accountability",
        "subcategory": "victim_protections",
        "jurisdiction": "federal",
        "summary": "Expanded summary of housing protections for victims of domestic violence, dating violence, sexual assault, and stalking in federally assisted housing.",
        "key_points": [
            "Victims cannot be evicted or denied housing based on the violence",
            "May terminate lease early without penalty",
            "May request emergency transfer",
            "Confidentiality of victim information required",
            "Notice of VAWA rights must be provided",
            "Also applies to Section 8 vouchers, public housing, LIHTC, and others",
        ],
        "full_text": "A covered housing provider shall not, on the basis of domestic violence, dating violence, sexual assault, or stalking, deny assistance to, or terminate assistance of, an individual who is or has been a victim of such violence.",
        "related_forms": ["vawa_lease_termination", "emergency_transfer_request"],
        "effective_date": "2013-03-07",
        "enforcement": "HUD; DOJ; federal courts",
        "penalties": "Damages, injunctive relief, attorney fees, civil penalties",
    },
}
