"""Emotion module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="emotion",
    group_name="emotion_emotional_state",
    title="Emotion Get Emotional State (GET) (SSOT)",
    description="Get current emotional state for user.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.emotion.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="emotion",
    group_name="emotion_record_trigger",
    title="Emotion Record Trigger (POST) (SSOT)",
    description="POST /trigger",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.emotion.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="emotion",
    group_name="emotion_dashboard_configuration",
    title="Emotion Get Dashboard Configuration (GET) (SSOT)",
    description="Get full adaptive dashboard configuration.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.emotion.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="emotion",
    group_name="emotion_ui_settings",
    title="Emotion Get Ui Settings (GET) (SSOT)",
    description="Get UI adaptation settings only.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.emotion.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="emotion",
    group_name="emotion_suggested_action",
    title="Emotion Get Suggested Action (GET) (SSOT)",
    description="Get the emotionally-appropriate next action for user.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.emotion.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="emotion",
    group_name="emotion_available_triggers",
    title="Emotion List Available Triggers (GET) (SSOT)",
    description="List all available emotional triggers.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.emotion.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="emotion",
    group_name="emotion_simulate_emotional_scenario",
    title="Emotion Simulate Emotional Scenario (POST) (SSOT)",
    description="POST /simulate-scenario",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.emotion.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="emotion",
    group_name="emotion_emotional_history",
    title="Emotion Get Emotional History (GET) (SSOT)",
    description="GET /history",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.emotion.router",),
    deterministic=True,
))
