"""Setup module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group


register_function_group(FunctionGroupContract(
    module="setup",
    group_name="setup_check_setup_needed",
    title="Setup Check Setup Needed (GET) (SSOT)",
    description="Public endpoint - no auth required.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.setup.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="setup",
    group_name="setup_skip_setup",
    title="Setup Skip Setup (POST) (SSOT)",
    description="Skip setup wizard (for development/demo mode).",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.setup.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="setup",
    group_name="setup_reset_setup",
    title="Setup Reset Setup (POST) (SSOT)",
    description="POST /reset",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.setup.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="setup",
    group_name="setup_setup_status",
    title="Setup Get Setup Status (GET) (SSOT)",
    description="GET /status",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.setup.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="setup",
    group_name="setup_save_profile",
    title="Setup Save Profile (POST) (SSOT)",
    description="POST /profile",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.setup.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="setup",
    group_name="setup_profile",
    title="Setup Get Profile (GET) (SSOT)",
    description="GET /profile",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.setup.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="setup",
    group_name="setup_save_case_info",
    title="Setup Save Case Info (POST) (SSOT)",
    description="POST /case",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.setup.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="setup",
    group_name="setup_case_info",
    title="Setup Get Case Info (GET) (SSOT)",
    description="GET /case",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.setup.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="setup",
    group_name="setup_configure_storage",
    title="Setup Configure Storage (POST) (SSOT)",
    description="POST /storage",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.setup.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="setup",
    group_name="setup_storage_config",
    title="Setup Get Storage Config (GET) (SSOT)",
    description="GET /storage",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.setup.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="setup",
    group_name="setup_upload_document",
    title="Setup Upload Document (POST) (SSOT)",
    description="POST /documents/upload",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.setup.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="setup",
    group_name="setup_uploaded_documents",
    title="Setup Get Uploaded Documents (GET) (SSOT)",
    description="GET /documents",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.setup.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="setup",
    group_name="setup_process_all_documents",
    title="Setup Process All Documents (POST) (SSOT)",
    description="POST /documents/process",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.setup.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="setup",
    group_name="setup_complete_setup",
    title="Setup Complete Setup (POST) (SSOT)",
    description="POST /complete",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.setup.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="setup",
    group_name="setup_setup_summary",
    title="Setup Get Setup Summary (GET) (SSOT)",
    description="GET /summary",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.setup.router",),
    deterministic=True,
))
