"""Export_Import module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(
    FunctionGroupContract(
        module="export_import",
        group_name="export_import_export_request_endpoint",
        title="Export_Import Create Export Request Endpoint (POST) (SSOT)",
        description="POST /export/request",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.export_import.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="export_import",
        group_name="export_import_process_export_endpoint",
        title="Export_Import Process Export Endpoint (POST) (SSOT)",
        description="POST /export/{export_id}/process",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.export_import.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="export_import",
        group_name="export_import_export_status_endpoint",
        title="Export_Import Get Export Status Endpoint (GET) (SSOT)",
        description="GET /export/{export_id}",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.export_import.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="export_import",
        group_name="export_import_download_export_endpoint",
        title="Export_Import Download Export Endpoint (GET) (SSOT)",
        description="GET /export/{export_id}/download",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.export_import.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="export_import",
        group_name="export_import_user_exports_endpoint",
        title="Export_Import Get User Exports Endpoint (GET) (SSOT)",
        description="GET /exports",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.export_import.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="export_import",
        group_name="export_import_export_endpoint",
        title="Export_Import Delete Export Endpoint (DELETE) (SSOT)",
        description="DELETE /export/{export_id}",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.export_import.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="export_import",
        group_name="export_import_prepare_import_endpoint",
        title="Export_Import Prepare Import Endpoint (POST) (SSOT)",
        description="POST /import/prepare",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.export_import.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="export_import",
        group_name="export_import_upload_import_file_endpoint",
        title="Export_Import Upload Import File Endpoint (POST) (SSOT)",
        description="POST /import/upload/{import_id}",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.export_import.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="export_import",
        group_name="export_import_process_import_endpoint",
        title="Export_Import Process Import Endpoint (POST) (SSOT)",
        description="POST /import/{import_id}/process",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.export_import.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="export_import",
        group_name="export_import_export_statistics_endpoint",
        title="Export_Import Get Export Statistics Endpoint (GET) (SSOT)",
        description="GET /export/statistics",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.export_import.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="export_import",
        group_name="export_import_supported_formats_endpoint",
        title="Export_Import Get Supported Formats Endpoint (GET) (SSOT)",
        description="Get list of supported export and import formats.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.export_import.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="export_import",
        group_name="export_import_cleanup_exports_endpoint",
        title="Export_Import Cleanup Exports Endpoint (POST) (SSOT)",
        description="POST /cleanup",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.export_import.router",),
        deterministic=False,
    )
)
