python#!/usr/bin/env python3
"""
Semptify 5.0 — AI Context Compiler & State Sync Core
Mandated Python Version: 3.11.9
File Location: scripts/compile_ai_context.py

This script automates Layer 0 Operations:
1. Validates and generates a blank .ai_state.json if missing.
2. Compiles Blueprint, Project Bible, and Framework docs into a clean Handoff Packet.
"""

import os
import json
import subprocess
from datetime import datetime, timezone

# Define exact canonical file paths
AI_STATE_FILE = ".ai_state.json"
OUTPUT_PACKET_FILE = "DOCUMENTS/AI_HANDOFF_PACKET.md"

TARGET_DOCS = [
    "BLUEPRINT.md",
    "PROJECT_BIBLE.md",
    "GUI_PHASE1_DESIGN.md"
]

DEFAULT_STATE_SCHEMA = {
    "schema_version": "1.0.0",
    "last_sync_timestamp": "",
    "active_git_commit": "",
    "current_lock": {
        "is_locked": False,
        "locked_by_agent": "",
        "target_directory": ""
    },
    "completed_transactions": []
}

TRANSACTION_TEMPLATE = {
    "task_id": "TSK-000",
    "routing_tag": "EI",
    "resolved_at": "",
    "files_modified": [],
    "verification_output": ""
}

def get_git_commit():
    """Retrieves the current local git commit hash safely."""
    try:
        commit = subprocess.check_output(["git", "rev-parse", "HEAD"]).decode("utf-8").strip()
        return commit
    except Exception:
        return "NO_GIT_REPOSITORY_DETECTED"

def initialize_ai_state():
    """Ensures .ai_state.json exists and strictly adheres to the schema footprint."""
    print("Checking system state log...")
    if not os.path.exists(AI_STATE_FILE):
        current_schema = DEFAULT_STATE_SCHEMA.copy()
        current_schema["last_sync_timestamp"] = datetime.now(timezone.utc).isoformat() + "Z"
        current_schema["active_git_commit"] = get_git_commit()

        with open(AI_STATE_FILE, "w", encoding="utf-8") as f:
            json.dump(current_schema, f, indent=4)
        print(f" -> Initialized blank state tracking cluster at {AI_STATE_FILE}")
    else:
        try:
            with open(AI_STATE_FILE, "r", encoding="utf-8") as f:
                data = json.load(f)
            # Sync live Git commit baseline
            data["active_git_commit"] = get_git_commit()
            data["last_sync_timestamp"] = datetime.now(timezone.utc).isoformat() + "Z"
            with open(AI_STATE_FILE, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=4)
            print(" -> System state synchronized with active Git workspace.")
        except json.JSONDecodeError:
            print(" [!] WARNING: .ai_state.json is malformed. Repairing layout to schema base.")
            # Backup broken state safely
            os.rename(AI_STATE_FILE, f"{AI_STATE_FILE}.corrupt")
            initialize_ai_state()

def compile_handoff_packet():
    """Gathers canonical markdown files and compiles them into a unified payload wrapper."""
    print("Compiling context payload for external tools...")
    os.makedirs(os.path.dirname(OUTPUT_PACKET_FILE), exist_ok=True)

    current_hash = get_git_commit()
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    packet_header = (
        f"<!-- AUTOMATICALLY GENERATED BY SEMPTIFY CONTEXT COMPILER -->\n"
        f"# SEMPTIFY 5.0 — MASTER AI HANDOFF PACKET\n"
        f"**Generated:** {timestamp} | **Baseline Git Commit:** `{current_hash}`\n"
        f"**Instructions for External Tool:** Read this compiled file entirely before processing context. "
        f"Do not break directory structures outlined below.\n\n"
        f"---\n\n"
    )

    with open(OUTPUT_PACKET_FILE, "w", encoding="utf-8") as out:
        out.write(packet_header)

        # Inject Active .ai_state transaction summary first
        if os.path.exists(AI_STATE_FILE):
            out.write("## ACTIVE LAYER WORKSPACE LOCK STATE\n```json\n")
            with open(AI_STATE_FILE, "r", encoding="utf-8") as state_f:
                out.write(state_f.read())
            out.write("\n```\n\n---\n\n")

        # Append all key structural files
        for doc_name in TARGET_DOCS:
            if os.path.exists(doc_name):
                print(f" -> Merging {doc_name}")
                out.write(f"# FILE SSOT REFERENCE: /{doc_name}\n\n")
                with open(doc_name, "r", encoding="utf-8") as doc_f:
                    out.write(doc_f.read())
                out.write("\n\n---\n\n")
            else:
                print(f" [!] Skip: Reference file /{doc_name} was not found.")

    print(f" -> SUCCESS: Context packet successfully deployed to {OUTPUT_PACKET_FILE}")

if __name__ == "__main__":s
    compile_handoff_packet()
