"""Progress module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="progress",
    group_name="progress_progress",
    title="Progress Get Progress (GET) (SSOT)",
    description="GET /",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.progress.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="progress",
    group_name="progress_case_readiness",
    title="Progress Get Case Readiness (GET) (SSOT)",
    description="GET /readiness",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.progress.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="progress",
    group_name="progress_all_milestones",
    title="Progress Get All Milestones (GET) (SSOT)",
    description="GET /milestones",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.progress.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="progress",
    group_name="progress_next_milestones",
    title="Progress Get Next Milestones (GET) (SSOT)",
    description="GET /milestones/next",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.progress.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="progress",
    group_name="progress_complete_milestone",
    title="Progress Complete Milestone (POST) (SSOT)",
    description="POST /milestones/complete",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.progress.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="progress",
    group_name="progress_skip_milestone",
    title="Progress Skip Milestone (POST) (SSOT)",
    description="POST /milestones/skip/{milestone_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.progress.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="progress",
    group_name="progress_points",
    title="Progress Get Points (GET) (SSOT)",
    description="GET /points",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.progress.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="progress",
    group_name="progress_stats",
    title="Progress Get Stats (GET) (SSOT)",
    description="GET /stats",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.progress.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="progress",
    group_name="progress_increment_stat",
    title="Progress Increment Stat (POST) (SSOT)",
    description="POST /stat/{stat}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.progress.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="progress",
    group_name="progress_setup_case",
    title="Progress Setup Case (POST) (SSOT)",
    description="POST /setup",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.progress.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="progress",
    group_name="progress_journey_overview",
    title="Progress Get Journey Overview (GET) (SSOT)",
    description="GET /journey",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.progress.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="progress",
    group_name="progress_achievements",
    title="Progress Get Achievements (GET) (SSOT)",
    description="GET /achievements",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.progress.router",),
    deterministic=True,
))
