"""Role_Upgrade module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(
    FunctionGroupContract(
        module="role_upgrade",
        group_name="role_upgrade_available_roles",
        title="Role_Upgrade Get Available Roles (GET) (SSOT)",
        description="Get all available roles and their requirements.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.role_upgrade.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="role_upgrade",
        group_name="role_upgrade_role_requirements",
        title="Role_Upgrade Get Role Requirements (GET) (SSOT)",
        description="Get detailed requirements for a specific role.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.role_upgrade.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="role_upgrade",
        group_name="role_upgrade_request_role_upgrade",
        title="Role_Upgrade Request Role Upgrade (POST) (SSOT)",
        description="POST /upgrade",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.role_upgrade.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="role_upgrade",
        group_name="role_upgrade_my_role",
        title="Role_Upgrade Get My Role (GET) (SSOT)",
        description="GET /my-role",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.role_upgrade.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="role_upgrade",
        group_name="role_upgrade_trusted_organizations",
        title="Role_Upgrade Get Trusted Organizations (GET) (SSOT)",
        description="Get list of trusted organizations whose email domains auto-verify.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.role_upgrade.router",),
        deterministic=True,
    )
)
