"""Research module registration helper — FunctionGroupContracts.

Auto-generated by _fix_dups.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="research",
    group_name="research_health_check",
    title="Research Research Health Check (GET) (SSOT)",
    description="Health check for research module",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.research.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="research",
    group_name="research_property",
    title="Research Research Property (POST) (SSOT)",
    description="POST /property/{property_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.research.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="research",
    group_name="research_property_profile",
    title="Research Get Property Profile (GET) (SSOT)",
    description="GET /property/{property_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.research.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="research",
    group_name="research_property_summary",
    title="Research Get Property Summary (GET) (SSOT)",
    description="GET /property/{property_id}/summary",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.research.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="research",
    group_name="research_property_fraud_flags",
    title="Research Get Property Fraud Flags (GET) (SSOT)",
    description="GET /property/{property_id}/fraud-flags",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.research.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="research",
    group_name="research_download_evidence_zip",
    title="Research Download Evidence Zip (GET) (SSOT)",
    description="GET /property/{property_id}/download",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.research.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="research",
    group_name="research_checkpoint",
    title="Research Get Checkpoint (GET) (SSOT)",
    description="GET /checkpoint/{checkpoint_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.research.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="research",
    group_name="research_assessor_data_query",
    title="Research Get Assessor Data Query (GET) (SSOT)",
    description="GET /assessor",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.research.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="research",
    group_name="research_create_assessor_data",
    title="Research Post Assessor Data (POST) (SSOT)",
    description="POST /assessor",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.research.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="research",
    group_name="research_get_assessor_data",
    title="Research Get Assessor Data (GET) (SSOT)",
    description="GET /assessor/{property_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.research.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="research",
    group_name="research_recorder_data",
    title="Research Get Recorder Data (GET) (SSOT)",
    description="GET /recorder/{property_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.research.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="research",
    group_name="research_ucc_filings",
    title="Research Get Ucc Filings (GET) (SSOT)",
    description="GET /ucc",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.research.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="research",
    group_name="research_dispatch_calls",
    title="Research Get Dispatch Calls (GET) (SSOT)",
    description="GET /dispatch",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.research.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="research",
    group_name="research_news_mentions",
    title="Research Get News Mentions (GET) (SSOT)",
    description="GET /news",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.research.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="research",
    group_name="research_sos_entity",
    title="Research Get Sos Entity (GET) (SSOT)",
    description="GET /sos",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.research.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="research",
    group_name="research_bankruptcy_cases",
    title="Research Get Bankruptcy Cases (GET) (SSOT)",
    description="GET /bankruptcy",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.research.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="research",
    group_name="research_insurance_info",
    title="Research Get Insurance Info (GET) (SSOT)",
    description="GET /insurance",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.research.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="research",
    group_name="research_data_sources",
    title="Research List Data Sources (GET) (SSOT)",
    description="GET /sources",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.research.router",),
    deterministic=True,
))
