"""Auto_Mode module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group


register_function_group(FunctionGroupContract(
    module="auto_mode",
    group_name="auto_mode_auto_mode_status",
    title="Auto_Mode Get Auto Mode Status (GET) (SSOT)",
    description="GET /status",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.auto_mode.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="auto_mode",
    group_name="auto_mode_toggle_auto_mode",
    title="Auto_Mode Toggle Auto Mode (POST) (SSOT)",
    description="POST /toggle",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.auto_mode.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="auto_mode",
    group_name="auto_mode_auto_mode_config",
    title="Auto_Mode Update Auto Mode Config (POST) (SSOT)",
    description="POST /config",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.auto_mode.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="auto_mode",
    group_name="auto_mode_available_features",
    title="Auto_Mode Get Available Features (GET) (SSOT)",
    description="GET /features",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.auto_mode.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="auto_mode",
    group_name="auto_mode_analysis_summary",
    title="Auto_Mode Get Analysis Summary (GET) (SSOT)",
    description="GET /analysis/{doc_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.auto_mode.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="auto_mode",
    group_name="auto_mode_run_analysis_on_document",
    title="Auto_Mode Run Analysis On Document (POST) (SSOT)",
    description="POST /run-analysis/{doc_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.auto_mode.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="auto_mode",
    group_name="auto_mode_run_batch_analysis",
    title="Auto_Mode Run Batch Analysis (POST) (SSOT)",
    description="POST /batch-analysis",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.auto_mode.router",),
    deterministic=False,
))
