"""Testing module registration helper — FunctionGroupContracts.

Auto-generated by _fix_dups.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="testing",
    group_name="testing_create_test_suite_endpoint",
    title="Testing Create Test Suite Endpoint (POST) (SSOT)",
    description="POST /suites",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.testing.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="testing",
    group_name="testing_get_test_suite_endpoint",
    title="Testing Get Test Suite Endpoint (GET) (SSOT)",
    description="GET /suites/{suite_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.testing.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="testing",
    group_name="testing_test_suites",
    title="Testing List Test Suites (GET) (SSOT)",
    description="GET /suites",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.testing.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="testing",
    group_name="testing_run_test_suite_endpoint",
    title="Testing Run Test Suite Endpoint (POST) (SSOT)",
    description="POST /run",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.testing.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="testing",
    group_name="testing_test_run_endpoint",
    title="Testing Get Test Run Endpoint (GET) (SSOT)",
    description="GET /run/{run_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.testing.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="testing",
    group_name="testing_test_results_endpoint",
    title="Testing Get Test Results Endpoint (GET) (SSOT)",
    description="GET /run/{run_id}/results",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.testing.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="testing",
    group_name="testing_test_statistics_endpoint",
    title="Testing Get Test Statistics Endpoint (GET) (SSOT)",
    description="GET /statistics",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.testing.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="testing",
    group_name="testing_pipeline_endpoint",
    title="Testing Create Pipeline Endpoint (POST) (SSOT)",
    description="POST /pipeline/create",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.testing.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="testing",
    group_name="testing_run_pipeline_endpoint",
    title="Testing Run Pipeline Endpoint (POST) (SSOT)",
    description="POST /pipeline/{pipeline_id}/run",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.testing.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="testing",
    group_name="testing_pipeline_run_endpoint",
    title="Testing Get Pipeline Run Endpoint (GET) (SSOT)",
    description="GET /pipeline/run/{run_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.testing.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="testing",
    group_name="testing_pipeline_statistics_endpoint",
    title="Testing Get Pipeline Statistics Endpoint (GET) (SSOT)",
    description="GET /pipeline/statistics",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.testing.router",),
    deterministic=True,
))
