"""Form_Data module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="form_data",
    group_name="form_data_form_data",
    title="Form_Data Get Form Data (GET) (SSOT)",
    description="GET /",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.form_data.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="form_data",
    group_name="form_data_extracted_data",
    title="Form_Data Get Extracted Data (GET) (SSOT)",
    description="GET /extracted",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.form_data.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="form_data",
    group_name="form_data_case_summary",
    title="Form_Data Get Case Summary (GET) (SSOT)",
    description="GET /summary",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.form_data.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="form_data",
    group_name="form_data_case_info",
    title="Form_Data Update Case Info (PUT) (SSOT)",
    description="PUT /case",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.form_data.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="form_data",
    group_name="form_data_answer_form_data",
    title="Form_Data Get Answer Form Data (GET) (SSOT)",
    description="GET /forms/answer",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.form_data.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="form_data",
    group_name="form_data_motion_form_data",
    title="Form_Data Get Motion Form Data (GET) (SSOT)",
    description="GET /forms/motion/{motion_type}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.form_data.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="form_data",
    group_name="form_data_counterclaim_form_data",
    title="Form_Data Get Counterclaim Form Data (GET) (SSOT)",
    description="GET /forms/counterclaim",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.form_data.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="form_data",
    group_name="form_data_add_defense",
    title="Form_Data Add Defense (POST) (SSOT)",
    description="POST /defenses/add",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.form_data.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="form_data",
    group_name="form_data_remove_defense",
    title="Form_Data Remove Defense (POST) (SSOT)",
    description="POST /defenses/remove",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.form_data.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="form_data",
    group_name="form_data_selected_defenses",
    title="Form_Data Get Selected Defenses (GET) (SSOT)",
    description="GET /defenses",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.form_data.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="form_data",
    group_name="form_data_add_counterclaim",
    title="Form_Data Add Counterclaim (POST) (SSOT)",
    description="POST /counterclaims/add",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.form_data.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="form_data",
    group_name="form_data_counterclaims",
    title="Form_Data Get Counterclaims (GET) (SSOT)",
    description="GET /counterclaims",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.form_data.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="form_data",
    group_name="form_data_case_documents",
    title="Form_Data Get Case Documents (GET) (SSOT)",
    description="GET /documents",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.form_data.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="form_data",
    group_name="form_data_case_timeline",
    title="Form_Data Get Case Timeline (GET) (SSOT)",
    description="GET /timeline",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.form_data.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="form_data",
    group_name="form_data_refresh_form_data",
    title="Form_Data Refresh Form Data (POST) (SSOT)",
    description="POST /refresh",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.form_data.router",),
    deterministic=False,
))
