"""Preamble module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="preamble",
    group_name="preamble_preamble",
    title="Preamble Preamble (GET) (SSOT)",
    description="Single entry point — routes every user to exactly where they need to go.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.preamble.router",),
    deterministic=True,
))
