"""Mesh_Network module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group


register_function_group(FunctionGroupContract(
    module="mesh_network",
    group_name="mesh_network_network_status",
    title="Mesh_Network Get Network Status (GET) (SSOT)",
    description="Get mesh network status including all modules and statistics.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mesh_network.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="mesh_network",
    group_name="mesh_network_network_graph",
    title="Mesh_Network Get Network Graph (GET) (SSOT)",
    description="Get the module dependency graph for visualization.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mesh_network.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="mesh_network",
    group_name="mesh_network_network_modules",
    title="Mesh_Network List Network Modules (GET) (SSOT)",
    description="List all connected modules and their capabilities.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mesh_network.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="mesh_network",
    group_name="mesh_network_call_module",
    title="Mesh_Network Call Module (POST) (SSOT)",
    description="POST /network/call",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mesh_network.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="mesh_network",
    group_name="mesh_network_call_many_modules",
    title="Mesh_Network Call Many Modules (POST) (SSOT)",
    description="POST /network/call-many",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mesh_network.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="mesh_network",
    group_name="mesh_network_start_collaboration",
    title="Mesh_Network Start Collaboration (POST) (SSOT)",
    description="POST /network/collaborate",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mesh_network.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="mesh_network",
    group_name="mesh_network_broadcast_event",
    title="Mesh_Network Broadcast Event (POST) (SSOT)",
    description="POST /network/broadcast",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mesh_network.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="mesh_network",
    group_name="mesh_network_ask_mesh",
    title="Mesh_Network Ask Mesh (POST) (SSOT)",
    description="POST /network/ask",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mesh_network.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="mesh_network",
    group_name="mesh_network_quick_case_summary",
    title="Mesh_Network Quick Case Summary (POST) (SSOT)",
    description="Quick endpoint: Get a complete case summary from all relevant modules.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mesh_network.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="mesh_network",
    group_name="mesh_network_quick_deadline_check",
    title="Mesh_Network Quick Deadline Check (POST) (SSOT)",
    description="Quick endpoint: Check all deadlines across all modules.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mesh_network.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="mesh_network",
    group_name="mesh_network_quick_build_defense",
    title="Mesh_Network Quick Build Defense (POST) (SSOT)",
    description="Quick endpoint: Collaborative defense building.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mesh_network.router",),
    deterministic=False,
))
