"""Zoom_Court_Prep module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="zoom_court_prep",
    group_name="zoom_court_prep_status",
    title="Zoom_Court_Prep Zoom Court Prep Status (GET) (SSOT)",
    description="GET /api/zoom-court-prep/status",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.zoom_court_prep.router",),
    deterministic=True,
))
