"""Extraction module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(
    FunctionGroupContract(
        module="extraction",
        group_name="extraction_extract_form_fields",
        title="Extraction Extract Form Fields (POST) (SSOT)",
        description="POST /extract",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.extraction.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="extraction",
        group_name="extraction_extract_from_vault_documents",
        title="Extraction Extract From Vault Documents (POST) (SSOT)",
        description="POST /extract-from-vault",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.extraction.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="extraction",
        group_name="extraction_review_items",
        title="Extraction Get Review Items (GET) (SSOT)",
        description="GET /review-items",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.extraction.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="extraction",
        group_name="extraction_confirm_extracted_fields",
        title="Extraction Confirm Extracted Fields (POST) (SSOT)",
        description="POST /confirm",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.extraction.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="extraction",
        group_name="extraction_apply_extraction_to_forms",
        title="Extraction Apply Extraction To Forms (POST) (SSOT)",
        description="POST /apply-to-forms",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.extraction.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="extraction",
        group_name="extraction_field_definitions",
        title="Extraction Get Field Definitions (GET) (SSOT)",
        description="Get definitions and help text for all form fields.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.extraction.router",),
        deterministic=True,
    )
)
