"""Recognition module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(
    FunctionGroupContract(
        module="recognition",
        group_name="recognition_analyze_text",
        title="Recognition Analyze Text (POST) (SSOT)",
        description="POST /analyze",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.recognition.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="recognition",
        group_name="recognition_analyze_file",
        title="Recognition Analyze File (POST) (SSOT)",
        description="POST /analyze-file",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.recognition.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="recognition",
        group_name="recognition_quick_classify",
        title="Recognition Quick Classify (POST) (SSOT)",
        description="POST /quick-classify",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.recognition.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="recognition",
        group_name="recognition_analyze_handwriting_endpoint",
        title="Recognition Analyze Handwriting Endpoint (POST) (SSOT)",
        description="POST /handwriting/analyze",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.recognition.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="recognition",
        group_name="recognition_verify_signature",
        title="Recognition Verify Signature (POST) (SSOT)",
        description="POST /signature/verify",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.recognition.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="recognition",
        group_name="recognition_forgery_types",
        title="Recognition Get Forgery Types (GET) (SSOT)",
        description="● Get all detectable forgery types.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.recognition.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="recognition",
        group_name="recognition_batch_analyze",
        title="Recognition Batch Analyze (POST) (SSOT)",
        description="POST /batch",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.recognition.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="recognition",
        group_name="recognition_document_types",
        title="Recognition Get Document Types (GET) (SSOT)",
        description="● Get all supported document types.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.recognition.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="recognition",
        group_name="recognition_entity_types",
        title="Recognition Get Entity Types (GET) (SSOT)",
        description="● Get all entity types the engine can extract.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.recognition.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="recognition",
        group_name="recognition_health",
        title="Recognition Recognition Health (GET) (SSOT)",
        description="● Health check for the recognition engine.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.recognition.router",),
        deterministic=True,
    )
)
