"""Development module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(
    FunctionGroupContract(
        module="development",
        group_name="development_run_crawl",
        title="Development Run Crawl (POST) (SSOT)",
        description="POST /crawl",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.development.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="development",
        group_name="development_crawl_report",
        title="Development Get Crawl Report (GET) (SSOT)",
        description="GET /crawl/report",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.development.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="development",
        group_name="development_run_analysis",
        title="Development Run Analysis (POST) (SSOT)",
        description="POST /analyze",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.development.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="development",
        group_name="development_dev_health",
        title="Development Dev Health (GET) (SSOT)",
        description="Get development tools health status.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.development.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="development",
        group_name="development_dev_metrics",
        title="Development Get Dev Metrics (GET) (SSOT)",
        description="GET /metrics",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.development.router",),
        deterministic=True,
    )
)
