"""Mndes module registration helper — FunctionGroupContracts.

Auto-generated by _fix_dups.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="mndes",
    group_name="mndes_guide",
    title="Mndes Mndes Guide (GET) (SSOT)",
    description="Serve the MNDES submission guide (step-by-step).",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mndes.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="mndes",
    group_name="mndes_compliance_guide",
    title="Mndes Mndes Compliance Guide (GET) (SSOT)",
    description="Serve the full MNDES compliance reference guide (all roles).",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mndes.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="mndes",
    group_name="mndes_acceptable_file_types",
    title="Mndes Get Acceptable File Types (GET) (SSOT)",
    description="Return the current MNDES Acceptable File Types List.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mndes.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="mndes",
    group_name="mndes_validate_file",
    title="Mndes Validate File (GET) (SSOT)",
    description="Validate a single filename for MNDES compliance.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mndes.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="mndes",
    group_name="mndes_validate_vault_files",
    title="Mndes Validate Vault Files (POST) (SSOT)",
    description="Validate a batch of vault files for MNDES compliance.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mndes.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="mndes",
    group_name="mndes_create_exhibit_package",
    title="Mndes Create Exhibit Package (POST) (SSOT)",
    description="Build an MNDES exhibit package for a court case.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mndes.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="mndes",
    group_name="mndes_get_exhibit_package",
    title="Mndes Get Exhibit Package (GET) (SSOT)",
    description="Retrieve an exhibit package and its compliance status.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mndes.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="mndes",
    group_name="mndes_submission_checklist",
    title="Mndes Get Submission Checklist (GET) (SSOT)",
    description="Return the pre-submission checklist for an exhibit package.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mndes.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="mndes",
    group_name="mndes_package_compliance",
    title="Mndes Get Package Compliance (GET) (SSOT)",
    description="Return compliance summary for a package.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mndes.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="mndes",
    group_name="mndes_apply_attestations",
    title="Mndes Apply Attestations (POST) (SSOT)",
    description="Record user attestations required before MNDES submission.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mndes.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="mndes",
    group_name="mndes_confirm_submission",
    title="Mndes Confirm Submission (POST) (SSOT)",
    description="User confirms they completed manual upload at the MNDES portal.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mndes.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="mndes",
    group_name="mndes_submission_guide",
    title="Mndes Get Submission Guide (GET) (SSOT)",
    description="Return structured step-by-step instructions for submitting exhibits to MNDES.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.mndes.router",),
    deterministic=True,
))
