"""Zoom_Court module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="zoom_court",
    group_name="zoom_court_status",
    title="Zoom_Court Zoom Court Status (GET) (SSOT)",
    description="GET /api/zoom-court/status",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.zoom_court.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="zoom_court",
    group_name="zoom_court_tech_checklist",
    title="Zoom_Court Tech Checklist (GET) (SSOT)",
    description="Technical checklist for virtual court hearings.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.zoom_court.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="zoom_court",
    group_name="zoom_court_etiquette_rules",
    title="Zoom_Court Etiquette Rules (GET) (SSOT)",
    description="Etiquette rules for virtual court hearings.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.zoom_court.router",),
    deterministic=True,
))
