"""Add MNDES and vault index tables

Revision ID: 20250506_add_mndes_and_vault_index
Revises: a0e7e8c78ccf
Create Date: 2026-05-06 00:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20250506_add_mndes_and_vault_index'
down_revision: Union[str, None] = 'a0e7e8c78ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create mndes_exhibit_packages table
    op.create_table(
        'mndes_exhibit_packages',
        sa.Column('package_id', sa.String(36), nullable=False),
        sa.Column('user_id', sa.String(24), nullable=False),
        sa.Column('mn_case_number', sa.String(50), nullable=False),
        sa.Column('case_type', sa.String(50), nullable=False, server_default='eviction'),
        sa.Column('case_caption', sa.String(255), nullable=True),
        sa.Column('package_name', sa.String(255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('exhibits_json', sa.Text(), nullable=False),
        sa.Column('requires_attestation', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('attestation_provided', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('attestation_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('attested_by', sa.String(100), nullable=True),
        sa.Column('status', sa.String(50), nullable=False, server_default='draft'),
        sa.Column('is_sealed_case', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('confirmation_number', sa.String(100), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('package_id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    )
    op.create_index('ix_mndes_exhibit_packages_user_id', 'mndes_exhibit_packages', ['user_id'])
    op.create_index('ix_mndes_exhibit_packages_mn_case_number', 'mndes_exhibit_packages', ['mn_case_number'])
    
    # Create mndes_exhibit_items table
    op.create_table(
        'mndes_exhibit_items',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('package_id', sa.String(36), nullable=False),
        sa.Column('user_id', sa.String(24), nullable=False),
        sa.Column('vault_id', sa.String(36), nullable=False),
        sa.Column('exhibit_number', sa.String(20), nullable=False),
        sa.Column('exhibit_name', sa.String(255), nullable=False),
        sa.Column('filename', sa.String(255), nullable=False),
        sa.Column('file_size_bytes', sa.Integer(), nullable=False),
        sa.Column('validation_json', sa.Text(), nullable=False),
        sa.Column('is_compliant', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('issues_json', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['package_id'], ['mndes_exhibit_packages.package_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    )
    op.create_index('ix_mndes_exhibit_items_package_id', 'mndes_exhibit_items', ['package_id'])
    op.create_index('ix_mndes_exhibit_items_user_id', 'mndes_exhibit_items', ['user_id'])
    op.create_index('ix_mndes_exhibit_items_vault_id', 'mndes_exhibit_items', ['vault_id'])
    
    # Create vault_index table
    op.create_table(
        'vault_index',
        sa.Column('vault_id', sa.String(36), nullable=False),
        sa.Column('user_id', sa.String(24), nullable=False),
        sa.Column('filename', sa.String(255), nullable=False),
        sa.Column('safe_filename', sa.String(255), nullable=False),
        sa.Column('sha256_hash', sa.String(64), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('mime_type', sa.String(100), nullable=False),
        sa.Column('storage_path', sa.String(500), nullable=False),
        sa.Column('storage_provider', sa.String(50), nullable=False),
        sa.Column('document_type', sa.String(50), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('tags', sa.String(500), nullable=True),
        sa.Column('certificate_id', sa.String(36), nullable=True),
        sa.Column('registry_id', sa.String(24), nullable=True),
        sa.Column('integrity_status', sa.String(20), nullable=False, server_default='unverified'),
        sa.Column('processed', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('extracted_data_json', sa.Text(), nullable=True),
        sa.Column('source_module', sa.String(50), nullable=False, server_default='direct'),
        sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('vault_id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    )
    op.create_index('ix_vault_index_user_id', 'vault_index', ['user_id'])
    op.create_index('ix_vault_index_sha256_hash', 'vault_index', ['sha256_hash'])
    op.create_index('ix_vault_index_registry_id', 'vault_index', ['registry_id'])
    
    # Create vault_user_index table
    op.create_table(
        'vault_user_index',
        sa.Column('user_id', sa.String(24), nullable=False),
        sa.Column('vault_id', sa.String(36), nullable=False),
        sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('user_id', 'vault_id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['vault_id'], ['vault_index.vault_id'], ondelete='CASCADE'),
    )
    
    # Create vault_hash_index table
    op.create_table(
        'vault_hash_index',
        sa.Column('sha256_hash', sa.String(64), nullable=False),
        sa.Column('vault_id', sa.String(36), nullable=False),
        sa.Column('user_id', sa.String(24), nullable=False),
        sa.Column('ref_count', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('sha256_hash'),
        sa.ForeignKeyConstraint(['vault_id'], ['vault_index.vault_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vault_hash_index')
    op.drop_table('vault_user_index')
    op.drop_index('ix_vault_index_registry_id', table_name='vault_index')
    op.drop_index('ix_vault_index_sha256_hash', table_name='vault_index')
    op.drop_index('ix_vault_index_user_id', table_name='vault_index')
    op.drop_table('vault_index')
    op.drop_index('ix_mndes_exhibit_items_vault_id', table_name='mndes_exhibit_items')
    op.drop_index('ix_mndes_exhibit_items_user_id', table_name='mndes_exhibit_items')
    op.drop_index('ix_mndes_exhibit_items_package_id', table_name='mndes_exhibit_items')
    op.drop_table('mndes_exhibit_items')
    op.drop_index('ix_mndes_exhibit_packages_mn_case_number', table_name='mndes_exhibit_packages')
    op.drop_index('ix_mndes_exhibit_packages_user_id', table_name='mndes_exhibit_packages')
    op.drop_table('mndes_exhibit_packages')
    # ### end Alembic commands ###
