"""Add force_fresh field to oauth_states table

Revision ID: 20260520_add_force_fresh_to_oauth_state
Revises: 20250508_force_widen_sessions_user_id
Create Date: 2026-05-20 18:10:00.000000

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260520_add_force_fresh_to_oauth_state"
down_revision: str | None = "20250508_force_widen_sessions_user_id"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("oauth_states", sa.Column("force_fresh", sa.Boolean(), nullable=True, server_default="false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oauth_states", "force_fresh")
    # ### end Alembic commands ###
