"""Add Part 3B context fact fields

Revision ID: 35e49b1cefed
Revises: f7a1c2d3e4b5
Create Date: 2026-09-10 16:44:43.022338

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e49b1cefed'
down_revision: Union[str, Sequence[str], None] = 'f7a1c2d3e4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add Part 3B structured-fact sourcing columns to context_facts.

    Defaults quarantine existing rows (ai_generated=true, unresolved) until
    the gatherer or an admin loader re-upserts them with resolved values.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'context_facts',
        sa.Column('fact_id', sa.String(length=255), nullable=True),
    )
    op.add_column(
        'context_facts',
        sa.Column('taxonomy_subject', sa.String(length=50), nullable=True),
    )
    op.add_column(
        'context_facts',
        sa.Column('source_authority', sa.String(length=100), nullable=True),
    )
    op.add_column(
        'context_facts',
        sa.Column(
            'resolution_status',
            sa.String(length=20),
            nullable=False,
            server_default=sa.text("'Unresolved'"),
        ),
    )
    op.add_column(
        'context_facts',
        sa.Column('resolution_method', sa.String(length=100), nullable=True),
    )
    op.add_column(
        'context_facts',
        sa.Column('resolved_date', sa.String(length=20), nullable=True),
    )
    op.add_column(
        'context_facts',
        sa.Column('last_verified_date', sa.String(length=20), nullable=True),
    )
    op.add_column(
        'context_facts',
        sa.Column(
            'ai_generated',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('true'),
        ),
    )
    op.add_column(
        'context_facts',
        sa.Column(
            'fabrication_check',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false'),
        ),
    )
    op.create_index(op.f('ix_context_facts_fact_id'), 'context_facts', ['fact_id'], unique=False)
    op.create_index('ix_context_facts_status', 'context_facts', ['resolution_status', 'ai_generated'], unique=False)
    op.create_index(op.f('ix_context_facts_taxonomy_subject'), 'context_facts', ['taxonomy_subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_context_facts_taxonomy_subject'), table_name='context_facts')
    op.drop_index('ix_context_facts_status', table_name='context_facts')
    op.drop_index(op.f('ix_context_facts_fact_id'), table_name='context_facts')
    op.drop_column('context_facts', 'fabrication_check')
    op.drop_column('context_facts', 'ai_generated')
    op.drop_column('context_facts', 'last_verified_date')
    op.drop_column('context_facts', 'resolved_date')
    op.drop_column('context_facts', 'resolution_method')
    op.drop_column('context_facts', 'resolution_status')
    op.drop_column('context_facts', 'source_authority')
    op.drop_column('context_facts', 'taxonomy_subject')
    op.drop_column('context_facts', 'fact_id')
    # ### end Alembic commands ###
