"""add_completed_groups_to_user

Revision ID: 81c36d8f2466
Revises: 6405f204d7dc
Create Date: 2026-04-07 20:07:52.563501

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81c36d8f2466"
down_revision: str | Sequence[str] | None = "6405f204d7dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("completed_groups", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "completed_groups")
    # ### end Alembic commands ###
