"""Vault_All_In_One module registration helper — FunctionGroupContracts.

Auto-generated by _fix_dups.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group


register_function_group(FunctionGroupContract(
    module="vault_all_in_one",
    group_name="vault_all_in_one_ingest_vault_item",
    title="Vault_All_In_One Ingest Vault Item (POST) (SSOT)",
    description="POST /items",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.vault_all_in_one.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="vault_all_in_one",
    group_name="vault_all_in_one_search_vault_items",
    title="Vault_All_In_One Search Vault Items (GET) (SSOT)",
    description="GET /items",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.vault_all_in_one.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="vault_all_in_one",
    group_name="vault_all_in_one_advanced_search_vault_items",
    title="Vault_All_In_One Advanced Search Vault Items (POST) (SSOT)",
    description="POST /items/search",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.vault_all_in_one.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="vault_all_in_one",
    group_name="vault_all_in_one_get_vault_item",
    title="Vault_All_In_One Get Vault Item (GET) (SSOT)",
    description="GET /items/{item_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.vault_all_in_one.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="vault_all_in_one",
    group_name="vault_all_in_one_update_vault_item",
    title="Vault_All_In_One Update Vault Item (PUT) (SSOT)",
    description="PUT /items/{item_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.vault_all_in_one.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="vault_all_in_one",
    group_name="vault_all_in_one_delete_vault_item",
    title="Vault_All_In_One Delete Vault Item (DELETE) (SSOT)",
    description="DELETE /items/{item_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.vault_all_in_one.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="vault_all_in_one",
    group_name="vault_all_in_one_vault_timeline",
    title="Vault_All_In_One Get Vault Timeline (GET) (SSOT)",
    description="GET /timeline",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.vault_all_in_one.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="vault_all_in_one",
    group_name="vault_all_in_one_create_incident",
    title="Vault_All_In_One Create Incident (POST) (SSOT)",
    description="POST /incidents",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.vault_all_in_one.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="vault_all_in_one",
    group_name="vault_all_in_one_incidents",
    title="Vault_All_In_One List Incidents (GET) (SSOT)",
    description="GET /incidents",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.vault_all_in_one.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="vault_all_in_one",
    group_name="vault_all_in_one_get_incident",
    title="Vault_All_In_One Get Incident (GET) (SSOT)",
    description="GET /incidents/{incident_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.vault_all_in_one.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="vault_all_in_one",
    group_name="vault_all_in_one_incident_timeline",
    title="Vault_All_In_One Get Incident Timeline (GET) (SSOT)",
    description="GET /incidents/{incident_id}/timeline",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.vault_all_in_one.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="vault_all_in_one",
    group_name="vault_all_in_one_search_by_metadata",
    title="Vault_All_In_One Search By Metadata (GET) (SSOT)",
    description="GET /search/metadata",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.vault_all_in_one.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="vault_all_in_one",
    group_name="vault_all_in_one_search_by_location",
    title="Vault_All_In_One Search By Location (GET) (SSOT)",
    description="GET /search/location",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.vault_all_in_one.router",),
    deterministic=True,
))
