"""Workflow_Validator module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="workflow_validator",
    group_name="workflow_validator_validator_dashboard",
    title="Workflow_Validator Validator Dashboard (GET) (SSOT)",
    description="GET /",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.workflow_validator.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="workflow_validator",
    group_name="workflow_validator_test_routing",
    title="Workflow_Validator Test Routing (GET) (SSOT)",
    description="API endpoint to test specific routing scenarios.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.workflow_validator.router",),
    deterministic=True,
))
