"""Vault_Engine module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(
    FunctionGroupContract(
        module="vault_engine",
        group_name="vault_engine_check_access",
        title="Vault_Engine Check Access (POST) (SSOT)",
        description="POST /check-access",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.vault_engine.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="vault_engine",
        group_name="vault_engine_read_resource",
        title="Vault_Engine Read Resource (POST) (SSOT)",
        description="POST /read",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.vault_engine.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="vault_engine",
        group_name="vault_engine_write_resource",
        title="Vault_Engine Write Resource (POST) (SSOT)",
        description="POST /write",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.vault_engine.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="vault_engine",
        group_name="vault_engine_resource",
        title="Vault_Engine Delete Resource (POST) (SSOT)",
        description="POST /delete",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.vault_engine.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="vault_engine",
        group_name="vault_engine_share_resource",
        title="Vault_Engine Share Resource (POST) (SSOT)",
        description="POST /share",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.vault_engine.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="vault_engine",
        group_name="vault_engine_unshare_resource",
        title="Vault_Engine Unshare Resource (POST) (SSOT)",
        description="POST /unshare",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.vault_engine.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="vault_engine",
        group_name="vault_engine_resources",
        title="Vault_Engine List Resources (GET) (SSOT)",
        description="GET /list",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.vault_engine.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="vault_engine",
        group_name="vault_engine_audit_log",
        title="Vault_Engine Get Audit Log (GET) (SSOT)",
        description="GET /audit",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.vault_engine.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="vault_engine",
        group_name="vault_engine_stats",
        title="Vault_Engine Get Stats (GET) (SSOT)",
        description="GET /stats",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.vault_engine.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="vault_engine",
        group_name="vault_engine_resource_types",
        title="Vault_Engine List Resource Types (GET) (SSOT)",
        description="List all valid resource types.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.vault_engine.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="vault_engine",
        group_name="vault_engine_access_levels",
        title="Vault_Engine List Access Levels (GET) (SSOT)",
        description="List all valid access levels.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.vault_engine.router",),
        deterministic=True,
    )
)
