"""Legal_Filing module registration helper — FunctionGroupContracts.

Auto-generated by _fix_dups.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(
    FunctionGroupContract(
        module="legal_filing",
        group_name="legal_filing_cases",
        title="Legal_Filing Get Cases (GET) (SSOT)",
        description="GET /cases",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.legal_filing.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="legal_filing",
        group_name="legal_filing_get_case",
        title="Legal_Filing Get Case (GET) (SSOT)",
        description="GET /cases/{case_id}",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.legal_filing.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="legal_filing",
        group_name="legal_filing_create_case",
        title="Legal_Filing Create Case (POST) (SSOT)",
        description="POST /cases",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.legal_filing.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="legal_filing",
        group_name="legal_filing_add_evidence",
        title="Legal_Filing Add Evidence (POST) (SSOT)",
        description="POST /cases/{case_id}/evidence",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.legal_filing.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="legal_filing",
        group_name="legal_filing_evidence",
        title="Legal_Filing Get Evidence (GET) (SSOT)",
        description="GET /cases/{case_id}/evidence",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.legal_filing.router",),
        deterministic=True,
    )
)
