"""Data_Freshness module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="data_freshness",
    group_name="data_freshness_freshness_status",
    title="Data_Freshness Get Freshness Status (GET) (SSOT)",
    description="Get overall freshness status of all data types.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.data_freshness.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="data_freshness",
    group_name="data_freshness_freshness_report",
    title="Data_Freshness Get Freshness Report (GET) (SSOT)",
    description="Get comprehensive freshness report.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.data_freshness.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="data_freshness",
    group_name="data_freshness_refresh_data",
    title="Data_Freshness Refresh Data (POST) (SSOT)",
    description="Manually trigger refresh for specific data type.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.data_freshness.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="data_freshness",
    group_name="data_freshness_refresh_stale_data",
    title="Data_Freshness Refresh Stale Data (POST) (SSOT)",
    description="Refresh all stale data up to specified priority.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.data_freshness.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="data_freshness",
    group_name="data_freshness_freshness_alerts",
    title="Data_Freshness Get Freshness Alerts (GET) (SSOT)",
    description="Get freshness alerts.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.data_freshness.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="data_freshness",
    group_name="data_freshness_acknowledge_alert",
    title="Data_Freshness Acknowledge Alert (POST) (SSOT)",
    description="Acknowledge a freshness alert.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.data_freshness.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="data_freshness",
    group_name="data_freshness_freshness_rules",
    title="Data_Freshness Get Freshness Rules (GET) (SSOT)",
    description="Get all freshness rules.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.data_freshness.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="data_freshness",
    group_name="data_freshness_daily_refresh_cron",
    title="Data_Freshness Daily Refresh Cron (POST) (SSOT)",
    description="Daily cron job for data freshness (Render compatible).",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.data_freshness.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="data_freshness",
    group_name="data_freshness_hourly_deadlines_cron",
    title="Data_Freshness Hourly Deadlines Cron (POST) (SSOT)",
    description="Hourly cron job for deadline updates (Render compatible).",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.data_freshness.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="data_freshness",
    group_name="data_freshness_health_check",
    title="Data_Freshness Health Check (GET) (SSOT)",
    description="Health check for data freshness system.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.data_freshness.router",),
    deterministic=True,
))
