"""Unified_Overlays module registration helper — FunctionGroupContracts.

Auto-generated by _fix_dups.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(
    FunctionGroupContract(
        module="unified_overlays",
        group_name="unified_overlays_health_check",
        title="Unified_Overlays Health Check (GET) (SSOT)",
        description="Health check endpoint.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.unified_overlays.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="unified_overlays",
        group_name="unified_overlays_create_overlay",
        title="Unified_Overlays Create Overlay (POST) (SSOT)",
        description="POST /create",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.unified_overlays.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="unified_overlays",
        group_name="unified_overlays_overlays",
        title="Unified_Overlays List Overlays (GET) (SSOT)",
        description="GET /list",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.unified_overlays.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="unified_overlays",
        group_name="unified_overlays_get_overlay",
        title="Unified_Overlays Get Overlay (GET) (SSOT)",
        description="GET /{overlay_id}",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.unified_overlays.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="unified_overlays",
        group_name="unified_overlays_patch_overlay",
        title="Unified_Overlays Update Overlay (PATCH) (SSOT)",
        description="PATCH /{overlay_id}",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.unified_overlays.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="unified_overlays",
        group_name="unified_overlays_delete_overlay",
        title="Unified_Overlays Delete Overlay (DELETE) (SSOT)",
        description="DELETE /{overlay_id}",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.unified_overlays.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="unified_overlays",
        group_name="unified_overlays_compose_document_view",
        title="Unified_Overlays Compose Document View (POST) (SSOT)",
        description="POST /compose-view",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.unified_overlays.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="unified_overlays",
        group_name="unified_overlays_add_highlight",
        title="Unified_Overlays Add Highlight (POST) (SSOT)",
        description="POST /annotations/highlight",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.unified_overlays.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="unified_overlays",
        group_name="unified_overlays_add_note",
        title="Unified_Overlays Add Note (POST) (SSOT)",
        description="POST /annotations/note",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.unified_overlays.router",),
        deterministic=False,
    )
)
