"""Fems module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group


register_function_group(FunctionGroupContract(
    module="fems",
    group_name="fems_health",
    title="Fems Fems Health (GET) (SSOT)",
    description="GET /health",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.fems.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="fems",
    group_name="fems_stats",
    title="Fems Fems Stats (GET) (SSOT)",
    description="GET /stats",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.fems.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="fems",
    group_name="fems_upload_file",
    title="Fems Upload File (POST) (SSOT)",
    description="POST /upload",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.fems.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="fems",
    group_name="fems_search",
    title="Fems Search (GET) (SSOT)",
    description="GET /search",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.fems.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="fems",
    group_name="fems_documents",
    title="Fems List Documents (GET) (SSOT)",
    description="GET /documents",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.fems.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="fems",
    group_name="fems_document",
    title="Fems Get Document (GET) (SSOT)",
    description="GET /documents/{doc_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.fems.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="fems",
    group_name="fems_phones",
    title="Fems List Phones (GET) (SSOT)",
    description="GET /phones",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.fems.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="fems",
    group_name="fems_quarantine",
    title="Fems List Quarantine (GET) (SSOT)",
    description="GET /quarantine",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.fems.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="fems",
    group_name="fems_cases",
    title="Fems List Cases (GET) (SSOT)",
    description="GET /cases",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.fems.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="fems",
    group_name="fems_case",
    title="Fems Create Case (POST) (SSOT)",
    description="POST /cases",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.fems.router",),
    deterministic=False,
))
