"""Filedored module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group


register_function_group(FunctionGroupContract(
    module="filedored",
    group_name="filedored_process_documents",
    title="Filedored Process Documents (POST) (SSOT)",
    description="POST /process",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.filedored.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="filedored",
    group_name="filedored_check_folders",
    title="Filedored Check Folders (POST) (SSOT)",
    description="POST /folders/status",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.filedored.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="filedored",
    group_name="filedored_browse_folder",
    title="Filedored Browse Folder (GET) (SSOT)",
    description="GET /browse/{folder:path}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.filedored.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="filedored",
    group_name="filedored_folders",
    title="Filedored List Folders (GET) (SSOT)",
    description="GET /folders",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.filedored.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="filedored",
    group_name="filedored_health_check",
    title="Filedored Health Check (GET) (SSOT)",
    description="Health check for filedored module.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.filedored.router",),
    deterministic=True,
))
