"""Funding_Mgmt module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(
    FunctionGroupContract(
        module="funding_mgmt",
        group_name="funding_mgmt_funding_dashboard",
        title="Funding_Mgmt Funding Dashboard (GET) (SSOT)",
        description="Main funding management dashboard.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.funding_mgmt.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="funding_mgmt",
        group_name="funding_mgmt_funding_prospectus",
        title="Funding_Mgmt Funding Prospectus (GET) (SSOT)",
        description="Display the ID System Funding Prospectus.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.funding_mgmt.router",),
        deterministic=True,
    )
)
