"""Enterprise_Dashboard module registration helper — FunctionGroupContracts.

Auto-generated by _fix_dups.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group


register_function_group(FunctionGroupContract(
    module="enterprise_dashboard",
    group_name="enterprise_dashboard_dashboard_stats",
    title="Enterprise_Dashboard Get Dashboard Stats (GET) (SSOT)",
    description="Get comprehensive dashboard statistics.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.enterprise_dashboard.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="enterprise_dashboard",
    group_name="enterprise_dashboard_recent_activity",
    title="Enterprise_Dashboard Get Recent Activity (GET) (SSOT)",
    description="Get recent activity timeline.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.enterprise_dashboard.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="enterprise_dashboard",
    group_name="enterprise_dashboard_case_progress",
    title="Enterprise_Dashboard Get Case Progress (GET) (SSOT)",
    description="Get case preparation progress metrics.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.enterprise_dashboard.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="enterprise_dashboard",
    group_name="enterprise_dashboard_recent_documents",
    title="Enterprise_Dashboard Get Recent Documents (GET) (SSOT)",
    description="Get recently uploaded/modified documents.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.enterprise_dashboard.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="enterprise_dashboard",
    group_name="enterprise_dashboard_quick_actions",
    title="Enterprise_Dashboard Get Quick Actions (GET) (SSOT)",
    description="Get personalized quick actions based on case status.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.enterprise_dashboard.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="enterprise_dashboard",
    group_name="enterprise_dashboard_ai_insights",
    title="Enterprise_Dashboard Get Ai Insights (GET) (SSOT)",
    description="Get AI-powered insights and recommendations.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.enterprise_dashboard.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="enterprise_dashboard",
    group_name="enterprise_dashboard_analytics",
    title="Enterprise_Dashboard Get Analytics (GET) (SSOT)",
    description="Get detailed analytics for charts and visualizations.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.enterprise_dashboard.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="enterprise_dashboard",
    group_name="enterprise_dashboard_notifications",
    title="Enterprise_Dashboard Get Notifications (GET) (SSOT)",
    description="Get user notifications.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.enterprise_dashboard.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="enterprise_dashboard",
    group_name="enterprise_dashboard_mark_notification_read",
    title="Enterprise_Dashboard Mark Notification Read (POST) (SSOT)",
    description="Mark a notification as read.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.enterprise_dashboard.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="enterprise_dashboard",
    group_name="enterprise_dashboard_global_search",
    title="Enterprise_Dashboard Global Search (GET) (SSOT)",
    description="Global search across all resources.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.enterprise_dashboard.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="enterprise_dashboard",
    group_name="enterprise_dashboard_export_dashboard_report",
    title="Enterprise_Dashboard Export Dashboard Report (GET) (SSOT)",
    description="Export comprehensive dashboard report.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.enterprise_dashboard.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="enterprise_dashboard",
    group_name="enterprise_dashboard_get_dashboard_preferences",
    title="Enterprise_Dashboard Get Dashboard Preferences (GET) (SSOT)",
    description="Get user's dashboard preferences.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.enterprise_dashboard.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="enterprise_dashboard",
    group_name="enterprise_dashboard_update_dashboard_preferences",
    title="Enterprise_Dashboard Update Dashboard Preferences (PUT) (SSOT)",
    description="Update user's dashboard preferences.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.enterprise_dashboard.router",),
    deterministic=False,
))
