"""Inventory module registration helper — FunctionGroupContracts.

Auto-generated by _fix_dups.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="inventory",
    group_name="inventory_backup",
    title="Inventory Create Backup (POST) (SSOT)",
    description="POST /backup",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.inventory.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="inventory",
    group_name="inventory_snapshot",
    title="Inventory Create Snapshot (POST) (SSOT)",
    description="POST /snapshot",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.inventory.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="inventory",
    group_name="inventory_inventory_items",
    title="Inventory Get Inventory Items (GET) (SSOT)",
    description="Get inventory items with optional filters.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.inventory.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="inventory",
    group_name="inventory_get_inventory_item",
    title="Inventory Get Inventory Item (GET) (SSOT)",
    description="Get specific inventory item.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.inventory.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="inventory",
    group_name="inventory_inventory_summary",
    title="Inventory Get Inventory Summary (GET) (SSOT)",
    description="Get inventory summary.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.inventory.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="inventory",
    group_name="inventory_rotate_inventory",
    title="Inventory Rotate Inventory (POST) (SSOT)",
    description="Manually trigger inventory rotation.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.inventory.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="inventory",
    group_name="inventory_delete_inventory_item",
    title="Inventory Delete Inventory Item (DELETE) (SSOT)",
    description="Delete an inventory item.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.inventory.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="inventory",
    group_name="inventory_health",
    title="Inventory Inventory Health (GET) (SSOT)",
    description="Health check for inventory system.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.inventory.router",),
    deterministic=True,
))
