"""Briefcase module registration helper — FunctionGroupContracts.

Auto-generated by _fix_dups.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_briefcase",
    title="Briefcase Get Briefcase (GET) (SSOT)",
    description="Get entire briefcase structure",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_folder_contents",
    title="Briefcase Get Folder Contents (GET) (SSOT)",
    description="Get contents of a specific folder",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_create_folder",
    title="Briefcase Create Folder (POST) (SSOT)",
    description="Create a new folder",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_update_folder",
    title="Briefcase Update Folder (PUT) (SSOT)",
    description="Update folder properties",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_delete_folder",
    title="Briefcase Delete Folder (DELETE) (SSOT)",
    description="Delete a folder",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_upload_document",
    title="Briefcase Upload Document (POST) (SSOT)",
    description="POST /document",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_get_document",
    title="Briefcase Get Document (GET) (SSOT)",
    description="Get document metadata",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_download_document",
    title="Briefcase Download Document (GET) (SSOT)",
    description="Download a document.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_preview_document",
    title="Briefcase Preview Document (GET) (SSOT)",
    description="Get document content for preview (base64)",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_update_document",
    title="Briefcase Update Document (PUT) (SSOT)",
    description="Update document properties",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_delete_document",
    title="Briefcase Delete Document (DELETE) (SSOT)",
    description="Delete a document",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_move_document",
    title="Briefcase Move Document (POST) (SSOT)",
    description="POST /document/{doc_id}/move",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_copy_document",
    title="Briefcase Copy Document (POST) (SSOT)",
    description="POST /document/{doc_id}/copy",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_search_documents",
    title="Briefcase Search Documents (GET) (SSOT)",
    description="Search documents",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_starred_documents",
    title="Briefcase Get Starred Documents (GET) (SSOT)",
    description="Get all starred documents",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_recent_documents",
    title="Briefcase Get Recent Documents (GET) (SSOT)",
    description="Get recently added/updated documents",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_all_tags",
    title="Briefcase Get All Tags (GET) (SSOT)",
    description="Get all available tags",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_add_tag",
    title="Briefcase Add Tag (POST) (SSOT)",
    description="POST /tags",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_export_folder",
    title="Briefcase Export Folder (POST) (SSOT)",
    description="POST /export",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_save_converted_document",
    title="Briefcase Save Converted Document (POST) (SSOT)",
    description="Save a converted document to the briefcase.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_briefcase_stats",
    title="Briefcase Get Briefcase Stats (GET) (SSOT)",
    description="Get detailed briefcase statistics",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_save_extraction",
    title="Briefcase Save Extraction (POST) (SSOT)",
    description="POST /extraction",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_extractions",
    title="Briefcase List Extractions (GET) (SSOT)",
    description="List all saved extractions.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_get_extraction",
    title="Briefcase Get Extraction (GET) (SSOT)",
    description="Get a specific extraction.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_delete_extraction",
    title="Briefcase Delete Extraction (DELETE) (SSOT)",
    description="Delete an extraction.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_download_extraction",
    title="Briefcase Download Extraction (GET) (SSOT)",
    description="Download extracted PDF file.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_save_highlight",
    title="Briefcase Save Highlight (POST) (SSOT)",
    description="POST /highlight",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_save_highlights_batch",
    title="Briefcase Save Highlights Batch (POST) (SSOT)",
    description="Save multiple highlights at once.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_highlights",
    title="Briefcase List Highlights (GET) (SSOT)",
    description="List all saved highlights, optionally filtered.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_get_highlight",
    title="Briefcase Get Highlight (GET) (SSOT)",
    description="Get a specific highlight.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_delete_highlight",
    title="Briefcase Delete Highlight (DELETE) (SSOT)",
    description="Delete a highlight.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_highlights_grouped_by_color",
    title="Briefcase Get Highlights Grouped By Color (GET) (SSOT)",
    description="Get highlights grouped by color category.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_create_annotation",
    title="Briefcase Create Annotation (POST) (SSOT)",
    description="Create a new document annotation with auto-numbered footnotes.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_annotations",
    title="Briefcase List Annotations (GET) (SSOT)",
    description="List annotations with optional filters.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_get_annotation",
    title="Briefcase Get Annotation (GET) (SSOT)",
    description="Get a specific annotation.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_update_annotation",
    title="Briefcase Update Annotation (PUT) (SSOT)",
    description="Update an annotation's note or linked event.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_delete_annotation",
    title="Briefcase Delete Annotation (DELETE) (SSOT)",
    description="Delete an annotation.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_link_annotation_to_event",
    title="Briefcase Link Annotation To Event (POST) (SSOT)",
    description="POST /annotation/{annotation_id}/link-event",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_annotations_by_document",
    title="Briefcase Get Annotations By Document (GET) (SSOT)",
    description="Get all annotations for a document, grouped by extraction code.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_reset_annotation_counters",
    title="Briefcase Reset Annotation Counters (POST) (SSOT)",
    description="POST /annotations/reset-counters",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_create_timeline_event",
    title="Briefcase Create Timeline Event (POST) (SSOT)",
    description="Create a timeline event that can be linked to annotations.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_timeline_events",
    title="Briefcase List Timeline Events (GET) (SSOT)",
    description="List timeline events with optional filters.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_get_timeline_event",
    title="Briefcase Get Timeline Event (GET) (SSOT)",
    description="Get a timeline event with its linked annotations.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_update_timeline_event",
    title="Briefcase Update Timeline Event (PUT) (SSOT)",
    description="Update a timeline event.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_delete_timeline_event",
    title="Briefcase Delete Timeline Event (DELETE) (SSOT)",
    description="Delete a timeline event and unlink associated annotations.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_event_chain",
    title="Briefcase Get Event Chain (GET) (SSOT)",
    description="Get an event chain (linked events: start▸continued▸finish).",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_event_from_annotation",
    title="Briefcase Create Event From Annotation (POST) (SSOT)",
    description="Create a timeline event from an annotation's highlight.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_extraction_codes",
    title="Briefcase Get Extraction Codes (GET) (SSOT)",
    description="Get the complete list of extraction codes with colors and icons.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="briefcase",
    group_name="briefcase_event_statuses",
    title="Briefcase Get Event Statuses (GET) (SSOT)",
    description="Get the complete list of event statuses with descriptions.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.briefcase.router",),
    deterministic=True,
))
