"""Cloud_Sync module registration helper — FunctionGroupContracts.

Auto-generated by _fix_dups.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="cloud_sync",
    group_name="cloud_sync_sync_status",
    title="Cloud_Sync Get Sync Status (GET) (SSOT)",
    description="GET /status",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.cloud_sync.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="cloud_sync",
    group_name="cloud_sync_full_sync",
    title="Cloud_Sync Full Sync (POST) (SSOT)",
    description="POST /full",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.cloud_sync.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="cloud_sync",
    group_name="cloud_sync_get_profile",
    title="Cloud_Sync Get Profile (GET) (SSOT)",
    description="GET /profile",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.cloud_sync.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="cloud_sync",
    group_name="cloud_sync_update_profile",
    title="Cloud_Sync Update Profile (PUT) (SSOT)",
    description="PUT /profile",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.cloud_sync.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="cloud_sync",
    group_name="cloud_sync_get_case",
    title="Cloud_Sync Get Case (GET) (SSOT)",
    description="GET /case",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.cloud_sync.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="cloud_sync",
    group_name="cloud_sync_update_case",
    title="Cloud_Sync Update Case (PUT) (SSOT)",
    description="PUT /case",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.cloud_sync.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="cloud_sync",
    group_name="cloud_sync_timeline",
    title="Cloud_Sync Get Timeline (GET) (SSOT)",
    description="GET /timeline",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.cloud_sync.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="cloud_sync",
    group_name="cloud_sync_add_timeline_event",
    title="Cloud_Sync Add Timeline Event (POST) (SSOT)",
    description="POST /timeline",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.cloud_sync.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="cloud_sync",
    group_name="cloud_sync_calendar",
    title="Cloud_Sync Get Calendar (GET) (SSOT)",
    description="GET /calendar",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.cloud_sync.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="cloud_sync",
    group_name="cloud_sync_add_calendar_event",
    title="Cloud_Sync Add Calendar Event (POST) (SSOT)",
    description="POST /calendar",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.cloud_sync.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="cloud_sync",
    group_name="cloud_sync_export_all_data",
    title="Cloud_Sync Export All Data (GET) (SSOT)",
    description="GET /export",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.cloud_sync.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="cloud_sync",
    group_name="cloud_sync_import_all_data",
    title="Cloud_Sync Import All Data (POST) (SSOT)",
    description="POST /import",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.cloud_sync.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="cloud_sync",
    group_name="cloud_sync_documents",
    title="Cloud_Sync Get Documents (GET) (SSOT)",
    description="GET /documents",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.cloud_sync.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="cloud_sync",
    group_name="cloud_sync_vault_index",
    title="Cloud_Sync Get Vault Index (GET) (SSOT)",
    description="GET /vault/index",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.cloud_sync.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="cloud_sync",
    group_name="cloud_sync_get_vault_document",
    title="Cloud_Sync Get Vault Document (GET) (SSOT)",
    description="GET /vault/document/{document_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.cloud_sync.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="cloud_sync",
    group_name="cloud_sync_vault_document_content",
    title="Cloud_Sync Get Vault Document Content (GET) (SSOT)",
    description="GET /vault/document/{document_id}/content",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.cloud_sync.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="cloud_sync",
    group_name="cloud_sync_patch_vault_document",
    title="Cloud_Sync Update Vault Document (PATCH) (SSOT)",
    description="PATCH /vault/document/{document_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.cloud_sync.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="cloud_sync",
    group_name="cloud_sync_upload_document_to_cloud",
    title="Cloud_Sync Upload Document To Cloud (POST) (SSOT)",
    description="POST /documents/upload",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.cloud_sync.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="cloud_sync",
    group_name="cloud_sync_check_storage_connection",
    title="Cloud_Sync Check Storage Connection (GET) (SSOT)",
    description="GET /check",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.cloud_sync.router",),
    deterministic=True,
))
