"""Funding_Search module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="funding_search",
    group_name="funding_search_funding_programs",
    title="Funding_Search List Funding Programs (GET) (SSOT)",
    description="List all available funding programs with details",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.funding_search.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="funding_search",
    group_name="funding_search_program_details",
    title="Funding_Search Get Program Details (GET) (SSOT)",
    description="Get detailed information about a specific funding program",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.funding_search.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="funding_search",
    group_name="funding_search_search_funding_records",
    title="Funding_Search Search Funding Records (POST) (SSOT)",
    description="POST /search",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.funding_search.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="funding_search",
    group_name="funding_search_search_by_address",
    title="Funding_Search Search By Address (GET) (SSOT)",
    description="GET /search/address",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.funding_search.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="funding_search",
    group_name="funding_search_search_by_company",
    title="Funding_Search Search By Company (GET) (SSOT)",
    description="GET /search/company",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.funding_search.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="funding_search",
    group_name="funding_search_search_by_broker",
    title="Funding_Search Search By Broker (GET) (SSOT)",
    description="GET /search/broker",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.funding_search.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="funding_search",
    group_name="funding_search_funding_record",
    title="Funding_Search Get Funding Record (GET) (SSOT)",
    description="GET /record/{record_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.funding_search.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="funding_search",
    group_name="funding_search_funding_statistics",
    title="Funding_Search Get Funding Statistics (GET) (SSOT)",
    description="GET /statistics",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.funding_search.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="funding_search",
    group_name="funding_search_check_eligibility",
    title="Funding_Search Check Eligibility (GET) (SSOT)",
    description="GET /eligibility-check",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.funding_search.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="funding_search",
    group_name="funding_search_data_sources",
    title="Funding_Search List Data Sources (GET) (SSOT)",
    description="List authoritative data sources for funding research",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.funding_search.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="funding_search",
    group_name="funding_search_health",
    title="Funding_Search Funding Search Health (GET) (SSOT)",
    description="Health check for funding search service",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.funding_search.router",),
    deterministic=True,
))
