"""Components module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(
    FunctionGroupContract(
        module="components",
        group_name="components_handle_capture_upload",
        title="Components Handle Capture Upload (POST) (SSOT)",
        description="POST /capture/upload",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.components.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="components",
        group_name="components_handle_capture_input",
        title="Components Handle Capture Input (POST) (SSOT)",
        description="POST /capture/input",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.components.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="components",
        group_name="components_handle_capture_voice",
        title="Components Handle Capture Voice (POST) (SSOT)",
        description="POST /capture/voice",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.components.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="components",
        group_name="components_handle_understand_timeline",
        title="Components Handle Understand Timeline (POST) (SSOT)",
        description="POST /understand/timeline",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.components.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="components",
        group_name="components_handle_understand_rights",
        title="Components Handle Understand Rights (POST) (SSOT)",
        description="POST /understand/rights",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.components.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="components",
        group_name="components_handle_understand_risk",
        title="Components Handle Understand Risk (POST) (SSOT)",
        description="POST /understand/risk",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.components.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="components",
        group_name="components_handle_plan_action",
        title="Components Handle Plan Action (POST) (SSOT)",
        description="POST /plan/action",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.components.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="components",
        group_name="components_handle_plan_deadline",
        title="Components Handle Plan Deadline (POST) (SSOT)",
        description="POST /plan/deadline",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.components.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="components",
        group_name="components_handle_tenant_emergency",
        title="Components Handle Tenant Emergency (POST) (SSOT)",
        description="POST /tenant/emergency-action",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.components.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="components",
        group_name="components_handle_advocate_handoff",
        title="Components Handle Advocate Handoff (POST) (SSOT)",
        description="POST /advocate/handoff-client",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.components.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="components",
        group_name="components_handle_legal_review",
        title="Components Handle Legal Review (POST) (SSOT)",
        description="POST /legal/start-review",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.components.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="components",
        group_name="components_handle_admin_maintenance",
        title="Components Handle Admin Maintenance (POST) (SSOT)",
        description="POST /admin/system-maintenance",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.components.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="components",
        group_name="components_workspace_stage",
        title="Components Get Workspace Stage (GET) (SSOT)",
        description="GET /workspace-stage",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.components.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="components",
        group_name="components_next_step",
        title="Components Get Next Step (GET) (SSOT)",
        description="GET /next-step",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.components.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="components",
        group_name="components_component_config",
        title="Components Get Component Config (GET) (SSOT)",
        description="GET /config/{role}",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.components.router",),
        deterministic=True,
    )
)
