"""Batch module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group


register_function_group(FunctionGroupContract(
    module="batch",
    group_name="batch_batch_operation_endpoint",
    title="Batch Create Batch Operation Endpoint (POST) (SSOT)",
    description="POST /create",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.batch.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="batch",
    group_name="batch_start_batch_operation_endpoint",
    title="Batch Start Batch Operation Endpoint (POST) (SSOT)",
    description="POST /{operation_id}/start",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.batch.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="batch",
    group_name="batch_cancel_batch_operation_endpoint",
    title="Batch Cancel Batch Operation Endpoint (POST) (SSOT)",
    description="POST /{operation_id}/cancel",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.batch.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="batch",
    group_name="batch_batch_operation_endpoint",
    title="Batch Get Batch Operation Endpoint (GET) (SSOT)",
    description="GET /{operation_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.batch.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="batch",
    group_name="batch_user_batch_operations_endpoint",
    title="Batch Get User Batch Operations Endpoint (GET) (SSOT)",
    description="GET /",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.batch.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="batch",
    group_name="batch_batch_statistics_endpoint",
    title="Batch Get Batch Statistics Endpoint (GET) (SSOT)",
    description="GET /statistics",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.batch.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="batch",
    group_name="batch_prepare_batch_upload",
    title="Batch Prepare Batch Upload (POST) (SSOT)",
    description="POST /upload/prepare",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.batch.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="batch",
    group_name="batch_execute_batch_upload",
    title="Batch Execute Batch Upload (POST) (SSOT)",
    description="POST /upload/execute/{operation_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.batch.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="batch",
    group_name="batch_prepare_batch_delete",
    title="Batch Prepare Batch Delete (POST) (SSOT)",
    description="POST /delete/prepare",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.batch.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="batch",
    group_name="batch_prepare_batch_export",
    title="Batch Prepare Batch Export (POST) (SSOT)",
    description="POST /export/prepare",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.batch.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="batch",
    group_name="batch_supported_operations",
    title="Batch Get Supported Operations (GET) (SSOT)",
    description="Get list of supported batch operations.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.batch.router",),
    deterministic=True,
))
