"""Actions module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="actions",
    group_name="actions_action_plan",
    title="Actions Get Action Plan (GET) (SSOT)",
    description="GET /plan",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.actions.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="actions",
    group_name="actions_action_plan_with_context",
    title="Actions Get Action Plan With Context (POST) (SSOT)",
    description="POST /plan",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.actions.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="actions",
    group_name="actions_quick_wins",
    title="Actions Get Quick Wins (GET) (SSOT)",
    description="Get a list of quick win actions - low time, low effort, immediate benefit.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.actions.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="actions",
    group_name="actions_actions_by_category",
    title="Actions Get Actions By Category (GET) (SSOT)",
    description="Get all actions in a specific category.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.actions.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="actions",
    group_name="actions_all_actions",
    title="Actions Get All Actions (GET) (SSOT)",
    description="Get all available actions in the system.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.actions.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="actions",
    group_name="actions_current_capacity",
    title="Actions Get Current Capacity (GET) (SSOT)",
    description="GET /capacity",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.actions.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="actions",
    group_name="actions_self_care_suggestions",
    title="Actions Get Self Care Suggestions (GET) (SSOT)",
    description="Get self-care action suggestions.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.actions.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="actions",
    group_name="actions_encouragement",
    title="Actions Get Encouragement (GET) (SSOT)",
    description="GET /encouragement",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.actions.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="actions",
    group_name="actions_next_action",
    title="Actions Get Next Action (GET) (SSOT)",
    description="Get just the single most important next action.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.actions.router",),
    deterministic=True,
))
