"""Page_Index module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group


register_function_group(FunctionGroupContract(
    module="page_index",
    group_name="page_index_scan_html_pages",
    title="Page_Index Scan Html Pages (GET) (SSOT)",
    description="GET /scan",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.page_index.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="page_index",
    group_name="page_index_scan_fastapi_pages",
    title="Page_Index Scan Fastapi Pages (GET) (SSOT)",
    description="Scan only the Semptify-FastAPI static folder for HTML pages.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.page_index.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="page_index",
    group_name="page_index_page_stats",
    title="Page_Index Get Page Stats (GET) (SSOT)",
    description="GET /stats",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.page_index.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="page_index",
    group_name="page_index_search_pages",
    title="Page_Index Search Pages (GET) (SSOT)",
    description="GET /search",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.page_index.router",),
    deterministic=True,
))
