"""Fraud_Exposure module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group


register_function_group(FunctionGroupContract(
    module="fraud_exposure",
    group_name="fraud_exposure_fraud_health_check",
    title="Fraud_Exposure Fraud Health Check (GET) (SSOT)",
    description="Health check for fraud exposure service",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.fraud_exposure.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="fraud_exposure",
    group_name="fraud_exposure_analyze_fraud",
    title="Fraud_Exposure Analyze Fraud (POST) (SSOT)",
    description="POST /analyze",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.fraud_exposure.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="fraud_exposure",
    group_name="fraud_exposure_fraud_report",
    title="Fraud_Exposure Get Fraud Report (GET) (SSOT)",
    description="GET /report/{report_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.fraud_exposure.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="fraud_exposure",
    group_name="fraud_exposure_check_fraud_pattern",
    title="Fraud_Exposure Check Fraud Pattern (POST) (SSOT)",
    description="POST /check-pattern",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.fraud_exposure.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="fraud_exposure",
    group_name="fraud_exposure_statute_of_limitations",
    title="Fraud_Exposure Get Statute Of Limitations (GET) (SSOT)",
    description="GET /statute-of-limitations",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.fraud_exposure.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="fraud_exposure",
    group_name="fraud_exposure_whistleblower_info",
    title="Fraud_Exposure Get Whistleblower Info (GET) (SSOT)",
    description="GET /whistleblower-info",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.fraud_exposure.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="fraud_exposure",
    group_name="fraud_exposure_fraud_patterns",
    title="Fraud_Exposure List Fraud Patterns (GET) (SSOT)",
    description="GET /patterns",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.fraud_exposure.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="fraud_exposure",
    group_name="fraud_exposure_reporting_agencies",
    title="Fraud_Exposure List Reporting Agencies (GET) (SSOT)",
    description="GET /agencies",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.fraud_exposure.router",),
    deterministic=True,
))
