"""Risc module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group


register_function_group(FunctionGroupContract(
    module="risc",
    group_name="risc_webhook",
    title="Risc Risc Webhook (POST) (SSOT)",
    description="Receive Google Cross-Account Protection Security Event Tokens.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.risc.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="risc",
    group_name="risc_webhook_verify",
    title="Risc Risc Webhook Verify (GET) (SSOT)",
    description="Google verification GET request — returns 200 to confirm endpoint ownership.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.risc.router",),
    deterministic=True,
))
