"""Context_Loop module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="context_loop",
    group_name="context_loop_state",
    title="Context_Loop Get State (GET) (SSOT)",
    description="GET /state",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.context_loop.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="context_loop",
    group_name="context_loop_intensity",
    title="Context_Loop Get Intensity (GET) (SSOT)",
    description="GET /intensity",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.context_loop.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="context_loop",
    group_name="context_loop_context",
    title="Context_Loop Get Context (GET) (SSOT)",
    description="GET /context",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.context_loop.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="context_loop",
    group_name="context_loop_emit_event",
    title="Context_Loop Emit Event (POST) (SSOT)",
    description="POST /event",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.context_loop.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="context_loop",
    group_name="context_loop_process_document",
    title="Context_Loop Process Document (POST) (SSOT)",
    description="POST /document",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.context_loop.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="context_loop",
    group_name="context_loop_report_issue",
    title="Context_Loop Report Issue (POST) (SSOT)",
    description="POST /issue",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.context_loop.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="context_loop",
    group_name="context_loop_add_deadline",
    title="Context_Loop Add Deadline (POST) (SSOT)",
    description="POST /deadline",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.context_loop.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="context_loop",
    group_name="context_loop_record_action",
    title="Context_Loop Record Action (POST) (SSOT)",
    description="POST /action",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.context_loop.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="context_loop",
    group_name="context_loop_predictions",
    title="Context_Loop Get Predictions (GET) (SSOT)",
    description="GET /predictions",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.context_loop.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="context_loop",
    group_name="context_loop_events",
    title="Context_Loop Get Events (GET) (SSOT)",
    description="GET /events",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.context_loop.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="context_loop",
    group_name="context_loop_loop_health",
    title="Context_Loop Loop Health (GET) (SSOT)",
    description="Check context loop health.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.context_loop.router",),
    deterministic=True,
))
