"""Public_Exposure module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group


register_function_group(FunctionGroupContract(
    module="public_exposure",
    group_name="public_exposure_exposure_health_check",
    title="Public_Exposure Exposure Health Check (GET) (SSOT)",
    description="Health check for public exposure service",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.public_exposure.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="public_exposure",
    group_name="public_exposure_generate_press_release",
    title="Public_Exposure Generate Press Release (POST) (SSOT)",
    description="POST /press-release",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.public_exposure.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="public_exposure",
    group_name="public_exposure_press_release",
    title="Public_Exposure Get Press Release (GET) (SSOT)",
    description="GET /press-release/{release_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.public_exposure.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="public_exposure",
    group_name="public_exposure_press_release_text",
    title="Public_Exposure Get Press Release Text (GET) (SSOT)",
    description="GET /press-release/{release_id}/text",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.public_exposure.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="public_exposure",
    group_name="public_exposure_generate_media_kit",
    title="Public_Exposure Generate Media Kit (POST) (SSOT)",
    description="POST /media-kit",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.public_exposure.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="public_exposure",
    group_name="public_exposure_media_kit",
    title="Public_Exposure Get Media Kit (GET) (SSOT)",
    description="GET /media-kit/{kit_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.public_exposure.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="public_exposure",
    group_name="public_exposure_media_outlets",
    title="Public_Exposure List Media Outlets (GET) (SSOT)",
    description="GET /media-outlets",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.public_exposure.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="public_exposure",
    group_name="public_exposure_supported_languages",
    title="Public_Exposure List Supported Languages (GET) (SSOT)",
    description="GET /languages",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.public_exposure.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="public_exposure",
    group_name="public_exposure_release_types",
    title="Public_Exposure List Release Types (GET) (SSOT)",
    description="GET /release-types",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.public_exposure.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="public_exposure",
    group_name="public_exposure_generate_social_posts",
    title="Public_Exposure Generate Social Posts (POST) (SSOT)",
    description="POST /generate-social-posts",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.public_exposure.router",),
    deterministic=False,
))
