"""Dev_Lab module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group


register_function_group(FunctionGroupContract(
    module="dev_lab",
    group_name="dev_lab_dev_modules",
    title="Dev_Lab List Dev Modules (GET) (SSOT)",
    description="GET",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.dev_lab.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="dev_lab",
    group_name="dev_lab_dev_module",
    title="Dev_Lab Get Dev Module (GET) (SSOT)",
    description="GET /{module_path:path}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.dev_lab.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="dev_lab",
    group_name="dev_lab_module_status",
    title="Dev_Lab Get Module Status (GET) (SSOT)",
    description="GET /{module_path:path}/status",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.dev_lab.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="dev_lab",
    group_name="dev_lab_promote_module",
    title="Dev_Lab Promote Module (POST) (SSOT)",
    description="POST /{module_path:path}/promote",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.dev_lab.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="dev_lab",
    group_name="dev_lab_run_module_tests",
    title="Dev_Lab Run Module Tests (POST) (SSOT)",
    description="POST /{module_path:path}/test",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.dev_lab.router",),
    deterministic=False,
))
