"""Registry module registration helper — FunctionGroupContracts.

Auto-generated by _fix_dups.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_register_document",
    title="Registry Register Document (POST) (SSOT)",
    description="POST /register",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_get_document",
    title="Registry Get Document (GET) (SSOT)",
    description="GET /documents/{doc_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_documents",
    title="Registry List Documents (GET) (SSOT)",
    description="GET /documents",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_delete_document",
    title="Registry Delete Document (DELETE) (SSOT)",
    description="DELETE /documents/{doc_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_clear_all_documents",
    title="Registry Clear All Documents (DELETE) (SSOT)",
    description="DELETE /documents",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_duplicates",
    title="Registry Get Duplicates (GET) (SSOT)",
    description="GET /documents/{doc_id}/duplicates",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_custody_chain",
    title="Registry Get Custody Chain (GET) (SSOT)",
    description="GET /documents/{doc_id}/custody",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_verify_document",
    title="Registry Verify Document (POST) (SSOT)",
    description="POST /documents/{doc_id}/verify",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_integrity_status",
    title="Registry Get Integrity Status (GET) (SSOT)",
    description="Get the current integrity status of a document.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_document_hash",
    title="Registry Get Document Hash (GET) (SSOT)",
    description="Get the stored hashes for a document (for external verification).",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_flag_document",
    title="Registry Flag Document (POST) (SSOT)",
    description="Flag a document for review (suspected forgery, alteration, etc.).",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_associate_case",
    title="Registry Associate Case (POST) (SSOT)",
    description="Associate a document with a case number.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_flagged_documents",
    title="Registry Get Flagged Documents (GET) (SSOT)",
    description="Get all documents flagged for review.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_quarantined_documents",
    title="Registry Get Quarantined Documents (GET) (SSOT)",
    description="Get all quarantined documents (high forgery risk).",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_registry_stats",
    title="Registry Get Registry Stats (GET) (SSOT)",
    description="Get registry statistics.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_document_statuses",
    title="Registry Get Document Statuses (GET) (SSOT)",
    description="Get all document statuses.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_integrity_statuses",
    title="Registry Get Integrity Statuses (GET) (SSOT)",
    description="Get all integrity statuses.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_forgery_indicators",
    title="Registry Get Forgery Indicators (GET) (SSOT)",
    description="Get all forgery indicators.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_custody_actions",
    title="Registry Get Custody Actions (GET) (SSOT)",
    description="Get all custody actions.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_case_documents",
    title="Registry Get Case Documents (GET) (SSOT)",
    description="Get all documents for a specific case.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="registry",
    group_name="registry_cases",
    title="Registry List Cases (GET) (SSOT)",
    description="List all cases with document counts.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.registry.router",),
    deterministic=True,
))
