"""Module_Hub module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group


register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_hub_status",
    title="Module_Hub Get Hub Status (GET) (SSOT)",
    description="Get the status of the module hub",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_modules",
    title="Module_Hub List Modules (GET) (SSOT)",
    description="List all registered modules",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_function_group_contracts",
    title="Module_Hub List Function Group Contracts (GET) (SSOT)",
    description="List all registered standardized function-group contracts.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_function_group_contract_health",
    title="Module_Hub Function Group Contract Health (GET) (SSOT)",
    description="Validate function-group contracts for plug-and-play readiness.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_user_packs",
    title="Module_Hub Get User Packs (GET) (SSOT)",
    description="GET /packs",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_pending_packs",
    title="Module_Hub Get Pending Packs (GET) (SSOT)",
    description="GET /packs/pending",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_pack",
    title="Module_Hub Get Pack (GET) (SSOT)",
    description="GET /packs/{pack_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_complete_pack",
    title="Module_Hub Complete Pack (POST) (SSOT)",
    description="POST /packs/{pack_id}/complete",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_user_data",
    title="Module_Hub Get User Data (GET) (SSOT)",
    description="GET /data",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_make_data_request",
    title="Module_Hub Make Data Request (POST) (SSOT)",
    description="POST /request",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_comm_log",
    title="Module_Hub Get Comm Log (GET) (SSOT)",
    description="GET /log",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_case_info",
    title="Module_Hub Get Case Info (GET) (SSOT)",
    description="GET /case-info",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_lease_data",
    title="Module_Hub Get Lease Data (GET) (SSOT)",
    description="GET /lease-data",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_landlord_info",
    title="Module_Hub Get Landlord Info (GET) (SSOT)",
    description="GET /landlord-info",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_property_info",
    title="Module_Hub Get Property Info (GET) (SSOT)",
    description="GET /property-info",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_deadlines",
    title="Module_Hub Get Deadlines (GET) (SSOT)",
    description="GET /deadlines",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_user_context",
    title="Module_Hub Get User Context (GET) (SSOT)",
    description="GET /context",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_mesh_status",
    title="Module_Hub Get Mesh Status (GET) (SSOT)",
    description="Get current Positronic Mesh status including mode and deferrals.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_set_mesh_mode",
    title="Module_Hub Set Mesh Mode (POST) (SSOT)",
    description="Switch mesh operating mode ('lean' or 'full').",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_deferral_status",
    title="Module_Hub Get Deferral Status (GET) (SSOT)",
    description="Get status of deferred actions queue.",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="module_hub",
    group_name="module_hub_retry_deferred_actions",
    title="Module_Hub Retry Deferred Actions (POST) (SSOT)",
    description="Retry all deferred actions (only works in full mode).",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.module_hub.router",),
    deterministic=False,
))
