"""Functionx module registration helper — FunctionGroupContracts.

Auto-generated by _fix_dups.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="functionx",
    group_name="functionx_health",
    title="Functionx Functionx Health (GET) (SSOT)",
    description="GET /health",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.functionx.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="functionx",
    group_name="functionx_create_action_set",
    title="Functionx Create Action Set (POST) (SSOT)",
    description="POST /sets",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.functionx.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="functionx",
    group_name="functionx_action_sets",
    title="Functionx List Action Sets (GET) (SSOT)",
    description="GET /sets",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.functionx.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="functionx",
    group_name="functionx_get_action_set",
    title="Functionx Get Action Set (GET) (SSOT)",
    description="GET /sets/{set_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.functionx.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="functionx",
    group_name="functionx_execute_action_set",
    title="Functionx Execute Action Set (POST) (SSOT)",
    description="POST /sets/{set_id}/execute",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.functionx.router",),
    deterministic=False,
))
