"""Tools_Api module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="tools_api",
    group_name="tools_api_save_letter",
    title="Tools_Api Save Letter (POST) (SSOT)",
    description="POST /save-letter",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.tools_api.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="tools_api",
    group_name="tools_api_save_checklist",
    title="Tools_Api Save Checklist (POST) (SSOT)",
    description="POST /save-checklist",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.tools_api.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="tools_api",
    group_name="tools_api_save_calculation",
    title="Tools_Api Save Calculation (POST) (SSOT)",
    description="POST /save-calculation",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.tools_api.router",),
    deterministic=False,
))
