"""Brain module registration helper — FunctionGroupContracts.

Auto-generated by _fix_dups.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="brain",
    group_name="brain_brain_status",
    title="Brain Get Brain Status (GET) (SSOT)",
    description="GET /status",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.brain.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="brain",
    group_name="brain_modules",
    title="Brain List Modules (GET) (SSOT)",
    description="GET /modules",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.brain.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="brain",
    group_name="brain_get_state",
    title="Brain Get State (GET) (SSOT)",
    description="GET /state",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.brain.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="brain",
    group_name="brain_update_state",
    title="Brain Update State (PUT) (SSOT)",
    description="PUT /state",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.brain.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="brain",
    group_name="brain_recent_events",
    title="Brain Get Recent Events (GET) (SSOT)",
    description="GET /events",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.brain.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="brain",
    group_name="brain_emit_event",
    title="Brain Emit Event (POST) (SSOT)",
    description="POST /events",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.brain.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="brain",
    group_name="brain_trigger_workflow",
    title="Brain Trigger Workflow (POST) (SSOT)",
    description="POST /workflow",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.brain.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="brain",
    group_name="brain_workflows",
    title="Brain List Workflows (GET) (SSOT)",
    description="GET /workflows",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.brain.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="brain",
    group_name="brain_workflow",
    title="Brain Get Workflow (GET) (SSOT)",
    description="GET /workflows/{workflow_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.brain.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="brain",
    group_name="brain_think",
    title="Brain Brain Think (POST) (SSOT)",
    description="POST /think",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.brain.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="brain",
    group_name="brain_sync_all",
    title="Brain Sync All (POST) (SSOT)",
    description="POST /sync",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.brain.router",),
    deterministic=False,
))
