"""
Invite Code Service
==================

Manages generation, validation, and redemption of invite codes
for Advocate and Legal role validation.

Codes are generated by Managers/Admins and redeemed by users
during the onboarding flow to unlock elevated roles.
"""

import secrets
import string
from datetime import datetime, timedelta
from typing import Optional

from app.core.utc import utc_now
from app.models.models import InviteCode

# Alphabet for readable codes (no ambiguous characters)
CODE_ALPHABET = string.ascii_uppercase + string.digits
CODE_ALPHABET = CODE_ALPHABET.replace('0', '').replace('O', '').replace('1', '').replace('I', '')


def generate_code(length: int = 8) -> str:
    """
    Generate a random, readable invite code.
    
    Args:
        length: Code length (default 8: XXXX-XXXX format)
        
    Returns:
        Random code like "ABCD-1234"
    """
    raw = ''.join(secrets.choice(CODE_ALPHABET) for _ in range(length))
    # Format with hyphen in middle for readability
    if length >= 6:
        mid = length // 2
        return f"{raw[:mid]}-{raw[mid:]}"
    return raw


def create_invite_code(
    created_by: str,
    role: str = "advocate",
    organization_id: Optional[str] = None,
    organization_name: Optional[str] = None,
    max_uses: int = 1,
    expires_days: Optional[int] = None,
    description: Optional[str] = None,
    custom_code: Optional[str] = None,
) -> InviteCode:
    """
    Create a new invite code.
    
    Args:
        created_by: User ID of the manager/admin creating the code
        role: Role to grant (advocate, legal, admin)
        organization_id: Optional org identifier
        organization_name: Optional org name
        max_uses: Maximum number of redemptions (default 1)
        expires_days: Days until expiration (None = never)
        description: Optional note about this code
        custom_code: Optional specific code (otherwise auto-generated)
        
    Returns:
        Created InviteCode object (not yet committed)
    """
    code = custom_code.upper() if custom_code else generate_code()
    
    expires_at = None
    if expires_days:
        expires_at = utc_now() + timedelta(days=expires_days)
    
    return InviteCode(
        code=code,
        created_by=created_by,
        role=role,
        organization_id=organization_id,
        organization_name=organization_name,
        max_uses=max_uses,
        uses_count=0,
        used_by=[],
        expires_at=expires_at,
        is_active=True,
        description=description,
    )


def validate_invite_code(code: str, db_session) -> tuple[bool, str, Optional[InviteCode]]:
    """
    Validate an invite code.
    
    Args:
        code: The invite code to validate
        db_session: SQLAlchemy session
        
    Returns:
        Tuple of (is_valid: bool, message: str, invite_code: InviteCode or None)
    """
    # Normalize code
    code = code.upper().strip().replace('-', '')
    
    # Re-add hyphen format for lookup
    if len(code) >= 6 and '-' not in code:
        mid = len(code) // 2
        formatted_code = f"{code[:mid]}-{code[mid:]}"
    else:
        formatted_code = code
    
    invite = db_session.query(InviteCode).filter_by(code=formatted_code).first()
    
    if not invite:
        return False, "Invalid invite code", None
    
    if not invite.is_active:
        return False, "This invite code has been deactivated", invite
    
    if invite.is_expired:
        return False, "This invite code has expired", invite
    
    if invite.uses_count >= invite.max_uses:
        return False, "This invite code has already been used", invite
    
    return True, "Valid invite code", invite


def redeem_invite_code(
    code: str,
    user_id: str,
    db_session
) -> tuple[bool, str, Optional[InviteCode]]:
    """
    Redeem an invite code for a user.
    
    Args:
        code: The invite code to redeem
        user_id: User ID redeeming the code
        db_session: SQLAlchemy session
        
    Returns:
        Tuple of (success: bool, message: str, invite_code: InviteCode or None)
    """
    is_valid, message, invite = validate_invite_code(code, db_session)
    
    if not is_valid:
        return False, message, invite
    
    # Check if user already redeemed this code
    if user_id in (invite.used_by or []):
        return False, "You have already used this invite code", invite
    
    # Update the invite
    invite.uses_count += 1
    if invite.used_by is None:
        invite.used_by = []
    invite.used_by.append(user_id)
    
    # Auto-deactivate if max uses reached
    if invite.uses_count >= invite.max_uses:
        invite.is_active = False
    
    db_session.commit()
    
    return True, f"Invite code redeemed successfully. Role granted: {invite.role}", invite


def get_organization_codes(
    organization_id: str,
    db_session,
    include_inactive: bool = False
) -> list[InviteCode]:
    """
    Get all invite codes for an organization.
    
    Args:
        organization_id: Organization to lookup
        db_session: SQLAlchemy session
        include_inactive: Whether to include deactivated/expired codes
        
    Returns:
        List of InviteCode objects
    """
    query = db_session.query(InviteCode).filter_by(organization_id=organization_id)
    
    if not include_inactive:
        query = query.filter_by(is_active=True)
    
    return query.order_by(InviteCode.created_at.desc()).all()


def deactivate_invite_code(code: str, db_session) -> bool:
    """
    Deactivate an invite code.
    
    Args:
        code: Code to deactivate
        db_session: SQLAlchemy session
        
    Returns:
        True if deactivated, False if not found
    """
    invite = db_session.query(InviteCode).filter_by(code=code.upper()).first()
    
    if not invite:
        return False
    
    invite.is_active = False
    db_session.commit()
    
    return True


def get_code_stats(code: str, db_session) -> Optional[dict]:
    """
    Get statistics about an invite code.
    
    Args:
        code: Code to get stats for
        db_session: SQLAlchemy session
        
    Returns:
        Dict with code stats or None if not found
    """
    invite = db_session.query(InviteCode).filter_by(code=code.upper()).first()
    
    if not invite:
        return None
    
    return {
        "code": invite.code,
        "role": invite.role,
        "organization": invite.organization_name,
        "max_uses": invite.max_uses,
        "uses_count": invite.uses_count,
        "remaining_uses": invite.remaining_uses,
        "is_active": invite.is_active,
        "is_expired": invite.is_expired,
        "is_valid": invite.is_valid,
        "expires_at": invite.expires_at.isoformat() if invite.expires_at else None,
        "created_at": invite.created_at.isoformat(),
        "used_by": invite.used_by or [],
    }
