"""Campaign module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(FunctionGroupContract(
    module="campaign",
    group_name="campaign_launch_campaign",
    title="Campaign Launch Campaign (POST) (SSOT)",
    description="POST /launch",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.campaign.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="campaign",
    group_name="campaign_campaign_status",
    title="Campaign Get Campaign Status (GET) (SSOT)",
    description="GET /status/{campaign_id}",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.campaign.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="campaign",
    group_name="campaign_campaigns",
    title="Campaign List Campaigns (GET) (SSOT)",
    description="GET /list",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.campaign.router",),
    deterministic=True,
))

register_function_group(FunctionGroupContract(
    module="campaign",
    group_name="campaign_quick_file_complaint",
    title="Campaign Quick File Complaint (POST) (SSOT)",
    description="POST /quick-file",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.campaign.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="campaign",
    group_name="campaign_quick_analyze_fraud",
    title="Campaign Quick Analyze Fraud (POST) (SSOT)",
    description="POST /quick-analyze",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.campaign.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="campaign",
    group_name="campaign_quick_generate_press",
    title="Campaign Quick Generate Press (POST) (SSOT)",
    description="POST /quick-press",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.campaign.router",),
    deterministic=False,
))

register_function_group(FunctionGroupContract(
    module="campaign",
    group_name="campaign_health",
    title="Campaign Campaign Health (GET) (SSOT)",
    description="Health check for campaign service",
    inputs=(),
    outputs=("result",),
    dependencies=("app.modules.campaign.router",),
    deterministic=True,
))
