"""Crawler module registration helper — FunctionGroupContracts.

Auto-generated by _generate_contracts.py.
"""

from app.core.module_contracts import FunctionGroupContract, register_function_group

register_function_group(
    FunctionGroupContract(
        module="crawler",
        group_name="crawler_sources",
        title="Crawler List Sources (GET) (SSOT)",
        description="List all available data sources.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.crawler.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="crawler",
        group_name="crawler_source",
        title="Crawler Get Source (GET) (SSOT)",
        description="Get details about a specific source.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.crawler.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="crawler",
        group_name="crawler_crawl_url",
        title="Crawler Crawl Url (POST) (SSOT)",
        description="Crawl a single URL.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.crawler.router",),
        deterministic=False,
    )
)

register_function_group(
    FunctionGroupContract(
        module="crawler",
        group_name="crawler_search",
        title="Crawler Search (GET) (SSOT)",
        description="GET /search",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.crawler.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="crawler",
        group_name="crawler_search_statutes",
        title="Crawler Search Statutes (GET) (SSOT)",
        description="GET /search/statutes",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.crawler.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="crawler",
        group_name="crawler_search_business",
        title="Crawler Search Business (GET) (SSOT)",
        description="GET /search/business",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.crawler.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="crawler",
        group_name="crawler_search_property",
        title="Crawler Search Property (GET) (SSOT)",
        description="GET /search/property",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.crawler.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="crawler",
        group_name="crawler_search_legal_aid",
        title="Crawler Search Legal Aid (GET) (SSOT)",
        description="GET /search/legal-aid",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.crawler.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="crawler",
        group_name="crawler_statute",
        title="Crawler Get Statute (GET) (SSOT)",
        description="GET /statute/{chapter}",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.crawler.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="crawler",
        group_name="crawler_tenant_rights_statutes",
        title="Crawler Get Tenant Rights Statutes (GET) (SSOT)",
        description="Get all key Minnesota tenant rights statutes.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.crawler.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="crawler",
        group_name="crawler_ethics_policy",
        title="Crawler Get Ethics Policy (GET) (SSOT)",
        description="Get the crawler's ethics policy.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.crawler.router",),
        deterministic=True,
    )
)

register_function_group(
    FunctionGroupContract(
        module="crawler",
        group_name="crawler_clear_cache",
        title="Crawler Clear Cache (DELETE) (SSOT)",
        description="Clear the crawler cache.",
        inputs=(),
        outputs=("result",),
        dependencies=("app.modules.crawler.router",),
        deterministic=False,
    )
)
